### ISSUE TITLE
no effect

### ISSUE THREAD

**Issue by twonth** [moudey/shell#1]
I love the idea behind this software but I can't seem to get it to run

I downloaded Shell (the 64-bit version), ran the exe as an admin and hit the Register button. The registration was reported as successful and I restarted Explorer. But my context menu is unchanged. I also tried replacing the shell.shl file with the Hello World example and redid all the steps: still no result. Any idea what I could be doing wrong?

I'm on Windows 11 22000.376.

**Comment by moudey** [comment]
Please give me the value of the registry key after Shell registration

"HKEY_CURRENT_USER\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32"

**Comment by asakurato** [comment]
So it seems like I have this problem too. When I check that path in regedit, there is no folder with that name, so that's probably why shell doesn't work. The screenshot is after registering and restarting the explorer.
![image](https://user-images.githubusercontent.com/20476454/147105219-5f93b72c-e489-47b2-8b13-260c5c601897.png)

**Comment by moudey** [comment]
> So it seems like I have this problem too. When I check that path in regedit, there is no folder with that name, so that's probably why shell doesn't work. The screenshot is after registering and restarting the explorer.
> ![image](https://user-images.githubusercontent.com/20476454/147105219-5f93b72c-e489-47b2-8b13-260c5c601897.png)
> 

Is it the modern context menu that appears or legacy?

**Comment by asakurato** [comment]
> > So it seems like I have this problem too. When I check that path in regedit, there is no folder with that name, so that's probably why shell doesn't work. The screenshot is after registering and restarting the explorer.
> > ![image](https://user-images.githubusercontent.com/20476454/147105219-5f93b72c-e489-47b2-8b13-260c5c601897.png)
> 
> Is it the modern context menu that appears or legacy?

It's modern, like nothing has changed after registering. Old context menu also doesn't have anything new.

**Comment by moudey** [comment]
It works fine on version 22000.318

![w11 22000 318](https://user-images.githubusercontent.com/39198/147121763-53d1ae4e-0254-485d-952c-d3b3092b6d8d.png)

We will review those keys in the system registry to see if Shell is registered correctly

```
HKEY_CLASSES_ROOT\CLSID\{47535343-0064-434D-0000-000000000046}

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved
{47535343-0064-434D-0000-000000000046}

HKEY_CLASSES_ROOT\AllFilesystemObjects\shellex\ContextMenuHandlers\nilesoft.shell
{47535343-0064-434D-0000-000000000046}

HKEY_CLASSES_ROOT\Directory\Background\shellex\ContextMenuHandlers\nilesoft.shell
{47535343-0064-434D-0000-000000000046}

HKEY_CLASSES_ROOT\CLSID\{47535343-0064-494F-0000-000000000046}

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers\nilesoft.shell
{47535343-0064-494F-0000-000000000046}

```

**Comment by twonth** [comment]
Just like asakurato, I don't have {{86ca1aa0-34aa-4e8b-a509-50c905bae2a2} under HKEY_CURRENT_USER\Software\Classes\CLSID\ 

The registry keys mentioned in the last message do exist and (as far as I can tell) seem  configured correctly, in that I see entries for shell where I would expect.

Thanks for looking into this !

**Comment by moudey** [comment]
Hi everyone, 

This issue is resolved by changing the following Windows registry values by putting a minus sign in the first file path or deleting the value as you like as shown below.

```
[HKEY_CLASSES_ROOT\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32]
@="-C:\\Windows\\System32\\Windows.UI.FileExplorer.dll"

[HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InProcServer32]
@="-C:\\Windows\\SysWOW64\\Windows.UI.FileExplorer.dll"

[HKEY_CURRENT_USER\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32]
@="-C:\\Windows\\System32\\Windows.UI.FileExplorer.dll"
```

**Comment by moudey** [comment]
After applying the change of Registry values, you must restart the File Explorer by pressing Restart Explorer button
