### ISSUE TITLE
Disable the rounded corners

### ISSUE THREAD

**Issue by Marvinoo** [moudey/shell#10]
The new `modern_dark` theme is really nice but is there anyway to reduce or disable the rounded corners? Some people like me hate the rounded corners and prefer squared corners instead.

**Comment by moudey** [comment]
You can disable the round corner by set false in place of radius
```
def {
    //frame=[border color, border size (0:10), radius (true:false), opacity (0:100)]
    frame = [default, 0, false]
}
```

**Comment by moudey** [comment]
The corner radius value has been changed in the next update to the following values:
```
0 = disable
1 = small
2 = large
```
