### ISSUE TITLE
Windows install with MSI added some invalid menu options

### ISSUE THREAD

**Issue by enkelmedia** [moudey/Shell#100]
Hi!

Thanks for a really great utility!

Just wanted to help out and report some issues I experienced when installing v1.7 on Windows 11.

**VSCode**
The command to open VSCode was added as `code.exe` which did not work, but when I changed it to just `code` it did work. For me it's the same in powershell or cmd, `code` works while `code.exe` does not. 

**Nodepad3**
Notepad3 was added as a editor but I don't have this installed on my machine

![image](https://user-images.githubusercontent.com/1782524/212433112-151f72dc-fbaf-47d3-a450-ec7a4b32c6f2.png)

**Comment by moudey** [comment]
Thank you, @enkelmedia . The configuration file has been modified to remove "Notepad3" item because it is not used by many people. and change vscode to "code"
