### ISSUE TITLE
Can't see the Shell menu when Right clicking task bar

### ISSUE THREAD

**Issue by NetBod** [moudey/Shell#101]
HI
I saw 1.8 had been release so did an upgrade to it, after that upgrade I do no see the shell menu when right clicking the task bar in windows, was working ok till the up grade. I see in the NSS file that a taskbar .nss is called but looks like that's not working. I can see the menus if right click on the desktop thou. 
How do I get the menu back when right clicking the taskbar.
Thanks

**Comment by HenryBaby** [comment]
I experienced the same issue while also running ExplorerPatcher. Uninstalling EP fixed it. Would be nice if Shell could work alongside EP :-)

**Comment by NetBod** [comment]
Win 11 version 22H2 (OS Build 25276.1000) nothing installed to modify the taskbar. I was running the version u posted in issue #57 and had no issue with that, only started when upgrade to the new 1.8 version posted, you have added a few things since then  around NSS files. Is there anyway of getting any error out of Shell to see why its not loading the task bar menu.

**Comment by moudey** [comment]
Tested on this build 25276.1000 with two monitors and it works fine with Taskbar

**Comment by moudey** [comment]
@NetBod Did you modify the config file?

**Comment by Dean-Corso** [comment]
I also have some issues to get to see everything like that taskbar items. Is it just showing for Windows 11 users only? I'am using Win 10 and I can see this in the shell.nss...
```
	dynamic
	{
		menu(mode="multiple" title="Pin/Unpin" image=icon.pin) { }
		menu(mode="multiple" title=title.more_options image=icon.more_options) { }
		
		import 'imports/terminal.nss'
		import 'imports/file-manage.nss'
		import 'imports/develop.nss'
		import 'imports/goto.nss'
		
		menu(type="taskbar" vis=key.shift() pos=0 title=app.name image=\uE249)
		{
			item(title="config" image=\uE10A cmd='"@app.cfg"')
			item(title="manager" image=\uE0F3 admin cmd='"@app.exe"')
			item(title="directory" image=\uE0E8 cmd='"@app.dir"')
			item(title="version\t"+@app.ver vis=label col=1)
			item(title="docs" image=\uE1C4 cmd='https://nilesoft.org/docs')
			item(title="donate" image=\uE1A7 cmd='https://nilesoft.org/donate')
		}
		
		import if(isw11, 'imports/taskbar.nss')  <--- This check
	}
```
Why this check? Is it a mistake or anything you forgot to remove? Just don't see any reason why just using this import on Win 11 only because all of the apps are also present and to execute on Win 10 same. In my case I don't get anything from "taskbar.nss" content to see. Maybe you can check & fix this so I would also like to have this menu points and taskbar right click. In the terminal.nss is also a check...
`item(where=sys.ver.major >= 10 title=title.Windows_Terminal admin=key.shift() image='@package.path("WindowsTerminal")\WindowsTerminal.exe' cmd='wt.exe' arg='-d "@sel.path\."')`
...if version higher / equal 10 and here I get showing just a empty menu entry instead of showing just 2. I don't have wt.exe on Win 10. Just remove the "=" sign in code to make it the empty entry for Win 10 disappear. Just try to check all nss files one more time with some little more attention and fix all wrong written code lines and then release a new fixed version of your app we all can download and try again to prevent another manually edits in default files etc and to have a clean portable / installer packages. Just keep going @moudey with that nice app.

**Comment by moudey** [comment]
@Dean-Corso 
All items, whether static or dynamic, are just examples to help you create your own menu.
The configuration files will be uploaded to the repository for improvement.

**Comment by NetBod** [comment]
Hi, So I have got it working, how well no idea, but did not remove or change any programs on the PC. What I did was this.
As I could not get the installed version to work after removing and installing  many time, as a last restore I tried the portable version, and to my surprise that worked, slight issue thou that I found that once the portable version was registered I could still not access the Shell menu from the Taskbar until I had accessed on the desktop via right click, once that was done a right click on the Taskbar worked. 
So I decided to remove the installed version again and install one last time. So removed it, rebooted, checked with Promon that  the shell.dll was not installed, once checked reboot again.
Once the PC came up I ran the Shell 1.8 install app, after that finished rebooted PC.
After PC came back up a right click on the Taskbar did not work, so right click desktop and could see Shell was install and working on the desk top as it had been, retried a right click on the Taskbar and it worked I could see the Shell menus. I have also add my app list code to the Tackbar.nss file and that works as well, can see it in the menu etc.
As for your question re config file, no I had not change the config file when I could not get it to work was just installing and uninstalling the app each time.
Its a nice app, and dose what I was looking for, but seem to be a bit temperamental.
Couple of thing, really could do with some sort of debug log to help with PD when it dose  not work to help the end user to fix issue they may hit, also update documentation on the web site would be good so we have some points of reference around the config files  and how they interact with each other.
Thanks for the App

**Comment by moudey** [comment]
@NetBod Before installing version 1.8 did you unregister previous version?

**Comment by NetBod** [comment]
yes I did, and checked it was not in use via procexp, also the issue I describe above about having to right click desktop before right on task bar will work, I also see that issue on restart and shutdown/turn on of the PC, very strange.

**Comment by juliocoliveira** [comment]
I saw that once I boot up windows and Right Click on the Taskbar it does not show up the custom menu, But once I open explorer, it does show up. On Windows 11 using the latest shell version 1.8

**Comment by moudey** [comment]
Now, the issue became clear.

**Comment by krilok** [comment]
I'm running ExplorerPatcher 22621.819.52.2 alongside Shell 1.8, and if  

> I experienced the same issue while also running ExplorerPatcher. Uninstalling EP fixed it. Would be nice if Shell could work alongside EP :-)

I'm running ExplorerPatcher 22621.819.52.2 alongside Shell 1.8 myself, and indeed the shell menu when right clicking the taskbar is blank, but only if you set the taskbar style on ExplorerPatcher to Windows 11. If you set it to Windows 10, then the shell menu will show when right clicking taskbar.

However, if ExplorerPatcher is not running or if you uninstall it completely, then shell menu on taskbar will show without issues with the Windows 11 default taskbar...

**Comment by HenryBaby** [comment]
> I'm running ExplorerPatcher 22621.819.52.2 alongside Shell 1.8, and if
> 
> > I experienced the same issue while also running ExplorerPatcher. Uninstalling EP fixed it. Would be nice if Shell could work alongside EP :-)
> 
> I'm running ExplorerPatcher 22621.819.52.2 alongside Shell 1.8 myself, and indeed the shell menu when right clicking the taskbar is blank, but only if you set the taskbar style on ExplorerPatcher to Windows 11. If you set it to Windows 10, then the shell menu will show when right clicking taskbar.
> 
> However, if ExplorerPatcher is not running or if you uninstall it completely, then shell menu on taskbar will show without issues with the Windows 11 default taskbar...
> 
> So looks like there's some sort of clash between both apps, and second HenryBaby's comment; it would be nice to have them both working alongside...

I actually had another approach to this, but in the end it achieves the same thing as outlined by you. Disabling the hook within EP that puts a menu option for EP's properties in taskbar right click also solved it, which again, makes sense as you outlined it.

Now I just use the applications own shortcut to reach its properties instead. And I suppose that could even be configured as an option in Shell.

**Comment by krilok** [comment]
> > I'm running ExplorerPatcher 22621.819.52.2 alongside Shell 1.8, and if
> > > I experienced the same issue while also running ExplorerPatcher. Uninstalling EP fixed it. Would be nice if Shell could work alongside EP :-)
> > 
> > 
> > I'm running ExplorerPatcher 22621.819.52.2 alongside Shell 1.8 myself, and indeed the shell menu when right clicking the taskbar is blank, but only if you set the taskbar style on ExplorerPatcher to Windows 11. If you set it to Windows 10, then the shell menu will show when right clicking taskbar.
> > However, if ExplorerPatcher is not running or if you uninstall it completely, then shell menu on taskbar will show without issues with the Windows 11 default taskbar...
> > So looks like there's some sort of clash between both apps, and second HenryBaby's comment; it would be nice to have them both working alongside...
> 
> I actually had another approach to this, but in the end it achieves the same thing as outlined by you. Disabling the hook within EP that puts a menu option for EP's properties in taskbar right click also solved it, which again, makes sense as you outlined it.
> 
> Now I just use the applications own shortcut to reach its properties instead. And I suppose that could even be configured as an option in Shell.

Thank you for the response... Would it be possible for you to guide me on how you disabled the hook?

**Comment by HenryBaby** [comment]
> Thank you for the response... Would it be possible for you to guide me on how you disabled the hook?

Of course! Go into EP settings > Advanced, and enable the option called Do not change the taskbar context [...]

**Comment by krilok** [comment]
> > Thank you for the response... Would it be possible for you to guide me on how you disabled the hook?
> 
> Of course! Go into EP settings > Advanced, and enable the option called Do not change the taskbar context [...]

Thank you for the guidance. On EP version 22621.605.51.6, there's no ''Do not change the taskbar context...'' option you mentioned, but instead there's ''Hide the program settings item (''Properties'') from the taskbar context menu'', which I assume is the same thing?

Anyhow, I tried toggling this, but unfortunately, I still get a blank Shell menu when I apply Windows 11 taskbar style in EP.

**Comment by jxolotl** [comment]
https://github.com/valinet/ExplorerPatcher/blob/7c4567ac799ceaed8fbb582d1e232dfacfa3c354/CHANGELOG.md#1

> Windows 11 taskbar: Option to use the stock taskbar context menu. (451db3c)

Update your ExplorerPatcher to at least `22621.819.52`: https://github.com/valinet/ExplorerPatcher/releases

**Comment by krilok** [comment]
> @krilok https://github.com/valinet/ExplorerPatcher/blob/7c4567ac799ceaed8fbb582d1e232dfacfa3c354/CHANGELOG.md#1
> 
> > Windows 11 taskbar: Option to use the stock taskbar context menu. (451db3c)
> 
> Update your ExplorerPatcher to at least `22621.819.52`: https://github.com/valinet/ExplorerPatcher/releases

Thank you... Updated to EP 22621.819.52, and after activating ''Do not change the the taskbar context menu'' option under EP's Advanced options, I now get the context menu while maintaining the Windows 11 taskbar style...

**Comment by jxolotl** [comment]
@moudey Perhaps you can check for the following registry keys and offer compatibility suggestion in GUI (once Shell has one):

- `HKEY_CURRENT_USER\Software\ExplorerPatcher` - `NoPropertiesInContextMenu` (`DWORD`)
    - When set to 1, ExplorerPatcher's taskbar context menu is disabled
    - This requires at least version `22621.819.52` for ExplorerPatcher
- `HKEY_CURRENT_USER\Software\ExplorerPatcher` - `OldTaskbar` (`DWORD`)
    - When set to 1, Windows 10 style taskbar is used, and Shell context menu works regardless of `NoPropertiesInContextMenu`

**Comment by moudey** [comment]
Hi all, I try as much as possible to make the Shell compatible with 3rd party software. I will make time to eliminate this issue 👊

**Comment by krilok** [comment]
> Hi all, I try as much as possible to make Shell compatible with 3rd party software. I will make time to eliminate this issue 👊

Thank you very much for your efforts... 😉

**Comment by moudey** [comment]
Hi all,
Please test this [build](https://github.com/moudey/Shell/files/10611265/shell-test.zip)

**Comment by moudey** [comment]
> Thank you for the update. Tried it but unfortunately, same results...

Please unregister previous versions.
If the issue persists, attach the "shell.log" file.

**Comment by krilok** [comment]
> > Thank you for the update. Tried it but unfortunately, same results...
> 
> Please unregister previous versions. If the issue persists, attach the "shell.log" file.

Unregistered shell, replaced files with the ones from the zip, but still same blank context menu. Where would the log file be? I don't see it within the shell folder... Is it the ''shell'' txt document?

**Comment by moudey** [comment]
> Where would the log file be? I don't see it within the shell folder... Is it the ''shell'' txt document?

`shell.log` You can find it in the shell folder

Screenshot of a working Shell with Explorer Patcher
![ep](https://user-images.githubusercontent.com/39198/217045271-ae757ec2-3976-4beb-913e-eda9451b1322.png)

**Comment by krilok** [comment]
> > Where would the log file be? I don't see it within the shell folder... Is it the ''shell'' txt document?
> 
> `shell.log` You can find it in the shell folder
> 
> Screenshot of a working Shell with Explorer Patcher ![ep](https://user-images.githubusercontent.com/39198/217045271-ae757ec2-3976-4beb-913e-eda9451b1322.png)

![No log file](https://user-images.githubusercontent.com/38211404/217048016-58719b8d-0b8b-4980-bdf0-b53096683856.png)

No log file within the folder...

**Comment by moudey** [comment]
first file

**Comment by krilok** [comment]
> first file

[shell.log](https://github.com/moudey/Shell/files/10667757/shell.log)

**Comment by moudey** [comment]
Set the effect to 1 and tell me the result
```
theme
{
    background
    {
        effect = 1
        opacity=50
    }
}
```

**Comment by krilok** [comment]
> Set the effect to 1 and tell me the result
> 
> ```
> theme
> {
>     background
>     {
>         effect = 1
>         opacity=50
>     }
> }
> ```

Set the above, but context menu on taskbar is still blank, though on any other spot the context menu shows up, although slightly transparent (guess it's because of opacity=80 on the nss file settings)

**Comment by moudey** [comment]
>Also noticed; on your screenshot you're using the Windows10 style on EP, right? With that style set I don't have any issues either...

Well, the issue appeared now after changing the style to windows 11

**Comment by krilok** [comment]
> > Also noticed; on your screenshot you're using the Windows10 style on EP, right? With that style set I don't have any issues either...
> 
> Well, the issue appeared now after changing the style to windows 11

Yes, seems to only apply while using this style... 😉

**Comment by moudey** [comment]
Shell works fine when you use `Menu` key or `Shift` + `F10`

**Comment by moudey** [comment]
Hi @krilok test this [build](https://github.com/moudey/Shell/files/10673840/shell-test.zip)
First rename `shell.dll` to `shell.dll.old` then extract `shell-test.zip/shell.dll` then restart explorer

**Comment by krilok** [comment]
> Hi @krilok test this [build](https://github.com/moudey/Shell/files/10673840/shell-test.zip) First rename `shell.dll` to `shell.dll.old` then extract `shell-test.zip/shell.dll` then restart explorer

Thank you. Tried it and working fine, and context menu does indeed appear now with the Win11 style active on EP. However, EP's taskbar properties option doesn't appear any longer, but that's OK; I can still access EP's settings through the start menu...

**Comment by moudey** [comment]
>EP's taskbar properties option doesn't appear any longer, but that's OK; I can still access EP's settings through the start menu...

Add this item to `imports/taskbar.nss`
```
item(type='taskbar' title='EP Properties ' cmd='rundll32' args='@sys.dir\dxgi.dll,ZZGUI')
```

**Comment by krilok** [comment]
> > EP's taskbar properties option doesn't appear any longer, but that's OK; I can still access EP's settings through the start menu...
> 
> Add this item to `imports/taskbar.nss`
> 
> ```
> item(type='taskbar' title='EP Properties ' cmd='rundll32' args='@sys.dir\dxgi.dll,ZZGUI')
> ```

Thank you, this fixes it. I now see the EP Properties option (no icon though)...
