### ISSUE TITLE
Terminal.nss syntax causes blank menu title (v1.8)

### ISSUE THREAD

**Issue by kontosa** [moudey/Shell#102]
![image](https://user-images.githubusercontent.com/102735221/212704678-9336a454-a90d-406d-b9d0-a6b7cd6d26cb.png)

If I change 1st line e.g. to '... title='Terminals' ...' then it works. 

`menu(type='*' where=(sel.count or wnd.is_taskbar or wnd.is_edit) title='Terminals' sep='top' image=icon.run_with_powershell)`

![image](https://user-images.githubusercontent.com/102735221/212704268-38b42cfb-6d59-4630-b899-6c5249926dd0.png)

**Comment by SaiyajinK** [comment]
No problem on 22H2... but problem on 21H2 : 
FIX with : 

```
menu(type='*' where=(sel.count or wnd.is_taskbar or wnd.is_edit) title=id.terminal.title sep='top' image=icon.run_with_powershell)
{
	item(title=id.command_prompt.title admin=key.shift() image cmd='cmd.exe' args='/K TITLE Command Prompt &ver& PUSHD "@sel.dir"')
	item(title=id.windows_powershell.title admin=@key.shift() image cmd='powershell.exe' args='-noexit -command Set-Location -Path "@sel.dir\."')
	item(where=sys.ver.major >= 10 title=id.Windows_Terminal.title image='@package.path("WindowsTerminal")\WindowsTerminal.exe' cmd='wt.exe' arg='-d "@sel.path\."')
}
```

**Comment by SaiyajinK** [comment]
selection menu also not working on 21h2 but working on 22h2.
this stable version is more "unstable" than the last beta that I could test, it's strange

**Comment by moudey** [comment]
Please replace the title property value with `id.select.title`

**Comment by SaiyajinK** [comment]
> Veuillez remplacer la valeur de propriété du titre par `id.select.title`

If I replace the title with **id.select.title** it's not working. when I click on "select all" "invert the selection ", "select none" nothing happens (under 21h2 build 22000.1455 and 22H2 build 22621.1105)

after careful consideration I decided to remove this menu, technically it is not "useful" for me so I can do without it 👍

**Comment by moudey** [comment]
>If I replace the title with id.select.title it's not working. when I click on "select all" "invert the selection ", "select none" nothing happens (under 21h2 build 22000.1455 and 22H2 build 22621.1105)

These items have been tested on Windows 7, 10, 11. And it worked on desktop and file explorer

**Comment by moudey** [comment]
@Dean-Corso 
>Where can I find a list of all those commands you do use for cmd=? Any full list?

The documentation for version 1.8 is currently being updated.  Commands will fall under command scope

>PS: On my system is no shell.shl to find.

In version 1.8, the extension of "shell.shl" file was changed to "shell.nss".

**Comment by kontosa** [comment]
If I replace the title with id.select.title then the menu works (Win11, 21H2) - but the menu text is 'Select'. Not sure that makes sense for terminals?
Also, for the Powershell submenu option, you should not need any args (nothing fter cmd='powershell.exe') as:
- it works without those args 
- the Set-Location errors when there is a space in the sel.dir (even though the correct path is set once powershell opens)
