### ISSUE TITLE
SD card format.

### ISSUE THREAD

**Issue by Natejoestev** [moudey/Shell#103]
The `Format` option doesn't show by default whilst using Shell.
![image](https://user-images.githubusercontent.com/85044853/212788074-18ffbfb6-ea44-4ede-bb3a-a4cf6eda78c0.png)
(it is still under the `...` at the top while selecting the drive though.)

**Comment by moudey** [comment]
Please refer to this [topic](https://github.com/moudey/Shell/discussions/73)
