### ISSUE TITLE
Long context menu support

### ISSUE THREAD

**Issue by krystofkrticka** [moudey/shell#105]
Hello, today I installed shell but I'm unable to see all context menu entries because my context menu is too long. So scrolling context menu or something like windows has by default when you context menu won't fit on your screen would be useful.

Some of icons where pushed of to more options section but some disappeared completely. 

| This is how long context menu looks with shell enabled: | This is how long context menu looks when just restored and tweaked by StartAllBack: |
|---|---|
| ![2023-01-17_10-59-12](https://user-images.githubusercontent.com/37749100/212869027-ed1e39eb-190e-4884-bd6c-9ee6749791b1.png) | ![2023-01-17_11-01-19](https://user-images.githubusercontent.com/37749100/212869350-795bdbc3-6f80-4266-85d6-aa9c3481fb40.png) |

**Comment by moudey** [comment]
it's too too too long,

You can shorten it by moving items to a submenu, for example

add this code to `static` section

```
item (find='winamp|git|insync|powerrename|sign and encrypt' menu="more options")
```

Or you can long press in an empty place below the context menu and it will scroll the items.

**Comment by krystofkrticka** [comment]
@moudey Thank you! Though that there would be a way but without updated docs there is not much I can do.
