### ISSUE TITLE
Remove Context Menu Checkmark

### ISSUE THREAD

**Issue by Tristanslayer** [moudey/Shell#106]
![image](https://user-images.githubusercontent.com/16424516/212993421-837cc7d7-97f6-403a-b9ca-1d7051c32935.png)
Hello, thank you for your wonderful work. May I ask if it is possible to remove the checkmark (basically the empty space at the left)?

**Comment by moudey** [comment]
Hi @Tristanslayer

In the `theme` section change `image.align` value to 0

```
set {
    theme {
        image.align = 0
    }
}
```

**Comment by moudey** [comment]
The static item is provided with a `checked` property to change the checked state.

**Comment by Tristanslayer** [comment]
Thank you very much, it worked.
