### ISSUE TITLE
Please add releases info / rss feed about updates

### ISSUE THREAD

**Issue by Dean-Corso** [moudey/Shell#107]
Hi @moudey,

just have a little question / request. So I see you don't have created any releases page on your project and you just pointing us to your website to download your app. Just wanna ask whether you have any rss feed on your webpage or if not could you add any on your website or on this project site? Just to check for updates from outside of the browser. I'am using a RSS tool and check different channels on internet & github too...like this...
`https://github.com/portapps/brave-portable/releases.atom`
...to see new updates without to visit every single channel manually. Would be nice if you could add any I can check for. A simple info about new version XY is released is ok. Thanks.

**Comment by moudey** [comment]
@Dean-Corso 
Thank you for your feedback.

I will work on that in updating the site.
You can use this link to check the latest shell version: https://nilesoft.org/shell/version

**Comment by Dean-Corso** [comment]
@moudey,

Ok thanks but make a rss feed on your site or here which I can include in my RSS tool. I have many rss channels to check everyday (+20 on github) and I do not check every single URL manually for this you know. In a rss tool you can check all rss channels right away without to visit any website to get the actually status. Just look...
![rss_2023-01-17_220514](https://user-images.githubusercontent.com/88513086/213012478-9c8df6c4-66b6-4aba-866f-46f5b36ec6c6.png)
....pretty simple to get all update states of any github projects who also using the releases page itself. If you don't wanna share your source then you can still using the releases page to put your installer / portable packages into or just a info about the update XY and then I can use this page as rss feed what github supports already. Otherwise if you don't like this then just do it on your website later if possible so that would be better for users like me who using rss tools. Thank you.

**Comment by moudey** [comment]
Hi @Dean-Corso 

Please use these feed channels

releases 
https://nilesoft.org/feed/releases

news 
https://nilesoft.org/feed/new

all
https://nilesoft.org/feed
