### ISSUE TITLE
Shell does not respect MenuShowDelay value

### ISSUE THREAD

**Issue by Raymai97** [moudey/shell#11]
First of all, thank you for this awesome project! I just started using this extender and already loving it.
However I found something is wrong with the submenu opening speed. It opens too fast.
It is as the "MenuShowDelay" value in "HKEY_CURRENT_USER\Control Panel\Desktop" has been set to zero.
![Animation2](https://user-images.githubusercontent.com/3296077/168467217-278c6679-90fd-4eaa-bd71-49f44c7020ad.gif)

If I unregister Shell DLL, log off and on, the issue disappears.
As soon as I register Shell DLL, the issue appears again.
This issue is system-global.
It would affect OpenShell submenu opening speed as well.

Can we make Shell respect the "MenuShowDelay" value?

**Comment by moudey** [comment]
Yes, MenuShowDelay is set to zero during registration.  An option to control this feature will be added in the next update.

**Comment by moudey** [comment]
@Raymai97 The option to control the value of show menu delay has been added, and it is immediately applied to Shell only

```
shell {
    default {
        showdelay = 200
    }
}
```
