### ISSUE TITLE
1. bug or not? /2. shell no longer loads after adding a remove function in static.nss

### ISSUE THREAD

**Issue by SaiyajinK** [moudey/Shell#117]
Hi @moudey 

I have two questions please :+1: 

I removed from the context menu the NVIDIA control panel with the remove function (vis.remove) in the static.nss file

`item(type='desktop' find='Panneau de configuration NVIDIA' vis=vis.remove)`

The entry is deleted and no longer appears in the context menu.

I created a page (nvidia.nss) to create a menu with the control panel and the nvidia geforce experience

![iNZXuxyr7K](https://user-images.githubusercontent.com/105972098/213459954-155fe39e-fe37-4b37-b375-98380eafec35.png)

Except that the line to launch **nvcplui.exe** doesn't launch anything (but it works if I create a shortcut and point to it)
yet it is the exact path without error (I checked several times)

do you have a solution ? (because I don't know if it's a bug or if I'm doing something wrong!)

---------------------

second question, do you have a solution to remove from the context menu of the taskbar the entry "Toolbars" 

![bvl8OxwCmy](https://user-images.githubusercontent.com/105972098/213462048-dbffd5ed-d4ab-4f73-ae4c-28a64c8d7890.png)

because when I add this line to the file static.nss shell no longer loads at all:

`item(type='taskbar' find='Barres d'outils' vis=vis.remove)`

![v5aTFwpW73](https://user-images.githubusercontent.com/105972098/213468114-de8ebacf-36bd-409b-8852-9f2cda8664f7.png)

maybe it's not possible, I don't know ?

thank you for your feedback ++

**Comment by moudey** [comment]
1. Make the execution of the command through the operating shortcut instead of the direct command.

2. Replace the single quotes with the double quotes

`find="Barres d'outils"`

**Comment by SaiyajinK** [comment]
> 1. Effectuez l'exécution de la commande via le raccourci de fonctionnement au lieu de la commande directe.
> 
>     2. Remplacez les guillemets simples par les guillemets doubles
> 
> 
> `find="Barres d'outils"`

yes I will use with the shortcut! :+1: 

for the taskbar item, I'm stupid it was only a quotation mark question, so I modified, shell loads fine but the item remains present :

![CVqZEk5qUJ](https://user-images.githubusercontent.com/105972098/213568578-2faee9c4-af32-4b9c-ba21-afa1de73cee8.png)

I also noticed that on some item, when I try to apply a custom icon it doesn't work either I show you:

![14AEernsC7](https://user-images.githubusercontent.com/105972098/213569330-ef3a7186-ba27-4822-888f-6b565325f5e9.png)

do you know why ?

**Comment by moudey** [comment]
For Win+X menu

```
item(type='*' where=window.is_start find="system" vis=vis.remove)
```

For the first question, use this function to run UWP app

```
@appx.shell("NVIDIACorp.NVIDIAControlPanel")
```

**Comment by hiranokite** [comment]
> For Win+X menu
> 
> ```
> item(type='*' where=window.is_start find="system" vis=vis.remove)
> ```
> 
> For the first question, use this function to run UWP app
> 
> ```
> @appx.shell("NVIDIACorp.NVIDIAControlPanel")
> ```

Can't get nvidia control panel to open, im doing something wrong?

`item(title='NVIDIA Control Panel' cmd=@appx.shell("NVIDIACorp.NVIDIAControlPanel") image=\uE260)`

The nvidia control panel is working from other shortcuts.

**Comment by SaiyajinK** [comment]
> For Win+X menu
> 
> ```
> item(type='*' where=window.is_start find="system" vis=vis.remove)
> ```
> 
> For the first question, use this function to run UWP app
> 
> ```
> @appx.shell("NVIDIACorp.NVIDIAControlPanel")
> ```

I just want to successfully integrate an icon on the WIN + X menu and not remove items !
I use the commands of usual but as I indicate some icon does not change and it does not put me anything while on others it works... it's really strange...
I was wondering if all this could have a direct / indirect interaction with StartAllBack that I use ?!


> Can't get nvidia control panel to open, im doing something wrong?
> 
> `item(title='NVIDIA Control Panel' cmd=@appx.shell("NVIDIACorp.NVIDIAControlPanel") image=\uE260)`
> 
> The nvidia control panel is working from other shortcuts.

same for me I have the same command line and nothing happens, shell loads fine but nothing launches

**Comment by hiranokite** [comment]
> > For Win+X menu
> > ```
> > item(type='*' where=window.is_start find="system" vis=vis.remove)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For the first question, use this function to run UWP app
> > ```
> > @appx.shell("NVIDIACorp.NVIDIAControlPanel")
> > ```
> 
> I just want to successfully integrate an icon on the WIN + X menu and not remove items ! I use the commands of usual but as I indicate some icon does not change and it does not put me anything while on others it works... it's really strange... I was wondering if all this could have a direct / indirect interaction with StartAllBack that I use ?!
> 
> > Can't get nvidia control panel to open, im doing something wrong?
> > `item(title='NVIDIA Control Panel' cmd=@appx.shell("NVIDIACorp.NVIDIAControlPanel") image=\uE260)`
> > The nvidia control panel is working from other shortcuts.
> 
> same for me I have the same command line and nothing happens, shell loads fine but nothing launches

got it to work, use this command
`item(title='NVIDIA Control Panel' cmd='shell:appsFolder\NVIDIACorp.NVIDIAControlPanel_56jybvy8sckqj!NVIDIACorp.NVIDIAControlPanel' image=\uE260)`
