### ISSUE TITLE
How can I add link shell extension to your "Shell"

### ISSUE THREAD

**Issue by bigplayer-ai** [moudey/Shell#119]
Hey,
How can I add link shell extension (symlink between folders) to your shell?
https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html

**Comment by moudey** [comment]
I have no idea now how this program works.
Please refer to this link https://schinagl.priv.at/nt/ln/ln.html

**Comment by moudey** [comment]
@TheChilliPL Can you help here about using LinkShellExtension
