### ISSUE TITLE
Windows 7 install troubleshooting

### ISSUE THREAD

**Issue by Virgus** [moudey/shell#12]
Hello moudey, I just discovered your tool now, despite I've been looking for something like this for years !

I just tried to install it onto my W7 Ultimate OS 64bit but I'm stuck.
I've read [here ](https://www.trishtech.com/2022/02/nilesoft-shell-easy-context-menu-extender-for-windows/) that other context-menu managers might interphere so I just tried to cleanup my system from whatever might bother but still I cannot see "Shell" in action.

Shell.log says "[info] Register completed successfully." but in reality either via CLI or via GUI all actions are unresponsive despite restarting explorer.exe manually or rebooting the PC.

I tried to register shell.dll manually via REGSRV32 but I got an error stating that the module "failed to load".

Besides what I've already cleaned, Is there a way to find out if other dlls are interphering with shell so that I can uninstall them completely ? Are there other possible reasons for shell not installing on W7U ?

Could you please help me troubleshooting this issue ?
I would really appreciate, thanks !
V.

**Comment by moudey** [comment]
Hi @Virgus, Supposedly compatible with Windows 7. In any case I will install a copy of Windows 7 to resolve any issues

**Comment by Virgus** [comment]
Thank you so much @moudey, this was the feature of XP that I missed the most since Vista ! Have a nice day, V.

**Comment by moudey** [comment]
This version [shell.zip](https://github.com/moudey/shell/files/8807969/shell.zip) has been improved and tested on Windows 7 version 6.1.7600

![w7](https://user-images.githubusercontent.com/39198/171276406-cd39d978-8de8-41c1-a6b4-b68e1746101c.png)
