### ISSUE TITLE
Print Option

### ISSUE THREAD

**Issue by sarathdm** [moudey/Shell#120]
How to Add Print Option in Context menu

**Comment by moudey** [comment]
Open the `/imports/static.nss` file located in **Shell** directory.
At the end of line number 7, find `, id.print`  delete it, and then restart File Explorer from Shell.exe

![print](https://user-images.githubusercontent.com/39198/213843173-c0573a5c-4061-4177-8105-3f9616cb42c9.png)

**Comment by sarathdm** [comment]
thanks
