### ISSUE TITLE
nothing start after system is powered on

### ISSUE THREAD

**Issue by sarathdm** [moudey/Shell#124]
no shell or original one is not working on after sysytem starts.....
i have to restart explorer every time after system on to work the shell....
Any idea how to fix this......

**Comment by moudey** [comment]
Attach file `shell.log`

**Comment by sarathdm** [comment]
[shell.log](https://github.com/moudey/Shell/files/10476529/shell.log)

**Comment by moudey** [comment]
There is an error in `goto.nss` file that I attached as well

`[error] line[1] column[6], Property unexpected "goto.nss"`

**Comment by sarathdm** [comment]
[goto.zip](https://github.com/moudey/Shell/files/10476712/goto.zip)

**Comment by moudey** [comment]
Syntax error in `where` property.   `||sel.count`
```
menu(type='*' where=!window.is_start && (!window.is_taskbar||sel.count)||sel.count mode=mode.multiple title='Goto' sep=sep.both image=\uE14A)
```
corrected
```
menu(type='*' where=!window.is_start && (!window.is_taskbar||sel.count) mode=mode.multiple title='Goto' sep=sep.both image=\uE14A)
```

**Comment by sarathdm** [comment]
ok

**Comment by sarathdm** [comment]
it still didn't fix not showing any menu when system is powered on or restarted unless i restart windows explorer process.
i don't know its shell problem or any other.....

**Comment by moudey** [comment]
Attach file shell.log

**Comment by sarathdm** [comment]
[shell.zip](https://github.com/moudey/Shell/files/10477132/shell.zip)

**Comment by moudey** [comment]
Temporarily disable "goto.nss" items from "shell.nss" file. 
restart explorer by this command `shell.exe -restart`

**Comment by sarathdm** [comment]
ok

**Comment by sarathdm** [comment]
it's still not fixed....
i think it's not shell problem
i think it's explorer problem
so lets check after another shell update....

**Comment by moudey** [comment]
1. Unregister Shell 
2. delete shell.log file 
3. restart explorer
4. register Shell 
5. Attach file shell.log and shell.nss

**Comment by sarathdm** [comment]
[shell.zip](https://github.com/moudey/Shell/files/10480163/shell.zip)

**Comment by moudey** [comment]
There are no errors in the "shell.nss"

Does a shell menu appear with the desktop?

Try "shell.nss" file without settings  file like below

```
shell
{
	set
	{
		theme
		{
			name="modern"
			image.align = 1
		}
		
		exclude.where = !process.is_explorer
		showdelay=200
	}

	static
	{	
	}

	dynamic
	{
	}
}
```

Unregister
restart explorer
register Shell
restart explorer

**Comment by sarathdm** [comment]
when i restart or power on the system.... No menu appers (context menu, taskbar or win+x menu)..... Only after i restart explorer.exe will it appears....

I tried "shell.nss" file without settings file and it works fine untill i restart the system.

**Comment by moudey** [comment]
Please test this [build](https://github.com/moudey/Shell/files/10611265/shell-test.zip)
