### ISSUE TITLE
Right click not working (v1.8)

### ISSUE THREAD

**Issue by Aman1337g** [moudey/Shell#126]
After installing shell **(v1.8)** , I have to restart the **File Explorer** process for right click to work . Also , in this new version how to remove the **shadow** animation.

**Comment by moudey** [comment]
To disable  shadow, go to `theme` section in `shell.nss` file and write the following code
```
shadow.enabled=false
```

save file, hold `shift`+`right-click` to reload or restart explorer.

**Comment by SaltireSoul** [comment]
1.8 seems to be broken on Windows 10.  As detailed [here](https://www.reddit.com/r/nilesoft/comments/10gqv3o/terminal_not_working/)

"Open /imports/terminal.nss file in Shell folder, then replace the title property value from title.terminal to id.terminal.title, save the file and restart file explorer".

I also adjusted the Windows Terminal line
from:
`item(where=sys.ver.major >= 10 title=title.Windows_Terminal admin=key.shift() image='@package.path("WindowsTerminal")\WindowsTerminal.exe' cmd='wt.exe' arg='-d "@sel.path\."')`

to:
`item(where=sys.ver.major >= 10 title='@appx.name("WindowsTerminal")@elevated' admin=key.shift() image='@package.path("WindowsTerminal")\WindowsTerminal.exe' cmd='wt.exe' arg='-d "@sel.path\."')`

**Comment by r-katabasis** [comment]
@Aman1337g I had the same problem, and I think it had to do with several instances of Shell being installed and conflicting with each other. 

I originally installed it via the **_installer_**; one day I updated via **_winget_**. I think that's when the problem you describe began for me. I tried uninstalling with the **_Windows Uninstall_** feature in the **_Control Panel_** as well as the **_uninstaller_** it comes with. The problem persisted. 

What I did is a search of all related files on my system and deleted  them all. No trace of **_Shell_** left. Reinstalled it, rebooted the system and the right-click is back to functional right away without the need of restarting the explorer.

**Comment by Aman1337g** [comment]
> @Aman1337g I had the same problem, and I think it had to do with several instances of Shell being installed and conflicting with each other.
> 
> I originally installed it via the **_installer_**; one day I updated via **_winget_**. I think that's when the problem you describe began for me. I tried uninstalling with the **_Windows Uninstall_** feature in the **_Control Panel_** as well as the **_uninstaller_** it comes with. The problem persisted.
> 
> What I did is a search of all related files on my system and deleted them all. No trace of **_Shell_** left. Reinstalled it, rebooted the system and the right-click is back to functional right away without the need of restarting the explorer.

Thanks @r-katabasis the problem is now fixed.
