### ISSUE TITLE
Right click on Taskbar after boot or explorer restart does not show custom menu

### ISSUE THREAD

**Issue by juliocoliveira** [moudey/Shell#127]
When I right click on Taskbar after boot or explorer restart does not show custom menu on Taskbar.

![image](https://user-images.githubusercontent.com/6606725/214327301-ffdc4361-a929-4cad-ac0c-4bebc355c096.png)

But once I open explorer it does show up.
![image](https://user-images.githubusercontent.com/6606725/214327550-005f42e3-0080-4f68-87f4-6b4490e5053b.png)

I saw this on #101 but the guy is complaining about Explorer Patcher, and I don't use Explorer patcher, just regular explorer.
I don't know if is possible to fix this, or is just an explorer issue.

**Comment by juliocoliveira** [comment]
There is any special build that I can use to see if its really fixed? I tried the build from #149 but it didn't fixed this issue in particular.

**Comment by moudey** [comment]
Please refer to this issue #101

**Comment by juliocoliveira** [comment]
The issue on #101 is ExplorerPatcher, as I already said on the issue, I don't have ExplorerPatcher installed, Just regular explorer, and the build available on that issue #101 is the same from #149, And I already using it, And it didn't fixed for me.

If I Shift-Right Click on taskbar and click on Exit Explorer, The custom menu on the taskbar stop working, IF I open explorer or Right Click on Desktop with this build the menu on taskbar starts working again, If I restart explorer it stops working again until I do the same thing mentioned before.

**Comment by moudey** [comment]
Test this [build](https://github.com/moudey/Shell/files/10677987/shell-test.zip)

1. Unregister Shell with restart explorer.
2. Register Shell with restart explorer.

**Comment by juliocoliveira** [comment]
![image](https://user-images.githubusercontent.com/6606725/217347967-84b37151-5a60-4e9a-ab41-b1b8d096c381.png)
![image](https://user-images.githubusercontent.com/6606725/217347996-5b64949b-dd4a-43d3-8ed2-302c5bf0b5d3.png)
![image](https://user-images.githubusercontent.com/6606725/217348084-0fe9b185-93b8-46b7-8a70-82aa5ab8276c.png)

This is not working at all, Now it never shows the custom menu, just classic context, and on taskbar even the original icons is missing.

**Comment by moudey** [comment]
>This is not working at all, Now it never shows the custom menu, just classic context, and on taskbar even the original icons is missing.

Don't worry about the modifications, the important thing is that they work. Is there an issue now with Taskbar?

**Comment by juliocoliveira** [comment]
As you can see on the screenshots i Posted, nothing is working, No taskbar or normal context menu on this build, From the build from #101 and #149 it works fine except if I restart explrorer. With this build you sent me nothing works at all.

**Comment by moudey** [comment]
Shell works as per attached screenshot

This is the same build combined with customizations
[shell-test.zip](https://github.com/moudey/Shell/files/10679050/shell-test.zip)

**Comment by juliocoliveira** [comment]
Tested this new build, Now it works like before, If i open explorer it shows the custom menu on taskbar, But if i restart explorer it does not work anymore until I open explorer again or right click on desktop.
Before explorer open:
![image](https://user-images.githubusercontent.com/6606725/217356382-5eab1017-31bb-4e02-b67e-e46cd829870d.png)
After explorer is opened:
![image](https://user-images.githubusercontent.com/6606725/217356493-04ea7c44-7b9f-4195-ae2d-9238e23df413.png)

**Comment by moudey** [comment]
Did you hide desktop icons?

**Comment by juliocoliveira** [comment]
> Did you hide desktop icons?

No

**Comment by moudey** [comment]
This [build](https://github.com/moudey/Shell/files/10687638/shell-test.zip) should work!

**Comment by juliocoliveira** [comment]
YES!! It does works! Thanks!

**Comment by FlorentLM** [comment]
Hey,
First thanks for this piece of software, it's excellent.

I had this same problem with ExplorerPatcher, and this build indeed fixes it, but it introduces a scaling bug with 4k displays, the context menu is ### SO BIG

**Comment by moudey** [comment]
Hi @FlorentLM This issue has been fixed in this [build](https://github.com/moudey/Shell/files/10725237/shell-test.zip)
