### ISSUE TITLE
Odd, unaligned useless menu item that doesn't work on clicking

### ISSUE THREAD

**Issue by Hidetoshi6721** [moudey/Shell#129]
![image](https://user-images.githubusercontent.com/85873175/214473834-92aac9ea-57d6-4ee1-8038-a25f10d6ce4b.png)

**OS: Windows 10 22H2**

Also, the Terminal menu item seems to be missing. Is this a Windows 10-specific issue?

**Comment by moudey** [comment]
This issue has been fixed in the portable version build 100
https://nilesoft.org/download/

**Comment by ThePython10110** [comment]
Maybe close the issue?

**Comment by alex-obada** [comment]
I am having the same problem. I also have installed the Terminal (1.15.3466.0) application from Microsoft and I am running the latest version of Shell

![image](https://user-images.githubusercontent.com/93531660/214710159-4130dd71-9afb-4027-943e-7eb4ea2d4eaf.png)

OS: Windows 11 21H2 build 22000.1516

**Comment by Hidetoshi6721** [comment]
> I am having the same problem. I also have installed the Terminal (1.15.3466.0) application from Microsoft and I am running the latest version of Shell
> 
> ![image](https://user-images.githubusercontent.com/93531660/214710159-4130dd71-9afb-4027-943e-7eb4ea2d4eaf.png)
> 
> OS: Windows 11 21H2 build 22000.1516

Hi, just like @moudey said, you can fix this in the following way (or at least how I fixed it):
1. Run Shell as admin > Unregister.
2. Download latest portable from https://nilesoft.org/download/
4. Unzip the portable (Step 2) and copy all these files to the directory `%programfiles%\Nilesoft\Shell`
5. Replace when prompted.
6. Close out of all windows.
7. Run Shell as admin > Register.

**Alternatively,**

1. Uninstall Shell completely.
2. Download latest portable from https://nilesoft.org/download/
3. Run 'shell.exe' as admin > Register.

**Comment by alex-obada** [comment]
It worked. Thank you
