### ISSUE TITLE
How to manage the menu?!

### ISSUE THREAD

**Issue by ClandestineClout** [moudey/Shell#138]
So I've installed Shell and I have absolute no idea how to manage the menu. It changed it, but I have no way to manage it. It doesn't say anywhere in the readme nor in the application how to do this... yet it's the primary advertised feature. If it is detailed somewhere consider making it more prominent.

**Comment by hiranokite** [comment]
hold shift and right click on taskbar, Shell menu will appear at the top with the submenus, from here you can open directory where the shell configuration files is saved.

shell.nss is where shell config is set, and inside imports\*.nss is the config of menu items, you can open those file with any text editor, i recommend the notepad++, and set the document language to C, to make the nss file more readable.

after editing any nss, you'll need to update changes, hold ctrl and press right click on desktop area or taskbar to it will force shell nss files to reload, or you can restart explorer.

please refer to [this page](https://nilesoft.org/docs) to start editing your menu.

Note: you can easily "brick" the shell menu if you do some typos on the nss files, and the default Windows menu will appear. To resolve just correct the syntax or undo the changes and restart explorer.
