### ISSUE TITLE
Matching items using `where` only applies to the top-level menu unless `find` is also specified.

### ISSUE THREAD

**Issue by SteffanDonal** [moudey/Shell#143]
Hey there!
First, thank you for the excellent tool. I've never enjoyed menu customisation like this, and I like the "declarative layer" config method as it allows deep customisation without affecting registry data.
I can see myself creating a comprehensive, powerful configuration that I'd end up sharing on GitHub.

As part of that goal, I want to make my config more robust. Instead, I want to avoid matching existing menu items based on their titles and use IDs everywhere.

I'm using this helpful snippet to get the IDs of items that aren't included in the `id` function:
```
item(find="*" title=(this.title + " (" + this.id + ")"))
```

This gives me a very helpful view:
![image](https://user-images.githubusercontent.com/1431570/215321283-3d4e6995-5cad-4d8a-9d34-af11c20bfeeb.png)

However, when I attempt to match _some_ items by using their IDs as reported, I get this behaviour:
```
item(where=this.id==3854266799 image.color=#0f0) // Notepad++
item(where=this.id==2906872540 image.color=#ff0) // Search MS Store
item(where=this.id==2086460140 image.color=#0ff) // Open with Code
item(where=this.id==1169978760 image.color=#00f) // Open in Terminal
```
![image](https://user-images.githubusercontent.com/1431570/215321634-11517d34-0234-4299-80c7-5f2e655463cd.png)

I can only resolve this by including `find="*"` as part of the item definition:
```
item(find="*" where=this.id==3854266799 image.color=#0f0) // Notepad++
item(find="*" where=this.id==2906872540 image.color=#ff0) // Search MS Store
item(find="*" where=this.id==2086460140 image.color=#0ff) // Open with Code
item(find="*" where=this.id==1169978760 image.color=#00f) // Open in Terminal
```
![image](https://user-images.githubusercontent.com/1431570/215322397-728d04ab-1f4b-4096-ab02-b53f08ac91d6.png)

It took me quite a while to figure out this solution, so I hope you can add this to your documentation site!

**Comment by moudey** [comment]
Thank you @SteffanDonal for your interest

This issue was fixed immediately try [this](https://github.com/moudey/Shell/files/10529763/shell-test.zip)

**Comment by SteffanDonal** [comment]
Cheers! Happy to confirm it's fixed 😀
