### ISSUE TITLE
Bug with dynamic menu?

### ISSUE THREAD

**Issue by hiranokite** [moudey/Shell#144]
If i create a new item inside dynamic and set the type to a specific type of object like "type='desktop|drive|file'" the object still appears on Explorer window "titlebar", seems there's no function to enable only in titlebar type.

```
dynamic
{
	item(type='file' title='Hello, World!')
		separator
	menu(type='desktop' title = 'sub menu' image = #0000ff)
	{
		item(type='taskbar' title = 'test subitem')
	}
}
```

![image](https://user-images.githubusercontent.com/5361459/215354986-06687be9-a7ad-4fa1-b290-55263cb2796c.png)

It only works as instead when i set the type to taskbar, as you can see in the image, only the item inside "sub menu" isn't showing.

Bug or I'm doing something wrong?

And there's a typo [here](https://github.com/moudey/shell/blob/main/docs/syntax/dynamic.html#L11)

**Comment by moudey** [comment]
This issue was fixed immediately. and added `titlebar`, `edit` and `start` to `type` property
