### ISSUE TITLE
It shows the regular windows 11 context menu on the desktop

### ISSUE THREAD

**Issue by cpuccino** [moudey/Shell#148]
Shell only shows up after I click "Show More Options" or if I do a shift+right click on the desktop

I remember when I installed this a month ago or something, that it automatically replaced right click on the desktop? IIRC I didn't do any additional steps to make that work?

**Comment by cpuccino** [comment]
I jumped back to version 1.7 and everything works well again. Odd

**Comment by moudey** [comment]
Please refer to #149

**Comment by Paras6408** [comment]
@moudey I can check, this is now working fine.
Can close this issue
