### ISSUE TITLE
After restart doesnt work

### ISSUE THREAD

**Issue by Cromaxxx** [moudey/Shell#149]
After computer restart right click doesnt work.. tried checking reg keys but still doesnt work

**Comment by moudey** [comment]
Use this command to register a shell. Version 1.8 build 100 is available in portable version

Open command prompt as admin
```
shell -register -treat -restart
```

**Comment by Cromaxxx** [comment]
somehow my shell commands is missing

**Comment by moudey** [comment]
run cmd in shell directory or write shell path
```
path\to\shell.exe -r -restart -treat
```

**Comment by Cromaxxx** [comment]
command went through but after restart again theres no context menu unless i unregister or register again.. and i copied files from portable

**Comment by moudey** [comment]
Did you modify the settings file `.nss`?

**Comment by Cromaxxx** [comment]
Can you pls provide me link for 1.7 bc its 1.8 that breaks right click on desktop i had to restore back up of system image where was 1.7 and it works fine until you update it to 1.8 even portable 100 doesnt work

**Comment by moudey** [comment]
Please test this [build](https://github.com/moudey/Shell/files/10611265/shell-test.zip)

Unregister Shell and then register the attached build.

**Comment by Cromaxxx** [comment]
yeah works now... ty.. mark as solved
