### ISSUE TITLE
How do I organize 3rd party application context menu entries ?

### ISSUE THREAD

**Issue by carlosvsilva** [moudey/Shell#150]
Hi, I'd like to move some 3rd party apps context menu entries to the "More options" hidden section for rarely used items.
But I'd like to keep the most used items (from 3rd party apps) in the main context menu.

![image](https://user-images.githubusercontent.com/40889421/216209048-27602fc0-1908-49b6-88ec-9ec32c168b59.png)

Is that possible with this Shell software? Care to send an example?

Thanks

**Comment by moudey** [comment]
With just one line, a shell enables you to remove unwanted items or move them to a submenu.  See the following example: 
Open the `shell.nss` file and add this code to the `static` section

```
// to move items
item(find='add zip|add 7z|"extract"' menu='more options')

// to remove items
item(find='open as archive|extract here' vis=0)
```
Save changes, then press `Ctrl` + `right-click`, or restart Explorer to reload settings.

**Comment by carlosvsilva** [comment]
Great. How does one display entries according to file type?

Eg: Extract for archive files, Add to Zip for non-archive, non-media files, Scan with Anti-Virus for dangerous filetypes (exe, bat, cmd, ps1, office, pdf, etc), Edit With Notepad++ just for non-binary files...

**Comment by carlosvsilva** [comment]
And how do I return an item to the root context menu, when a default line is sending it to the submenu "More options" ?

		item(find='Extract here (smart new folder)' menu=title)
		item(where=this.title.length > 25 menu=title.more_options)

this doesnt seem to work like intended.

**Comment by moudey** [comment]
> Great. How does one display entries according to file type?
> 
> Eg: Extract for archive files, Add to Zip for non-archive, non-media files, Scan with Anti-Virus for dangerous filetypes (exe, bat, cmd, ps1, office, pdf, etc), Edit With Notepad++ just for non-binary files...

items can be filtered by file type with `where` property.
```
item(type='file'
    find='add zip|add 7z' 
    where=(sel.file.ext== '.zip' || sel.file.ext== '.z7') 
    menu='zip')
```

>And how do I return an item to the root context menu, when a default line is sending it to the submenu "More options" ?

Please refer to #154

**Comment by carlosvsilva** [comment]
Thanks. 
Btw, when I try to hide menu entries that end with ... (three dots) they still show up no matter what. Any idea how to hide these? Thanks

`item(find='Extrair Todos...|Extract...|Open as archive' vis=0) `

**Comment by moudey** [comment]
It is ignored "..." when searchin

**Comment by bigplayer-ai** [comment]
> 

How to add the context menu "Open Folder as PyCharm Project" to the main view of context menu (not in the more options context menu)?

**Comment by moudey** [comment]
#224
