### ISSUE TITLE
item with type 'file' shows in Win+X menu

### ISSUE THREAD

**Issue by peterzh4ng** [moudey/Shell#151]
### Environment

Windows 10, OS build 20348.1487

### Problem Description

There is problem that I just insert a menu item with type **file**, but it shows in the Win+X menu. Am I missed something?

```
item(type='file' title='Edit with Notepad++' image='@npp' cmd='@npp' args='"@sel.path"' position=top)
```

![图片](https://user-images.githubusercontent.com/86906331/216269190-86ed8c19-558c-4204-bfda-e13d8aa8eed8.png)

Btw, I'm so happy to see that customized menu items could show in the Win+X menu.

**Comment by moudey** [comment]
Please refer to #144
