### ISSUE TITLE
[Question] possibility of renaming certain entries of the contextual menu?

### ISSUE THREAD

**Issue by SaiyajinK** [moudey/Shell#154]
hi @moudey 

Is it possible with Shell to rename context menu entries as I would like to on multiple entries?

For example, I am using Kaspersky and I have an entry called "Scan for viruses" and I would like to rename it to "'Analyze"

Is there a command to do this?

for example in static.nss put something like this?

`item(type='*' find='Scan for viruses' rename='Scan')`
(this command obviously doesn't work)

Thank you for your answer 👍

**Comment by moudey** [comment]
```
item(type='*' find='Scan for viruses' title='Scan')
```

**Comment by SaiyajinK** [comment]
fast and efficient, thank you!

**Comment by SaiyajinK** [comment]
@moudey the command works well, on the other hand I don't know if it's normal but I could see that some renamed entries moved by themselves in the "More options" menu

In the file **shell.nss** I have these two lines there:

`item(type='taskbar' mode="multiple" where=this.title.len > 25 tip=this.title parent=@id.more_options.title)`
`item(type='desktop|file' mode="multiple" where=this.title.len > 20 tip=this.title parent=@id.more_options.title)`

I noticed this when I wanted to rename the "Edit with Notepad++" entry by just putting "Notepad++" in **static.nss**:

`item(type='*' find="Edit with Notepad++" title='Notepad++')`

However, the number of characters decreases, why does the input move by itself when the number of characters is much less than 20?

![3m73Q1XtnY](https://user-images.githubusercontent.com/105972098/216625850-18c29c17-6976-47ac-831b-0ba32144a4f5.png)

it's strange isn't it?

**Comment by moudey** [comment]
Commands must be arranged
```
item(type='*' find='Edit with Notepad++' title='Notepad++')
...
...
...
item(type='taskbar' mode="multiple" where=this.title.len > 25 tip=this.title parent=@id.more_options.title)
```

**Comment by moudey** [comment]
I see that you use changing icons a lot in a static section. You can change that method automatically through the new feature, `images` section.

```
shell
{
    ...
    images
    {
        ident0 = \ue007
        "ident1", ident2 = \ue008
        ident_3, 'ident 4' = #f00
    }
    ...
}
```

**Comment by SaiyajinK** [comment]
Hi,

I preferred to start from a healthy base following the many changes I had made. So I renamed the entry in the first place but I don't know, even by arranging the commands the renamed entry remains in the menu no more options...

the only viable solution I found is to create an Edit menu in the _dynamic_ section of the **shell.nss** file

```
...
dynamic
{
menu(mode="multiple" title="Edit" image=icon.edit) { }
...
```

and adding the renamed entry to the menu in **static.nss**

```
item(find="Edit with Notepad++" title='Open with Notepad++')
item(find='Open with Notepad++' menu='Edit')
```

![vmware_6PhJ1YOdDf](https://user-images.githubusercontent.com/105972098/220022535-8821cef8-4333-42b0-942c-5ef46b30b67f.png)

**Comment by moudey** [comment]
It can also be written like this:
```
item(find='Edit with Notepad' title='Open with Notepad++' menu='Edit')
```
