### ISSUE TITLE
Feature Request: OpenShell support

### ISSUE THREAD

**Issue by peterzh4ng** [moudey/Shell#156]
I'm so happy to find that Shell could affect the context menu clicked from the OpenShell menu!

But is it possible to let the 'file' or 'folder' attribute of 'item' to adapt the OpenShell menu? Because now everything customized always show in the OpenShell context menu.

![图片](https://user-images.githubusercontent.com/86906331/217311131-a73ef8fe-b8be-4719-b59b-2756431c8c09.png)

Thanks, anyway.

**Comment by moudey** [comment]
Sorry for the delay, I've been busy. Later, I'll show you how to filter these items by window names

**Comment by peterzh4ng** [comment]
That would be great.

**Comment by peterzh4ng** [comment]
That would be great.

**Comment by moudey** [comment]
This item will appear in all menus except for the one with the window name "OpenShell.CMenuContainer"
```
item(type='*' where=window.name!="OpenShell.CMenuContainer" title='Window name=@window.name')
```

**Comment by peterzh4ng** [comment]
![图片](https://user-images.githubusercontent.com/86906331/222799672-f7eec4fb-f398-4f75-9060-992fee8bdfb6.png)

😭 😭 😭 😭 😭

**Comment by peterzh4ng** [comment]
Bravo!
