### ISSUE TITLE
Hold shift for admin not working

### ISSUE THREAD

**Issue by enkelmedia** [moudey/Shell#159]
Hi!

Thank you so much for an awesome utility!

I'm trying to open Windows Terminal as administrator by holding the shift key while opening the editor and I can't get this to work. Here is what I've tried:

When inside a folder in explorer I have tried:

* Holding shift before right-clicking, clicking on "Terminal -> Windows Terminal" while still holding down shift.
* Rich-clicking in the folder, hold down shift and then click on "Terminal -> Windows Terminal"

None of these seems to open the terminal as administrator. I'm not sure if there is a setting that I'm missing? I'm using the `shell.nss` that was shipped with version 1.8.

```
menu(type='*' where=(sel.count or wnd.is_taskbar or wnd.is_edit) title=title.terminal sep='top' image=icon.run_with_powershell)
{
	item(where=sys.ver.major >= 10 title=title.Windows_Terminal admin=key.shift() image='@package.path("WindowsTerminal")\WindowsTerminal.exe' cmd='wt.exe' arg='-d "@sel.path\."')
	item(title=title.command_prompt admin=key.shift() image cmd='cmd.exe' args='/K TITLE Command Prompt &ver& PUSHD "@sel.dir"')
	item(title=title.windows_powershell admin=@key.shift() image cmd='powershell.exe' args='-noexit -command Set-Location -Path "@sel.dir\."')
}
```

**Comment by moudey** [comment]
This issue has been fixed in version 1.8 build 100 which is in the portable version.

**Comment by bigplayer-ai** [comment]
Can you please update the installer version?

**Comment by moudey** [comment]
@bigplayer-ai Sorry for the delay in updating the installer because I've been busy, but I promise you that the update will be done this week with a special installer that meets Shell's needs.

**Comment by bigplayer-ai** [comment]
Does the installer have auto update module?
And did you update the installed version (not the portable).

**Comment by moudey** [comment]
>Does the installer have auto update module?

Not yet

>And did you update the installed version (not the portable).

Yes, the installer has been updated, and you can also extract a portable copy from it.

**Comment by bigplayer-ai** [comment]
> > Does the installer have auto update module?
> 
> Not yet
> 
> > And did you update the installed version (not the portable).
> 
> Yes, the installer has been updated, and you can also extract a portable copy from it.

Next time please release a changelog So we don't have to ask you first.
Best Regards,

**Comment by moudey** [comment]
This is a periodic maintenance update. But new versions will be added to the changelog with all periodic changes.
You can follow the changes through the link: https://nilesoft.org/feed/releases
