### ISSUE TITLE
[Feature Request] Accent Color

### ISSUE THREAD

**Issue by ClifffordW** [moudey/Shell#162]
Make the menu use accent color of the system

**Comment by bigplayer-ai** [comment]
This would be so good.

**Comment by moudey** [comment]
You can use Accent Color with borders and images, see the following example:
```
theme
{
    image.color=[color.accent, color.accent_dark3]
    border
    {
        enabled = 1
        size = 1
        color =  color.accent
        opacity = 100
    }
}
```
![screenshot_20230218_202523](https://user-images.githubusercontent.com/39198/219882257-61653819-529d-4146-b402-a52c3f35a380.png)

**Comment by bigplayer-ai** [comment]
Can I use it only for Glyph colors?On 18 Feb 2023, at 20:26, Mahmoud Gomaa ***@***.***> wrote:﻿
You can use Accent Color with borders and images, see the following example:
theme
{
    image.color=[color.accent, color.accent_dark3]
    border
    {
        enabled = 1
        size = 1
        color =  color.accent
        opacity = 100
    }
}

**Comment by moudey** [comment]
>Can I use it only for Glyph colors?
```
theme
{
    image.color=[color.accent, color.accent_light3]
}
```

**Comment by bigplayer-ai** [comment]
thanks

**Comment by duckduckdog** [comment]
Came here looking for Accent colored glyphs & was not disapointed.
Thanks moudey.

**Comment by kleidiss** [comment]
`image.color=[image.color1,color.accent,image.color3]`

This is more accurate to the w11 context menu

**Comment by RubicBG** [comment]
easy way to manage colors for all components
https://discord.com/channels/1106387012707168318/1139275510506082336/1155924668914610187
