### ISSUE TITLE
auto pop up menu form taskbar

### ISSUE THREAD

**Issue by NightmareZero** [moudey/Shell#165]
![Screenshot 2023-02-22 104848](https://user-images.githubusercontent.com/17422155/220508627-be535a9b-a283-4585-927f-000762553b1c.png)

i don't touch anything, the menu pops up every few minutes or hours

**Comment by moudey** [comment]
Please provide me Windows and Shell version

**Comment by NightmareZero** [comment]
windows version: 22H2  Build  22621.1265
shell version: 1.8.0

**Comment by moudey** [comment]
Does this issue still exist?
