### ISSUE TITLE
[BUG] No Option to "print" the photo, when using right-click on an image.

### ISSUE THREAD

**Issue by Paras6408** [moudey/Shell#166]
However, I am able to do so with Windows Stock Context Menu.

**Comment by moudey** [comment]
This item has been moved to `More Options > Print`

**Comment by Paras6408** [comment]
Right-clicked on a .jpg file.

No print option...

Please refer to attached ss:

![Screenshot 2023-03-02 223826](https://user-images.githubusercontent.com/94892430/222501337-267060b4-cc5f-4002-9abb-63bcef7a6c5a.png)

**Comment by moudey** [comment]
Press <kbd>CTRL</kbd> + <kbd>WIN</kbd> + <kbd>RIGHT-CLICK</kbd> to check if "Print" appear in classic menu
Press <kbd>CTRL</kbd> + <kbd>RIGHT-CLICK</kbd> to restore **Shell** menu

**Comment by Paras6408** [comment]
Yes, "Print" is there in classic menu.

![Screenshot 2023-03-03 160739](https://user-images.githubusercontent.com/94892430/222699049-8adb0607-c6c2-4ee2-9c4c-b465e4fc939a.png)

**Comment by Paras6408** [comment]
@moudey Where to find these files?
