### ISSUE TITLE
Strange behaviour with Win + X

### ISSUE THREAD

**Issue by naokoshoto** [moudey/Shell#168]
I don't know how this happened but every time I press Win + X hotkey, it shows many unrecognized characters with v1.8.1, v1.7 had no problem for me.

Additional information:
- When the first time the shell boots and press the hotkey, it does show as it should, but more than that will show that. Also, it will increase the length every time I press it.

![image](https://user-images.githubusercontent.com/25972975/221339141-fc997624-5ddf-4100-b439-b48b5d0e30e1.png)

**Comment by bigplayer-ai** [comment]
When I prss win +x i can't press A to run teminal as admin mode when running the shell context menu,

**Comment by moudey** [comment]
Hi @naokoshoto 

What version of Windows are you using?

**Comment by moudey** [comment]
>@bigplayer-ai When I prss win +x i can't press A to run teminal as admin mode when running the shell context menu,
 
I tried it on Windows 10 and opened Command prompt

**Comment by naokoshoto** [comment]
> Hi @naokoshoto
> 
> What version of Windows are you using?

Windows 10 22H2, Build 19045.2673

**Comment by bigplayer-ai** [comment]
﻿Windows 11 22h2 build 22621On 25 Feb 2023, at 18:53, Muhammad Fadly Saripudin ***@***.***> wrote:﻿

Hi @naokoshoto
What version of Windows are you using?

Windows 10 22H2, Build 19045.2673

**Comment by moudey** [comment]
@naokoshoto Try this [build](https://nilesoft.org/download/shell/test-x64.zip)

**Comment by naokoshoto** [comment]
@moudey 
Problem still occurs

**Comment by naokoshoto** [comment]
@moudey no updates or still working on this?

**Comment by moudey** [comment]
> @moudey no updates or still working on this?

I'm working on this issue.

**Comment by moudey** [comment]
@naokoshoto Try this [build 30](https://github.com/moudey/Shell/files/11361783/debug.zip)

**Comment by naokoshoto** [comment]
> @naokoshoto Try this [build 30](https://github.com/moudey/Shell/files/11361783/debug.zip)

Finally, this build worked for me, thanks for solving 🙏

**Comment by naokoshoto** [comment]
i don't think i should close this
