### ISSUE TITLE
No right click menu after restart

### ISSUE THREAD

**Issue by FeedTheChunk** [moudey/Shell#171]
I followed the advice in127 149 but I still have no right click after restarting the PC.  I have unregistered Shell, uninstalled shell and still no right click after rebooting.  I have to open an Explore window, CTRL+SHIFT+ESC and restart Explorer to get the right mouse button functionality back.  Any ideas on how I can get right click to work after reboots?

**Comment by 42yash** [comment]
I have a similar problem. Are you on the windows 11 insider channel?

**Comment by FeedTheChunk** [comment]
No.  Windows 10

**Comment by moudey** [comment]
>restart Explorer to get the right mouse button functionality back.

Do you mean the function of the right mouse button does not work after registering Shell?

**Comment by FeedTheChunk** [comment]
No,  Once explorer is restarted shell functionality works just fine.  I just have restart explorer every time after a reboot.  I've even uninstalled Shell and right click doesn't work until I restart Explorer.

When I say "doesn't work" I mean that there is no right click menu at all.

**Comment by moudey** [comment]
Run command prompt as administrator in shell folder
```
shell.exe -r -f -s -restart
```

**Comment by moudey** [comment]
Please attach `shell.log` file

**Comment by FeedTheChunk** [comment]
[shell.log](https://github.com/moudey/Shell/files/10854048/shell.log)

**Comment by moudey** [comment]
@FeedTheChunk Try this [build](https://nilesoft.org/download/shell/test-x64.zip) and attach `shell.log` file

**Comment by FeedTheChunk** [comment]
[shell.log](https://github.com/moudey/Shell/files/10862614/shell.log)

I Unregistered Shell, uninstalled Shell and then Extracted the zip file.  Ran Shell as Admin and Registered, rebooted and right-click still not working.  thanks.

**Comment by moudey** [comment]
1. Delete `shell.log` file
2. Reboot
3.  Click once on the desktop and another on any file
4. Go to Shell folder and execute this command
```
shell.exe check
```
6. attach `shell.log`

don't restart explorer

**Comment by FeedTheChunk** [comment]
[shell.log](https://github.com/moudey/Shell/files/10863968/shell.log)

**Comment by moudey** [comment]
Looks like you forgot this step:
4. Go to Shell folder and execute this command
```
shell.exe check
```
During the two clicks Shell menu would appear?

**Comment by FeedTheChunk** [comment]
Dang-it.  I did I forget.

[shell.log](https://github.com/moudey/Shell/files/10864086/shell.log)

**Comment by FeedTheChunk** [comment]
I would like to add the right click does work w/in apps such as Firefox, Outlook etc,

**Comment by moudey** [comment]
>During the two clicks Shell menu would appear?

**Comment by FeedTheChunk** [comment]
No menus at all.  Only menus I get are when I click in apps such as Firefox et. al.

**Comment by moudey** [comment]
Please attach a screenshot showing the context menu on the desktop and another for the taskbar context menu

**Comment by FeedTheChunk** [comment]
This is no context menu.  I'll fire up OBS and take a short video and UL it to youtube.

https://youtu.be/_3LDjI9-nw8

**Comment by FeedTheChunk** [comment]
Okay now we're getting somewhere!  I cleared the settings in the shell.nss file and then rebooted. (I had already restarted Explorer.) I now have a right click menu after rebooting and not having to restart explorer.

Here's the Right Click context menu:
![image](https://user-images.githubusercontent.com/35508630/222265927-b1f3475a-2c29-4fd7-84a5-ac7be91cb2a9.png)

**Comment by FeedTheChunk** [comment]
Good luck getting this fixed.  I never was able to get it the context menu to work after rebooting.  Now my other Windows 10 box does the exact same thing.  I've just give up at this point.  Not sure what Shell changes but it sure messed something up.

**Comment by stancho44** [comment]
I found a temporary workaround of just restarting "explorer.exe" using task scheduler and I'm pretty happy about it.

Here's a guide on how to do this
1. Search for task scheduler on windows
2. Create a new task
3. Name it whatever you want (ex. Restart Explorer)
4. On the trigger tab create a new trigger with "at log on"
5. On the actions tab create a new action and copy and paste this `powershell Stop-Process -ProcessName Explorer`
6. Click on yes when it tells you that it's going to move part of the code to the arguments
7. You should be set on the next time you restart.

Hope this helps

**Comment by FeedTheChunk** [comment]
Not for me. I used [stancho44](https://github.com/stancho44) workaround but added a 30 sec delay before the startup task ran.  Having it run right at start up sometimes caused other programs not to load.  I wish we knew what devs changed so that we could try and reverse it.  I suspect that there must a registry entry that is the root of our evil.

**Comment by FeedTheChunk** [comment]
I finally was able to get Shell unistalled properly and return the default right-click behavior!  I found another installation in C:\Program Files\Nilesoft\Shell and ran the uninstall from there.  I disabled the workaround posted by [stancho44](https://github.com/stancho44) and rebooted the PC. After rebooting w/out having to restart Explore the right-click worked fine.
