### ISSUE TITLE
1.8.0->1.8.1 regression (font: size)

### ISSUE THREAD

**Issue by IgorEisberg** [moudey/Shell#176]
Hi, thank you for this amazing utility.
I just updated from 1.8.0 to 1.8.1 and applied my previous settings.
One in particular causes trouble:

```
	font
	{
		size=14
	}
```

The moment I use a size for the font, all hell breaks loose.

![OtR8qqM](https://user-images.githubusercontent.com/8811086/222439889-e1ebac55-26da-45d0-86bc-f165565a18b5.png)

Quite obvious which one is the broken one.
The log is clean, nothing interesting in there.
The usual font is too small for me though. Any clues?

**Comment by moudey** [comment]
@IgorEisberg Thanks for your report. 

The issue has been fixed.

**Comment by IgorEisberg** [comment]
Can I like... download it somewhere? Kinda have bad vision.

**Comment by moudey** [comment]
https://nilesoft.org/download/shell/debug.zip
