### ISSUE TITLE
Add the possibility to customize each contextual menu separately

### ISSUE THREAD

**Issue by Nicryc** [moudey/Shell#18]
It would be a could feature to be able to customize the different contextual menus separately.

For example I want to customize the contextual menu of the file explorer in a certain way and customize the contextual menu of the desktop in a different way, I also don't want to customize the contextual menu of the task bar and keep its default appearance.

I guess this is technically feasible since these contextual menus are already themed differently on vanilla Windows 10.

**Comment by moudey** [comment]
Hi @Nicryc, 
This can be done in the following ways:

To customize the appearance by window use the following code:
```
default {

    //theme = [auto, dark, light, white, black, modern, modern_light, modern_dark, classic]

    // https://nilesoft.org/docs/functions/this
    theme = if(this.taskbar, theme.white, 
                        if(this.desktop, theme.black, theme.classic))
}
```

To customize the display of items by window:

```
dynamic {
    // by type
    item(title='item for taskbar only' type='taskbar')
    item(title='item for desktop only' type='desktop')
    item(title='item for file explorer only' type='~desktop|~taskbar')

    // or by where
    item(title='item for taskbar only' where=this.taskbar)
    item(title='item for desktop only' where=this.desktop)
    item(title='item for file explorer only' where=this.explorer)
}
```

**Comment by Nicryc** [comment]
Great! I guess I can close this then.
