### ISSUE TITLE
Error with `@sel.path.quote` when followed by another quoted argument

### ISSUE THREAD

**Issue by martin-rueegg** [moudey/Shell#182]
#### Item Configuration

```
item(
	title='Title'
	cmd='c:\path\to\file.bat'
	args='--some --argument @sel.path.quote "c:\path\to\some\other\file.txt"'
)
```

#### Expected Command Line

Above `item` is supposed to produce the following command line:

``` batch
c:\path\to\file.bat --some --argument "c:\path\to\selected\file.txt" "c:\path\to\some other\file.txt"
```
Where the last two arguments are `c:\path\to\selected\file.txt` and `c:\path\to\some other\file.txt`.

#### Actual Command Line 

The space between the last two arguments gets ignored:

``` batch
c:\path\to\file.bat --some --argument "c:\path\to\selected\file.txt""c:\path\to\some other\file.txt"
```
The two quotes `""` (rather than `" "`!) are a escaped quote (literal string `"`) and hence the last two arguments become one: \
`c:\path\to\selected\file.txt"c:\path\to\some other\file.txt`.

#### Workaround

If the `@sel.path.quote` is replaced with `"@sel.path"`, it works as expected:

```
item(
	title='Title'
	cmd='c:\path\to\file.bat'
	args='--some --argument @sel.path.quote "c:\path\to\some\other\file.txt"'
)
```

**Comment by moudey** [comment]
Do not use escape sequences in single quotes

Single quotes
```
item(
	title='Title'
	cmd='c:\path\to\file.bat' 
	args='--some --argument "@sel.path" "c:\path\to\some\other\file.txt"'
)
```
Use escape sequences
```
item(
	title='Title'
	cmd="c:\\path\\to\\file.bat"
	args="--some --argument " + sel.path.quote + " \"c:\\path\\to\\some\\other\\file.txt\""
)
```
quote func
```
item(
	title='Title'
	cmd='c:\path\to\file.bat'
	args="--some --argument " + sel.path.quote + quote(' c:\path\to\some\other\file.txt')
)
```
https://nilesoft.org/docs/expressions/string

**Comment by martin-rueegg** [comment]
I understand. To be honest, the documentation is still quite confusing to me .... :-)

> Do not use escape sequences in single quotes

As a matter of fact, I added those escape sequences just in the issue here. I indeed used it exactly as you wrote (have now updated the original post):

> Single quotes
> 
> ```
> item(
> 	title='Title'
> 	cmd='c:\path\to\file.bat' 
> 	args='--some --argument "@sel.path" "c:\path\to\some\other\file.txt"'
> )
> ```

However, this still causes the error.

**Comment by moudey** [comment]
>I understand. To be honest, the documentation is still quite confusing to me .... :-)

Perhaps this is due to Google Translate, as I use it to translate my Arabic language into English

>If the `@sel.path.quote` is replaced with `"@sel.path"`, it works as expected:

To avoid this issue use this method or the previous one
```
args='--some --argument @(sel.path) "c:\path\to\some\other\file.txt"'
```

This issue will be fixed

**Comment by moudey** [comment]
This issue has been fixed: [debug](https://nilesoft.org/download/shell/debug.zip)

**Comment by martin-rueegg** [comment]
> This issue has been fixed: [debug](https://nilesoft.org/download/shell/debug.zip)

Yes, this seems to be solving the issue! Fantastic!
