### ISSUE TITLE
Right-click on an icon in the taskbar doesn't pop-up  menu to unpin it

### ISSUE THREAD

**Issue by mohfarahiii** [moudey/Shell#186]
When I right-click on an icon in the taskbar doesn't pop-up  menu to unpin it BTW I have explorer patcher installed

**Comment by moudey** [comment]
What version of Windows are you using?

**Comment by mohfarahiii** [comment]
> What version of Windows are you using?

Latest windows 11 update moment 2

**Comment by moudey** [comment]
Please try this [build](https://nilesoft.org/download/shell/debug.zip)
