### ISSUE TITLE
[Documentation] website: `.html` extension not supported

### ISSUE THREAD

**Issue by martin-rueegg** [moudey/Shell#189]
On the website, the `.html` file extension is not supported.

E.g. the file [variables.html](https://github.com/moudey/Shell/blob/main/docs/syntax/variables.html) is not reachable at \
https://nilesoft.org/docs/syntax/variables.html, but only at \
https://nilesoft.org/docs/syntax/variables

This makes it more difficult to maintain URL's from one documentation page to another. 

An easy solution could be to [implement a permanent redirection on the webserver](https://duckduckgo.com/?q=how+to+set+up+permanent+redirect+from+to+remove+html+extension) from `basename.html` to `basename`. Like this, the user (and search engines) would still see the page without the extension, but the links can still be used within the document.

Another approach could be to remove the extension when creating the static file on the server after new pages have been published.

**Comment by moudey** [comment]
Document pages are loaded dynamically,
I have modified the new links to match the docs link

`../set` to `/docs/syntax/set`

I will format the documents to make it easier to update
