### ISSUE TITLE
Add the possibility to position static or dynamic items relatively to other same-level items

### ISSUE THREAD

**Issue by Nicryc** [moudey/Shell#19]
Currently it is only possible to place items at a specified integer position or with some predefined positions like top, bottom, middle (at least I didn't find a way to do differently).

It would be be a great addition to be able to place items next to other ones. For example I want to create an item "Delete all" and want to place it just after the already existing "Delete" system item.

Maybe one way to do it would be to add the possibility to the `id` function to access any element by id number (it is currently limited to system menu items) and to access the pos property. Something like: `id.254665032.pos`.

**Comment by moudey** [comment]
@Nicryc This feature requires a function that returns the position of the item and this function is being worked on.

**Comment by moudey** [comment]
`indexof("name"[,index][,default])` func returns the position of menu item
Please test this issue with [shell 1.8 beta](https://nilesoft.org/download)
