### ISSUE TITLE
[Documentation] CSS updates

### ISSUE THREAD

**Issue by martin-rueegg** [moudey/Shell#191]
### Document headings

In the current [website](https://nilesoft.org/docs/installation), there is no use made of `H1`, `H2`, and `H3` header tags. Hence, in the documents everything is done with `H4` and sometimes with `H5`. And lots of `br`s.

Would it not make sense to 

- [ ] Use the `H1` tag (currently `H4`) for the `Documents` heading (not used here in source code)
- [ ] Use the `H2` tag (currently `H4` in most cases) for the document's `Title` (e.g. `Installation`, `Functions`, etc.; its currently also used in the `head`er's `title` attribute). So this would be the one used in the first line of the documents here.
  - [ ] And it will be used only once per document
- [ ] Use `H3`, `H4` (and `H5` if required) for the structure on the document.
  - [ ] Where `H3` is the main structure of the document. Indexed in a TOC.
  - [ ] Where `H4` are sub-headings, that might be indexed, if useful.
  - [ ] Where `H5` is only used as minor descriptions. Not indexed. Alternative to `dt`, if it's not really a definition list.

### Some classes

It would be great to have the following classes:

- [ ] Rather than using the `<span class="is-family-monospace">` tag, it would make sense to use [`var`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/var) instead. It might need some CSS settings, even without a class to look similar to the above.
- [ ] Links are even worse! They look like this: `<a href="variables.html" style="border-bottom: 1px solid currentColor;">` This should be moved to CSS. (UPDATE: has been partly done in [here](https://github.com/moudey/Shell/issues/191#issuecomment-1456096476))
- [ ] Also the header tags should get some tweaking with margin-top and margin-bottom, so that the use of `br`s can be avoided and a nice and simple and consistent layout can be achieved.
- [ ] Same would apply to the `<pre>` tag.

### Adding the CSS to the source code

~Would it be possible to add the CSS to the source code (of course it can be downloaded manually, but it would make things easier)~

UPDATE: has been [done](#192).

### PHP wrapper script

~Also, it would be helpful to have a small wrapper script, that does roughly what the script does on the server, so that the documents look similar. Maybe easiest this could be done with PHP, as it can be used on all systems. And with [devilbox](http://devilbox.org/) it's super easy to host projects locally. This script would allow to include the CSS file.~

UPDATE: has been implemented as ASP application [here](#192) and [here](https://github.com/moudey/Shell/issues/191#issuecomment-1461810450).

### Future considerations

- [ ] #208
- [ ] Maybe some long tables would be easier as `div` for faster page loading.

**Comment by moudey** [comment]
The site runs with asp.net  and uses bulma.io 
I added `class="uline"` to use it instead of `style="border-bottom: 1px solid currentColor;"`  until the docs are reformatted.

**Comment by martin-rueegg** [comment]
> The site runs with asp.net and uses bulma.io

I understand.

> I added `class="uline"` to use it instead of `style="border-bottom: 1px solid currentColor;"` until the docs are reformatted.

Ok. But would it not make sense to have this as a default for any `a` tag? And instead use a class (e.g. `no-uline`) in case you don't want this?

**Comment by moudey** [comment]
>Ok. But would it not make sense to have this as a default for any a tag? And instead use a class (e.g. no-uline) in case you don't want this?

I put this in as a temporary workaround until I finished developing the import tag

**Comment by martin-rueegg** [comment]
> Also try this simulator of the documentation page on the site https://nilesoft.org/download/shell/www-docs.zip

Yes, that's exactly what I've been looking for when I was asking for a *PHP wrapper script" in the [initial post](https://github.com/moudey/Shell/issues/191#issue-1611216174). :-) Would have saved me some time, rather than creating PR #192 :-)

However, the solution I've provided has some benefits:
- It only requires .NET v4, which is installed by default
- It works with the current files in the local repository, hence no further setup required to see your changes reflected in the browser
- Also new files and folders are accessible, even in the left-hand navigation
- All images under /docs/images are shown correctly, even with the current working copy
- A draw-back is the size of the left-hand navigation, but maybe that could be improved.

To overcome these shortcomings in the solution with `www-docs.exe`, there are a few options:
- Once you've made some changes in your local code, copy it over to the `wwwroot` folder of `www-docs`, but be aware that images must go to `images/docs`, rather than `docs/images`
- you could delete the directory `wwwroot` and clone the repository there instead: \
  `git clone https://github.com/moudey/Shell.git wwwroot` \
  There still remains the issue with the `docs/images`
- you could also delete the directory `wwwroot` and make it a junction to your existing git working directory: \
  `mklink /j wwwroot path/to/working-directory` \
  again, the issue with the `docs/images` remains.

To make things easier, 
- the folder `/docs/images` should be moved to `/images/docs` in the main repository
- the folders `assets` and `images` should be moved/merged to the root of the main repository
- the current `www` could also be integrated into the root.
- the current [`/www/README.md`](https://github.com/moudey/Shell/blob/main/www/README.md) could be appended to the existing [`/README.md`](https://github.com/moudey/Shell/blob/main/README.md)
- the new `README.md` would also include the instruction how to use `www-docs.exe`

**Comment by martin-rueegg** [comment]
> It requires .net

Yes, took me quite a while to get it working, as I'm running on a x64 architecture, and when using `winget` to install, it takes that as the default.

So just for the record (if someone else wants to try this), to install the correct _.Net Runtime_, run the following command:

``` cmd
winget install --architecture x86 Microsoft.DotNet.Runtime.7
```

To **find out, if you already have that runtime installed**, run `dotnet --info` and make sure you see the following among the output:

```
.NET runtimes installed:
  ...
  Microsoft.NETCore.App 7.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  ...
```

Important is the installation path!
- `C:\Program Files (x86)\dotnet`, if you run a 64bit version of Windows 
- `C:\Program Files\dotnet` if you run a 32bit version of Windows

If instead you see the following:
```
Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
```

Then try again with the following command:
- `"C:\Program Files (x86)\dotnet\dotnet.exe" --info` in Command Prompt, or
- `& 'C:\Program Files (x86)\dotnet\dotnet.exe' --info` in PowerShell

and check the output again.
