### ISSUE TITLE
[Feature Request] Add option to delay multiple `invoke`

### ISSUE THREAD

**Issue by martin-rueegg** [moudey/Shell#193]
When using [`invoke = 'multiple'`](https://nilesoft.org/docs/syntax/dynamic#property-invoke), all the invocations are virtually simultaneous.

It would be great to be able to specify a delay between the invocations. This could be done in one of two ways:

- Use the `invoke` property itself, with the following syntax: if the value is
  - `0` or `single` => there is only one invocation (as currently)
  - `1` or `multiple` => there is one invocation for every selected item, with now delay (as currently)
  - `integer > 1` => like with `multiple`, but the value is used as a delay in `milliseconds` (or `seconds`) between the different invocations
- Introduce an new property `delay`, indicating the delay as with the above example.

**Comment by moudey** [comment]
>Introduce an new property delay, indicating the delay as with the above example.
A wait property can be customized to allow the delay time to be specified if it is > 1

**Comment by martin-rueegg** [comment]
> A wait property can be customized to allow the delay time to be specified if it is > 1

I see. But if I understand the description of the property correctly, then it would run the next invocation only once the previous has finished. Like so?

**With `wait = 1`**
```
Click by the user
└─ cmd 1 ┐
         └─ cmd 2 ┐
                  └── cmd 3 ┐
                            └── cmd 4
```

**While with `wait = 0`**

```
Click by the user
├── cmd 1
├── cmd 2
├── cmd 3
└── cmd 4
```

However, I was intending a *delay*, rather than a wait. Imagine you want to open 3 Word documents at once. If you have `wait = 0` then three instances of `word.exe` will remain open, as they all start simultaneously and do not know about each other's existence at the time of launch.

But then `wait = 1` would cause **Shell** to wait, until the Word is closed by the user - and then - all of a sudden, open the next document. Which may be immediately (in case there was already an open word instance who then takes over the opening the document and the new instance will close immediately. Or it can take "forever", because the user might simply not close Word or meanwhile have opened another document.

Here is where `wait = 0, delay = 500` comes in: It would start the first Word instance, opening the first document, then launching the second Word instance, opening the second document *but in the first instance* due to DDE-calls, or whatever is used nowadays.

So the delay would cause the following launch sequence:

```
Click by the user
└─┬─ cmd 1
  └─┬─ cmd 2
    └─┬─ cmd 3
      └── cmd 4
```

**Comment by moudey** [comment]
Multiple commands is a feature that is not currently documented. It must be viewed so that we have the idea of ​​working with the delay as well

```
item(title='multi-command' commands {
    cmd-line='/k echo FIRST COMMAND'  invoke=2000,
    cmd-line='/k echo SECOND COMMAND'  invoke=2000,
    cmd='cmd.exe' args { // MULTI-ARGUMENTS
        "/k" "echo THIRD COMMAND"
        "&" 
        "echo Welcome " + @user.name
    }
    //...
})
```

**Comment by martin-rueegg** [comment]
Sorry, it has become quite an extensive answer. Hope it helps! Gosh, sitting 4 hours on this already!

> Multiple commands is a feature that is not currently documented. 

What I figured from your example and from my own tests is, that ...

---

#### 1. there are three different syntax to call a **single** command

- `cmd='executable.exe'` + `args='--list of arguments'` (As currently documented)
- `cmd='executable.exe'` + `args { '--set' 'of' 'arguments' }`[^1] (currently undocumented)
- `cmd-line='/k -list of arguments run by cmd.exe'` (currently undocumented)

This is awesome!

However, the following syntax is **not recognized**:
- `cmd-line { '--set' 'of' 'arguments' 'for' 'cmd.exe' }`

I would suggest to add this syntax just to be consistent. Because then you could say:

- We have the following two ways to define a command:
  - `cmd='executable.exe'` + `args='--list of arguments'`
  - `cmd='executable.exe'` + `args { '--set' 'of' 'arguments' }`[^1]
- In case command is `cmd.exe` there is an abbreviated syntax:
  - `cmd-line='/k echo --list of arguments run by cmd.exe'`
  - `cmd-line { '/k' 'echo' '--set' 'of' 'arguments' 'for' 'cmd.exe' }`

However, my suggested implementation below does deal with this differently!

---

#### 2. there is the possibility of **multiple** commands to be run at once
 - `commands { %single-command% [, %single-command% [, ...]]`

This syntax seems to ignore the item's options `wait = 1` and `invoke = 'multiple'` and even `window = 'Minimized'`. They all run at once, all having the first item in the selection as `@sel.path`, but all items are available through `@sel(true, " ")`.

What I did not figure out, was what this `invoke` argument is suppose to do, as it makes apparently no difference whatsoever (as of now). Was it just meant as an example to define the new `delay` argument?

#### 3. my comments

> It must be viewed so that we have the idea of ​​working with the delay as well

Sure, makes sense.

Firstly, I find the syntax of the `commands{}` property should be changed. Because
- It looks like a `section` (e.g. `var`, `set`, `static`, etc.).
- But then does not follow the syntax of a section, as entries are not enclosed in curly brackets, but separated by commas

So in order to have a consistent syntax, my suggestion would be to change the way commands should be configured altogether. I have described a suggested syntax within the current specification below.

Another approach would be to switch to [YAML](https://yaml.org/). Then you get rid of all the parsing issues as you can just use an existing parser. If that's something you'd consider, I'm happy to help working on a specification for the config files. But it would be quite simple.

---

#### 4. Suggestion for implementation.

1. Deprecate current properties (they still work for now, but do not support the advanced features and their support may be removed in future versions):
   - `cmd`, `command`, and obviously `commands`
   - `arg`, `args`, `arguments`
   - `admin`, `directory`, `invoke`, `verb`, `window`
1. Optionally officially "introduce" the property `cmd-line`, if just a simple command should be executed, no options required or supported. The value is evaluated exactly the same as described in _simple syntax_ below.
1. Introduce a body to the `item` entry (similar as with the `menu` entry) which will be the container for command definitions,
   - general syntax:
      `item ( options ) { commands }`, where the `{ commands }` body is optional.
   - full syntax
     ```
     item ( title = 'title' [ option = value [...] ] )
     [ {                           // <== Begin of new optional body. [ indicates, the block is optional.
      command [ command [...]      // list of cmd entries
     } ]                           // <== Begin of new optional body
     ```
     Note:
     - All commands are started when the user clicks the entry.
     - A `delay` may be specified for an individual command.
     - If chain commands are required, then this can be done with the `on-complete` | `on-success` | `on-error` sections of a given command (see below).
1. Introduce a new `command`/`cmd` entry, which may only appear in the `item`'s body. The entry has two forms of syntax:
   1. **simple syntax**, when no options are required: \
     `cmd = '%command% [ %arguments% ]'`, where 
      - `%command%` must be one of
        - `command.exe` | `"quoted command with space.exe"`
        - `/k` | `/c`, which indicate the invocation of `cmd.exe` with the given switch. (if any other switch for cmd.exe is required, then one has to write e.g. `cmd.exe /T:06 /k echo yellow`).
      - `%arguments%` are optional, but must be in the same string (or concatenated with e.g. `+`)
   1. **extended syntax** when options or chained commands are used
      ```
      cmd ( %options% ) { command-list }
      ```
      where
      - `( %options% )` can be empty if no options are used, like so: `()`.
      - `command-list` has the following syntax
        ```
        [ execute ] %command-line% [ 'additional-agument1' [ 'further arguments' [...] ] ]
        [ on-complete { command [ command [...] } ]
        [ on-success { command [ command [...] } ]
        [ on-error { command [ command [...] } ]
        ```
        where
        - the keyword `execute` is optional. However, if given, it **must** be followed by 
          - an equal sign (`=`) for simple command lines (e.g. `execute = 'explorer.exe /n,c:\'`
          - follow the section syntax and embrace the following command-line and optional arguments within curly brackets '{}'
        - the **first string** (after the execute keyword) is always considered to be the `%command-line%`, which follows the exact same rules as with the short syntax.
        - the `on-complete` commands are always executed, regardless of the exit code of the current command. Replaces the old `wait` property
        - `on-success` commands are only executed, when the current command's exit code is zero (0)
        - `on-error` commands are only executed, when the current command's exit code is non-zero (<>0)
        - all commands in a section start in parallel, respecting their `delay` option
        - optionally, the sections `on-complete`, `on-success`, & `on-error` could also take the short form for simple commands, if there is only one chained command and no options used.
1. Introduce the following (new) options for the new `cmd` entry:
   - `admin` (meaning unchanged)
   - `directory` (meaning unchanged)
   - `verb` (meaning unchanged)
   - `window` (meaning unchanged)
   - `invoke = 'once' | 'every'` (previously `single` and `multiple` respectively; meaning unchanged)
   - `delay = %milliseconds%` to wait, before first invocation
   - `wait = %milliseconds%` to wait, before every subsequent invocation _of the same command_ when `invoke = 'every'`
   - optionally also support the `cmd-line` here. Which would require the `cmd` entry not having a body too!

With this you would have a very consistent syntax that goes along well with the syntax of existing elements. It would also be backwards-compatible. And it would accommodate all the scenarios discussed: multiple commands, multiple invocations, waiting for completion, start delay, intermediate delay.

The implementation software-wise must not be too difficult, if you use a command class to deal with the invocations and chaining.

However, it is also fairly complex, and I'm not sure how many people would actually use this stuff?

#### Here some examples:

1. Simple command
   ```
   item( title='Explore C:\' )  { cmd = 'explorer.exe /n,C:\' }        // new simple syntax
   item( title='Explore C:\' cmd-line = 'explorer.exe /n,C:\' }        // short alternative, no options
   // item( title='Explore C:\'   cmd = 'explorer.exe' args='/n,C:\' ) // old syntax
   ```
1. Simple multi-command
   ```
   item( title='Open Explorer in C:\ and Documents' ) {
      cmd = 'explorer.exe /n,C:\'
      cmd = 'explorer.exe /n,@user.documents'
   }
   ```
1. Run a simple command for every selected item
   ```
   item( title='Show all selected objects in separate explorer window' ) {
      cmd(invoke='every') { 'explorer.exe /n,@sel.path.quoted' }
   }
   ```
1. Show the log file after a command has failed
   ```
   item( title='Show all selected objects in separate explorer window' ) {
      cmd(window='hidden') {
        'update.exe'
        on-error = 'notepad.exe c:\temp\error.log'
      }
   }
   ```
1. A more complex example
   ```
   item( title='Run maintenance' ) {
      cmd(window='hidden', delay = 1800000 /* half an hour so I can close all my documents */ ) {
        'backup.exe'
        on-complete = 'email.exe c:\temp\error.log mail@example.com'
        on-error {
           cmd(window='normal') {
              '/k echo backup failed!'
              '& echo see log at 'c:\temp\error.log'
           }
        }
      }
     cmd ="msg @myteam I'm going home now!"
   }
   ```

 [^1]: Note: Arguments are simply concatenated into one single commandline, as with the `args=`-syntax. The separate arguments do not translate into actually individual arguments.
