### ISSUE TITLE
menu(type='file'   is misleading ?

### ISSUE THREAD

**Issue by xkajxkajx** [moudey/Shell#196]
Hi,
Such a nice tool but there are some issues .

1. menu(type='file'   is misleading because it deals with a (folder's shortcut) in the desktop as a (file)!? 
 (WHICH IS NOT A FILE  AS  YOU KNOW.)

2.How could I replace some registry commands like the following examples ? 
I think I'm gonna use "args=" command ,right ? But how ?

examples:
( cmd /c (echo.|set /p="%1") | clip )
( C:\WINDOWS\Recase.exe /u %1 )
( "D:\PORTABLE\AutoHotkey\Compiler\Ahk2Exe.exe" /Gui /In "%l"  )
("D:\PORTABLE\RegConvert\RegConvert.exe" "/S=%1" /O=bat /T )
( "D:\PORTABLES\Copy Full File Name\Copy Full File Name.exe" 1 %L   )

3. "XnShell    shows images with Low Quality thumbnails.

4. I Added "glyphs.nss"menu. Is it possible to click on the glyph icon and copy its code in the clipboard ?

 Sorry! Too many questions.
Have a nice day .

**Comment by moudey** [comment]
>menu(type='file' is misleading because it deals with a (folder's shortcut) in the desktop as a (file)!?
    (WHICH IS NOT A FILE AS YOU KNOW.)

Shell treats the shortcut as a file so you can edit it.

>"XnShell shows images with Low Quality thumbnails

Items that use direct drawing such as "XnShell" are skipped and not processed by Shell

>How could I replace some registry commands like the following examples ?

Only reading registry data is currently supported
```
item(title='Content Type' cmd=msg(reg(reg.cr,'.exe','Content Type',reg.sz)))
```

>I Added "glyphs.nss"menu. Is it possible to click on the glyph icon and copy its code in the clipboard ?

Do you mean to add a copy to clipboard button in the Glyph gallery on the site?

**Comment by martin-rueegg** [comment]
>     4. I Added "glyphs.nss"menu. Is it possible to click on the glyph icon and copy its code in the clipboard ?

@moudey, I guess @xkajxkajx is looking for something like this:

```
menu(
	title     = 'Glyphs'
	type      = 'taskbar'
	separator = 'both'
	image     = \uE0DA
)
{

	item(
		col         = 0
    	image       = \uE001
		cmd         = command.copy('\uE001')
	)

	item(
    	image       = \uE002
		cmd         = command.copy('\uE002')
	)

}
```

Would be awesome to complete the file with all the available glyphs! @xkajxkajx, did you create such a file? And if so, would you be willing to share it? So it could be included in the `/config` folder as an example ...
