### ISSUE TITLE
[Feature] Funktion `path.link.*`

### ISSUE THREAD

**Issue by martin-rueegg** [moudey/Shell#204]
You can handle the shortcut file through `path.lnktarget` function.
```
item(type='file|dir' find='.lnk' title='open arget' cmd=@path.lnktarget(sel.path))
```
I will develop a function `path.lnktarget` to specify the type of shortcut file and add other options.

- [x] Implement
- [ ] Test
- [ ] Release
- [ ] Document

**Comment by martin-rueegg** [comment]
@moudey [wrote](https://github.com/moudey/Shell/issues/197#issuecomment-1467091317):

> The following functions have been added to return shortcut file information:
> 
> `path.lnk.target` Return the file path
> `path.lnk.dir` Returns the work dir path
> `path.lnk.type` Shortcut type returned 0=unknown, 1 = file, 2 = dir
> 
> https://nilesoft.org/download/shell/debug.zip

**Comment by martin-rueegg** [comment]
> `path.lnk.type` Shortcut type returned 0=unknown, 1 = file, 2 = dir

Does "unknown" mean, it is unknown whether it is a link or not? Or is it sure it _is_ a link, but only the _target_ is unknown, e.g. does not exist?

How would you find out if a file is a regular file or a link? Would you use [`path.type`](https://nilesoft.org/docs/functions/path#path.type) for that? e.g.:

```
path.type(path) == type.file
// vs
path.type(path) == type.link
```
- Does `type.link` exist?
- Could you add `path.isLink()`?

can you also use `sel.path.type()` rather than `path.type(sel.path)`?

**Comment by moudey** [comment]
These results are only limited to common types:
0=Unknown or the target may not exist 
1= file
2 = directory
3 = drive

>Could you add path.isLink()?
>How would you find out if a file is a regular file or a link? Would you use [path.type](https://nilesoft.org/docs/functions/path#path.type) for that? e.g.:

There is no function for this currently, but a function can be added to verify this and return all information from the shortcut file.
