### ISSUE TITLE
[Question] Background Accent Color

### ISSUE THREAD

**Issue by ClifffordW** [moudey/Shell#209]
Is there way to make the background from black to slight accent color ?
![image](https://user-images.githubusercontent.com/55302963/226063431-3efbf88c-e8e8-4fcd-ba84-5610ef687c6a.png)

**Comment by hiranokite** [comment]
change `effect` value on theme.nss, and adjust as you like
```
effect = [3, color.accent_light3, 20]
```

**Comment by SteffanDonal** [comment]
Here's my go-to accent preset for background: `theme.background.effect = ["acrylic", color.dark(color.accent, 65), 20]`

**Comment by ClifffordW** [comment]
Where can I find list of all the effects like you mentioned acrylic

**Comment by SteffanDonal** [comment]
There's only that single effect, currently.
