### ISSUE TITLE
Some elements on the taskbar return false when calling this.taskbar

### ISSUE THREAD

**Issue by Nicryc** [moudey/Shell#21]
I don't know if it is a bug or an expected behaviour but some elements on the taskbar return false when calling `this.taskbar` and even more they return false when calling any of `this.desktop`, `this.explorer` or `this.nav`. This could be confusing, prone to error and inconsistent theming.

### Steps to reproduce:
If you write the following code, you will see that the contextual menus from the start button, the tray icons or the notification button will appear black while a right click on an empty part of the taskbar will appear white.

```
theme = if(this.taskbar, theme.white, if(this.explorer, theme.white, if(this.nav, theme.white, if(this.desktop, theme.white, theme.black))))
```

![taskbar_windows_10](https://user-images.githubusercontent.com/15157120/183298077-84c73d73-038a-454f-ad3d-961268b4365c.png)

### Expected behaviour
I think any click on the taskbar should be themed following the `this.taskbar` function.

### System informations
OS: Windows 10
Shell version: 1.7.0

**Comment by moudey** [comment]
@Nicryc,
Yes, it is a bug because these window handles of these menus do not return to the taskbar function.
