### ISSUE TITLE
Shell taskbar context-menu not showing on secondary monitors

### ISSUE THREAD

**Issue by OscarDL** [moudey/Shell#214]
I'm not sure if this is a technical limitation or not, and if it's already a known issue, but I couldn't find it myself in any of the currently open issues, so here's my issue:

Shell's custom taskbar context-menu does not seem to show on my secondary screen. Instead, the regular Windows one appears, which admittedly is very frustrating after getting used to the one Shell provides, which is infinitely more useful.

![XACgOe0xjh](https://user-images.githubusercontent.com/27915933/226181491-ca1183a5-9ae9-47f8-891b-d6f6ebbe4485.gif)

Currently running Shell v1.8.1, on Windows 11 Pro 22H2 (OS build: 22624.1465)
Let me know if you need any other information!

**Comment by moudey** [comment]
Please refer to [#181](https://github.com/moudey/Shell/discussions/181#discussioncomment-5347478)
