### ISSUE TITLE
Customization elements are forced even if the `shell.shl` file is empty

### ISSUE THREAD

**Issue by Nicryc** [moudey/Shell#22]
An empty `shell.shl` will still customize some aspect of the contextual menu. The following file will result in added icons, frame resizing (especially true for the taskbar contextual menu) and hidden borders.

```
shell 
{

}
```

### Screenshots
_Vanilla Windows taskbar contextual menu on the left and with an empty `shell.shl` file on the right:_
![taskbar_contextual_menu_diff](https://user-images.githubusercontent.com/15157120/183302261-7e15aaea-5581-4105-8a07-939c76bb8511.png)

_Vanilla Windows explorer contextual menu on the left and with an empty `shell.shl` file on the right:_
![explorer_contextual_menu_diff](https://user-images.githubusercontent.com/15157120/183302357-c275e616-3f57-4eaa-810e-88844012b9ee.png)

### Expected behaviour
An empty `shell.shl` file should leave the vanilla Windows appearance and let the decision to the user to customize it as he wants.

### System informations
OS: Windows 10
Shell version: 1.7.0

**Comment by moudey** [comment]
These are default settings to disable use the following options:

```
default {
   static-auto=false
}
```

More options can be added in the future to disable Shell customizations.

**Comment by moudey** [comment]
> Expected behaviour
> An empty shell.shl file should leave the vanilla Windows appearance and let the decision to the user to customize it as he wants.

Good suggestion, I will try to implement it.

**Comment by moudey** [comment]
Please test this issue with [shell 1.8 beta](https://nilesoft.org/download)
