### ISSUE TITLE
The CTRL+WIN shortcut does not restore the W11 taskbar context menu

### ISSUE THREAD

**Issue by SteffanDonal** [moudey/Shell#222]
Not a critical issue, but it means that if Shell breaks (some config errors require Explorer restarts), the taskbar context menu is not accessible.

**Comment by moudey** [comment]
Have you tried the latest [build](https://nilesoft.org/download/shell/debug.zip)?

This issue has been improved if Shell fails.  But the <kbd>win+ctrl</kbd> key issue will be fixed.

**Comment by moudey** [comment]
This issue has been fixed try this [build](https://nilesoft.org/download/shell/debug.zip)

<kbd>RIGHT-CLICK</kbd> or <kbd>SHEIFT</kbd> + <kbd>F10</kbd> and
<kbd>CTRL</kbd> + <kbd>WIN</kbd> Restore the default context menu of the taskbar.
<kbd>CTRL</kbd>  Re-apply shell settings.

**Comment by SteffanDonal** [comment]
I tested this; it appears to work mostly, however:
- Using `CTRL` does not restore Shell's custom menu on the taskbar
- Using `CTRL` in File Explorer _does_ restore all Shell functionality as expected, **except**
- Sometimes, the taskbar freezes for a period of time before the menu works again
- I could crash `explorer.exe` by holding `CTRL` and spam-right-clicking File Explorer, then tried to right-click the taskbar.
