### ISSUE TITLE
How to add the context menu "Open Folder as PyCharm Project" to the main/root view of context menu (not in the more options context menu)?

### ISSUE THREAD

**Issue by bigplayer-ai** [moudey/Shell#224]
In the application: "Shell Powerful manager for Windows File Explorer context menu. (https://github.com/moudey/Shell and https://nilesoft.org/docs). How to add the context menu "Open Folder as PyCharm Project" to the main/root view of context menu (not in the more options context menu)?

**Comment by moudey** [comment]
Does this item exist, but it is moved to "more options"?

**Comment by bigplayer-ai** [comment]
> Does this item exist, but it is moved to "more options"?

Yes indeed check the picture below
![0BEB22CC-AE66-4352-9D47-4AEC9D993F84](https://user-images.githubusercontent.com/119108387/229314024-fb14c3ff-0d91-457c-af28-12eaa0a7280e.png)

**Comment by moudey** [comment]
Open `shell.nss` and go to static section at this line
```
item(where=this.title.length > 25 menu=title.more_options)
```

You have two options:

1- The first is to disable this command by deleting it or placing a `//` sign at the beginning of the line
```
// item(where=this.title.length > 25 menu=title.more_options)
```

2- Ignore moving this item through the following command
```
 item(where=(this.title.length > 25 and this.name !="Open Folder as PyCharm Project" ) menu=title.more_options)
```

Save changes, press <kbd>CTRL</kbd> + <kbd>RIGHT-CLICK</kbd> to reload settings.

**Comment by bigplayer-ai** [comment]
Thanks

**Comment by moudey** [comment]
If you change the title and it is less than 25 characters, the previous modification must be deleted

```
 item(find="Open Folder as PyCharm Project" title='Open as PyCharm')
```
