### ISSUE TITLE
Extra spaces when right-clicking a file

### ISSUE THREAD

**Issue by NVHT** [moudey/Shell#227]
![image](https://user-images.githubusercontent.com/8341213/230703665-757a1c0b-e744-42dd-854e-52129e0a9465.png)

**Comment by moudey** [comment]
Did you modify the configuration files?

**Comment by NVHT** [comment]
> Did you modify the configuration files?

What config files do you mean?

**Comment by moudey** [comment]
Does this issue appear in all menus?

**Comment by moudey** [comment]
@NVHT  Please try this [build](https://nilesoft.org/download/shell/debug.zip)

**Comment by NVHT** [comment]
The issue is still there.
![image](https://user-images.githubusercontent.com/8341213/232314075-764a78cd-867a-45b6-9175-b3db86376726.png)
![image](https://user-images.githubusercontent.com/8341213/232314084-ccb99317-256a-4143-8a64-6179c0ff42ff.png)

**Comment by moudey** [comment]
Have you tried the build in the link? 
The menu theme is supposed to be black.

**Comment by NVHT** [comment]
> Have you tried the build in the link? The menu theme is supposed to be black.
> You must unregister the shell and then register the last build.

Same build from the link, however, I changed it to modern style.

**Comment by froggz19** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/8935954/234645260-c132e3f3-c102-456d-9d39-88c01ace6bef.png)

**Comment by moudey** [comment]
Please disable modification items in "shell.nss" file
```
// import 'imports/modifications.nss'
```

**Comment by froggz19** [comment]
> 

same problem :(

**Comment by NVHT** [comment]
> Please disable modification items in "shell.nss" file
> 
> ```
> // import 'imports/modifications.nss'
> ```

It didn't solve it.

**Comment by moudey** [comment]
@NVHT, @froggz19 Please try this [build 25](https://nilesoft.org/download/shell/debug.zip)

**Comment by StevenElev11n** [comment]
Just wanted to report that I have the same problem.

**Comment by NVHT** [comment]
> @NVHT, @froggz19 Please try this [build 25](https://nilesoft.org/download/shell/debug.zip)

It didn't work.

**Comment by moudey** [comment]
@NVHT Please try this [build 26](https://nilesoft.org/download/shell/debug.zip) and attach "shell.log" file.

**Comment by froggz19** [comment]
> @NVHT Please try this [build 26](https://nilesoft.org/download/shell/debug.zip) and attach "shell.log" file.

Same problem with this build.
Here's the log, I hope it helps solving the issue.
[shell_log.zip](https://github.com/moudey/Shell/files/11359840/shell_log.zip)

**Comment by moudey** [comment]
To bypass this issue use the following command
```
modify(type='file' where=this.disabled find='Edit with Notepad++' vis="remove")

// Or remove all items that are disabled
modify(type='file' where=this.disabled vis="remove")
```

**Comment by moudey** [comment]
@NVHT, @froggz19, @StevenElev11n Please try this [build 28](https://nilesoft.org/download/shell/debug.zip)

**Comment by NVHT** [comment]
> 

Fixed. Thanks.

**Comment by StevenElev11n** [comment]
> @NVHT, @froggz19, @StevenElev11n Please try this [build 28](https://nilesoft.org/download/shell/debug.zip)

Hi,
I just wanted to report that the extra space issue is fixed with build 28. I'm looking forward the the next update.

Best regards,

**Comment by moudey** [comment]
@rp1231 Place it before any modification command

 > Build 28 works but it has the black theme which I don't prefer........

Change `theme.name` to `modern`

**Comment by moudey** [comment]
> There is no modifications.nss file in the 1.8.1 installation like there is in the debug version. And there are no modification commands in the other nss files.

The debug version differs in a lot from previous versions.

**Comment by moudey** [comment]
> So where do I place the modify line in the 1.8.1 version?

in static section, but replace `modify` with `item`

**Comment by pavichokche** [comment]
I just wanted to chime in that I did a clean install of 1.8.1 on a few systems (for the first time) and they all exhibited this bug until I added the line at the end of the shell.nss 'static' section:
item(type='file' where=this.disabled find='Edit with Notepad++' vis="remove")

So there is still a fix needed in the software (which is awesome and I really appreciate!)
