### ISSUE TITLE
Combine glyphs of different colors

### ISSUE THREAD

**Issue by TheChilliPL** [moudey/Shell#228]
On the webpage, there's a lot of glyphs that seem could go together very well. Is there a way to draw multiple glyphs on the same icon, all with different colors? It could go well with the default styling of the copy/cut/paste commands.

**Comment by moudey** [comment]
It will be available in the next update

**Comment by moudey** [comment]
Hi @TheChilliPL The feature of combining two glyphs is now available in this [build](https://nilesoft.org/download/shell/debug.zip)

```
// Shell Icons
item(mode="multiple" title='test combine glyphs default1' image=[[\uE069],[\uE06A]])
item(mode="multiple" title='test combine glyphs default2' image=[[\uE069, #f00],[\uE06A, #00f]])

// Segoe Fluent Icons
item(mode="multiple" title='test combine glyphs1' image=[[\uE0A5, #f00],[\uE006, #fff], "Segoe Fluent Icons"])
item(mode="multiple" title='test combine glyphs2' image=[[\uE91F, #00f],[\uE170, #0f0], "Segoe Fluent Icons"])
```

![screenshot_20230416_085840](https://user-images.githubusercontent.com/39198/232279091-e4f638dc-28e8-4169-a28f-7ebc6b8f141d.png)

**Comment by TheChilliPL** [comment]
Why is the context menu so huge in that update?
![image](https://user-images.githubusercontent.com/18823939/232324817-26107ba6-264c-4ed1-9296-0c42de8ff505.png)

**Comment by TheChilliPL** [comment]
For some reason, this version with this config doesn't seem to have most icons, like `View`, `Sort by`, `Group by`?

![image](https://user-images.githubusercontent.com/18823939/232325347-b8582c44-d372-4fa4-976d-8e94093ec7cf.png)

**Comment by hiranokite** [comment]
> For some reason, this version with this config doesn't seem to have most icons, like `View`, `Sort by`, `Group by`?

go to `imports\theme.nss`and change `theme.name` from `black` to `modern`.
