### ISSUE TITLE
Position relative to another menu item

### ISSUE THREAD

**Issue by TheChilliPL** [moudey/Shell#229]
Is there any easy way to set a certain menu item to be immediately after (or before) another menu item? I'd like to have the LinkShellExtension “Pick Link Source” item right after the built-in “Copy”, but the “Copy” option doesn't have a static position, so no matter what number I set, it's not correct all the time.

**Comment by moudey** [comment]
Use the `indexof` function to find the position of the menu item
```
item(title="test" pos=indexof("copy"))
```
#19

**Comment by TheChilliPL** [comment]
I seem to be unable to place it after Copy.

`pos=indexof("Copy")` has this effect:
![image](https://user-images.githubusercontent.com/18823939/230922682-3a83461f-914d-4f02-8e23-2d7727b80bee.png)

yet `pos=indexof("Copy")+1` (or even `+0.001`) moves my menu item all the way down:
![image](https://user-images.githubusercontent.com/18823939/230922867-785eb2e2-2ecb-4409-81d7-893cbaf3545f.png)

**Comment by TheChilliPL** [comment]
It does work, thanks! Could be worth adding this `indexof` function to the documentation, I cannot find a single mention of that at all

**Comment by breadgrocery** [comment]
Since `indexof` is item display-name-based, it won't work in non-English locales ("Copy" differs accross locales).
Instead, using `str.res` is more flexible.
```
pos=indexof(str.res("shell32.dll", 4146), 1)
```

**Comment by RubicBG** [comment]
> Since `indexof` is item display-name-based, it won't work in non-English locales ("Copy" differs accross locales). Instead, using `str.res` is more flexible.
> 
> ```
> pos=indexof(str.res("shell32.dll", 4146), 1)
> ```

write "Copy" in your language to see it

**Comment by RubicBG** [comment]
Apparently I'm still asleep - I didn't see the whole conversation. it is as you say.
I personally use a different approach.
```js
pos=indexof(str.replace(title.copy, '&', ''), 1)
```
