### ISSUE TITLE
Any settings for background and text colors?

### ISSUE THREAD

**Issue by ghost** [moudey/Shell#23]
The modern_dark color does not reflect the one used by my current theme.

**Comment by moudey** [comment]
Standard colors are used for Windows 11, Windows 10, and system colors for the time being. In the next update, the colors of the Windows theme will be applied. 

To change the colors to a favorite color, use the following code:
```
default {
    item-text = [#fff, #fff]
    item-back = [#000, #333]
    separator-color = color.accent
    frame-color = color.accent
    symbol = [color.accent, color.accent]
}
```

**Comment by mki77** [comment]
Nice! Thank you.
