### ISSUE TITLE
unnecessary submenu

### ISSUE THREAD

**Issue by bl4xe** [moudey/Shell#230]
![image](https://user-images.githubusercontent.com/96691738/230733254-fc87ee31-2456-40d5-969c-21980084571a.png)
not sure if this is only with radeon gpus or if there is other programmes that would show up in this submenu but I'm pretty sure this could use a fix if you can call it that.

**Comment by hiranokite** [comment]
move items by title length is enabled on your configuration, search for `where=this.title.len` and delete the entire line or just add `//` at the beginning of the line.
e.g.
`//item(where=this.title.len > 20 tip=this.title parent=@id.more_options.title)`

after editing `CTRL + RIGHT-CLICK` on desktop to reload config or just restart explorer.

**Comment by Patz12** [comment]
> 

I commented the line and now I have the AMD Adrenaline option on the main menu.
This kind of options can be added/removed by modifying the static.nss file? Lets say I want to remove AMD Adrenaline, both Git options, and maybe add OneDrive

**Comment by moudey** [comment]
> I commented the line and now I have the AMD Adrenaline option on the main menu.
This kind of options can be added/removed by modifying the static.nss file? Lets say I want to remove AMD Adrenaline, both Git options, and maybe add OneDrive

A static section for editing regular context menu items.
Dynamic section through which you can add new items.

The static, dynamic, variables and images section will be dropped and will be handled directly from the body of the configuration file. You will find this clear in the [debug](https://nilesoft.org/download/shell/debug.zip) version.
