### ISSUE TITLE
Visual studio code extension for syntax highlighting

### ISSUE THREAD

**Issue by StarNumber12046** [moudey/Shell#232]
otherwise it is impossible to distinguish stuff

**Comment by moudey** [comment]
#81

**Comment by moudey** [comment]
Use any editor and apply the settings of any of these languages C/C++, C# or JS.

Duplicate of #81

**Comment by nathanpovo** [comment]
An third-party extension can be found here https://marketplace.visualstudio.com/items?itemName=code-nature.nilesoft-shell-file-formatter

Source https://github.com/moudey/Shell/discussions/81#discussioncomment-6075891
