### ISSUE TITLE
How to Display format menu for USB Drive

### ISSUE THREAD

**Issue by CiquattroFPV** [moudey/Shell#235]
Anyone can help me to understand how to show again the format menu for format USB pen Drives?

I'm going to do it manually now via DISK PART but will be fine to be implement by default

**Comment by hiranokite** [comment]
have you looked inside the `More options` menu?

![image](https://user-images.githubusercontent.com/5361459/232291070-be4daeaa-04e0-4d45-bcc8-8fb542f1bbf3.png)
