### ISSUE TITLE
[Feature Request] Single line with multiple options

### ISSUE THREAD

**Issue by hboyd2003** [moudey/Shell#237]
For all its problems Windows 11's default context menu does have one feature of great benefit. That is its multiple context menu items on a single line. It enables the context menu to be much shorter in length while also decreasing the distance the user needs to move to select an option, increasing productivity

This menu type would be limited to just a few items (5-6) and would not allow titles (or the title could be show as a tooltip only). It would also allow dividers in between the items. The items could be centered, on the left, right, or justified. 

An example use for this would be the terminal. Instead of a having to wait for a submenu a simply two icons side by side could be used. 

Windows 11 Default icon menu:
![Screenshot 2023-04-18 171729](https://user-images.githubusercontent.com/8950185/232917316-6ebd0e1e-3f8d-4b5a-b5fa-6da83dab8ad7.png)

**Comment by hiranokite** [comment]
duplicate of #104, it will be added on future.

**Comment by hboyd2003** [comment]
@hiranokite I see! It seems I missed that one! Ill close this topic.
