### ISSUE TITLE
Weird icon

### ISSUE THREAD

**Issue by marciozomb13** [moudey/Shell#239]
<img width="401" alt="Captura de tela 2023-04-20 222648" src="https://user-images.githubusercontent.com/2564929/233519395-2e88b6c6-7cef-4adb-852f-5f6cd1173710.png">

Using an icon from segoe symbols but the result is weird, might be a bug, my code for it
title='Tornar-se Proprietário' image=image.segoe(\uE1DE)

**Comment by hiranokite** [comment]
which Shell and Windows build are you using?

![image](https://user-images.githubusercontent.com/5361459/233520117-932ac46b-b26a-44f5-9d30-6150882046fd.png)

**Comment by marciozomb13** [comment]
Sorry, Shell 1.80, Windows 11 22h2 (not insider) (I'm not close to the pc right now to get exactly build number but I'll update this as soon as possible.) Thank you.

**Comment by moudey** [comment]
This issue has been fixed #212
