### ISSUE TITLE
[Feature request] Eject fixed drive

### ISSUE THREAD

**Issue by jairocontreras** [moudey/Shell#242]
```
item(type='fixed' title="Eject" cmd=command.eject)
```

my usb flash drive is removable but shows up as fixed and can be safely ejected from the system tray but not the file explorer context menu in this pc

**Comment by moudey** [comment]
Does `Eject` item appear in submenu `More options` when usb drive is selected?

**Comment by jairocontreras** [comment]
nope, not by default or using `id.eject`
