### ISSUE TITLE
Context menu becomes unresponsive/laggy on mouse hover

### ISSUE THREAD

**Issue by froggz19** [moudey/Shell#243]
Context menu becomes unresponsive/laggy if you keep hovering the mouse cursor over it.

https://user-images.githubusercontent.com/8935954/235319406-920dfe67-b27c-4a16-87fd-66e7adb0c547.mp4

**Comment by moudey** [comment]
I think this is the result of writing to the log file. Try this [build 27](https://nilesoft.org/download/shell/debug.zip)

**Comment by froggz19** [comment]
> I think this is the result of writing to the log file. Try this [build 27](https://nilesoft.org/download/shell/debug.zip)

That didn't help, sorry.

**Comment by moudey** [comment]
This issue did not appear with me. Did you try on a VM?
