### ISSUE TITLE
Minor UI issue with StartAllBack classic start menu

### ISSUE THREAD

**Issue by designgears** [moudey/Shell#246]
StartAllBack classic start menu introduces a minor UI issue when the `Lock the taskbar` option is selected. It looks like it adds a new column for the checkmark showing that it is enabled.

![image](https://user-images.githubusercontent.com/799451/235413359-9fb0da9f-0f03-4a77-83f1-679a8b4729ea.png)
![image](https://user-images.githubusercontent.com/799451/235413375-ebf1758b-d0e5-4ce6-a1e9-cbbe2306a28f.png)
![image](https://user-images.githubusercontent.com/799451/235413390-bdb3261a-5ef0-4133-8a71-de1ecf791c92.png)

**Comment by designgears** [comment]
Looks like it happens to all of the options, maybe that is working as intended. I'll leave it to you. 

![image](https://user-images.githubusercontent.com/799451/235413882-9096cbe8-7106-444f-a373-be1639d72943.png)

**Comment by hiranokite** [comment]
change theme.image.align to 0

**Comment by designgears** [comment]
> change theme.image.align to 0

Very nice, thank you!
