### ISSUE TITLE
Win+X menu (Start Menu context menu)

### ISSUE THREAD

**Issue by kronuschan** [moudey/Shell#25]
What type do I use to alter just the Win+X menu? I don't see it listed in the documentation?

**Comment by moudey** [comment]
Modifying Win+X menu by adding, deleting or changing, or titleing will cause the explorer to crashed, so work is limited to changing the appearance and only adding images for now until this issue is fixed.

**Comment by moudey** [comment]
I just tested it and noticed that some properties are applied to `WIN+X` menu, I will work on fixing this issue.

**Comment by moudey** [comment]
@kronuschan Please try this [bulld](https://github.com/moudey/Shell/files/10180947/shell-test.zip)
