### ISSUE TITLE
Positioning Bug

### ISSUE THREAD

**Issue by mjbelow** [moudey/Shell#252]
Shell version 1.8.1
Installer: setup.exe
SHA-1: 91FB304E587AF0BE920B0A713B25C372015765B2

Right clicking the background of a folder, The Shell sections (More options... Go To) are displayed at the top, which I imagine is the expected behavior.

![folder background](https://user-images.githubusercontent.com/55146074/236690723-20d2ac86-b648-4752-a037-47563b73a277.png)

But when right clicking on the desktop background, this paste section is being displayed above the Shell sections.
Don't know if this is a bug or intended, but I would prefer the behavior of the first screenshot.

![desktop background](https://user-images.githubusercontent.com/55146074/236690722-dd57bf81-608c-428c-9e1b-9745eced8290.png)

**Comment by moudey** [comment]
@mjbelow Thanks for your feedback

The default position value for new items is `middle`
