### ISSUE TITLE
Questions about the @icon. property & (Accent) Colors

### ISSUE THREAD

**Issue by kronuschan** [moudey/Shell#26]
Hey there, thanks for providing Shell, it's been great!

I have been trying to alter some context menus and found this peculiar property in the config file that ships alongside Shell that I wanted to try to do some stuff with, it's called `@icon.`, specified under `image=`. After having messed with it for a while, had a few questions about it.

First, I found that there are a bunch of terms it accepts, such as options, search, and more, in addition to those listed in the main shell file.  However, I can't seem to find out where these entries are sourced from; some things work, but others don't. Could it be possible to make a list for this?

An additional question I have is that I noticed that when I specify `image=@icon.more_options`, the icon has a bit of coloration applied to it (the arrow). Another one that does this is `image=@icon.copy_path`. Are there other icons that do this, will they be added, or can I specify custom ones? 

Lastly, will it be possible to recolor the blue in some of the icons to use the accent color instead? An excellent project for reference that does precisely this for the default Windows 11 context menus, among other things is this: https://github.com/krlvm/AccentColorizer-E11

Regardless, thanks in advance for answering, and thanks again for providing such an awesome tool it has been a blast using it!

**Comment by moudey** [comment]
New additions to colors
```
color.invert(#f00)

color.accent_light1
color.accent_light2
color.accent_light3
color.accent_dark1
color.accent_dark2
color.accent_dark3
```
