### ISSUE TITLE
Title bug

### ISSUE THREAD

**Issue by IrishBruse** [moudey/Shell#260]
Bug with displaying title

Every space after a variable like this gets eaten

`item(title='@sel.parent.name    test')`

![image](https://github.com/moudey/Shell/assets/14964651/4df415d6-2ad8-4388-ae1b-44b18e51d4c7)

**Comment by moudey** [comment]
@IrishBruse Thanks for your feedback

This issue has been fixed. You can try it in [debug](https://nilesoft.org/download/shell/debug.zip) version.
