### ISSUE TITLE
duplicate entry in submenu

### ISSUE THREAD

**Issue by SaiyajinK** [moudey/Shell#263]
Hi,

I could notice a duplicate entry for Edit with Notepad++ (the bottom one is grayed out)

![XwsMnk6Yrb](https://github.com/moudey/Shell/assets/105972098/68d69bc7-da68-41d6-a1e2-df0638ea5564)

How to remove the duplicate?

in **shell.nss** :

```
menu(type='desktop|file' mode="multiple" title="Édition..." image=icon.edit)
		{
		item(title='Ant Renamer' image=\uE281 cmd='C:\Program Files (x86)\Ant Renamer\Renamer.exe')
		}
```

in **static.nss** :

```
//move

item(find='Éditer avec Notepad++' menu='Édition...')
```

Impossible to remove the duplicate.
An idea ?

Thanks ++

**Comment by moudey** [comment]
Add this command before the move command
```
item(where=this.disabled find='Éditer avec Notepad++' vis=0)
```

**Comment by SaiyajinK** [comment]
@moudey problem solved, thanks for the speed!
