### ISSUE TITLE
More Options menu, Notepad++

### ISSUE THREAD

**Issue by atillagoguslu** [moudey/Shell#264]
Hello,
When I drop Notepad++ under the "More options" menu, it becomes grayed out and unclickable.

Default:
![1](https://github.com/moudey/Shell/assets/1498104/9af22191-ad4e-4bc2-825f-82abdb99e37b)
I add this line to static:
![2](https://github.com/moudey/Shell/assets/1498104/ba1f4961-ecd7-48db-9b4c-cebeb0eeef6b)
It became this:
![3](https://github.com/moudey/Shell/assets/1498104/2ccd072d-e777-4af3-872b-7f406517f7cf)

Have a nice day.

**Comment by moudey** [comment]
Enable it with moving
```
item(find='edit with notepad++' vis=1 pos=15 sep="both" menu=title.more_options)
```
