### ISSUE TITLE
Duplicate Entry "Power Rename" from Microsoft PowerToys

### ISSUE THREAD

**Issue by detile** [moudey/Shell#265]
Shell : v 1.8.1
PowerToys : 0.69.1

The entry Power Rename (a function included in [Microsoft PowerToys](https://github.com/microsoft/PowerToys)) is added twice in Shell right click.

Right click on an empty space
![empty_space_Rclick](https://github.com/moudey/Shell/assets/7447705/6726c67e-a84a-45c0-912c-1a94e7da9e8a)

Right click on a file
![file_Rclick](https://github.com/moudey/Shell/assets/7447705/99b4a902-5834-407d-a02c-19a396b588be)

**Comment by moudey** [comment]
Please refer to this topic #210

**Comment by detile** [comment]
Thanks a lot, i should have noticed  the other topic. My bad.
