### ISSUE TITLE
Duplicate entry "Copy the access path" from "File Mange".

### ISSUE THREAD

**Issue by dracp** [moudey/Shell#266]
In **SHELL 1.8.32**, the "Copy the access path" entry is duplicated in the "File Mange" submenu.

![230520 SHELL 1 8 32_Copiar ruta_Duplicado desde File Manage](https://github.com/moudey/Shell/assets/102802425/919105f3-404f-4212-8bad-84d85611be01)

**Comment by moudey** [comment]
The first item of the system has been moved from the main menu to here. The second item is a new submenu that contains several other orders.

**Comment by dracp** [comment]
> The first item of the system has been moved from the main menu to here. The second item is a new submenu that contains several other orders.

Yes, I understand. Thank you for the answer.

But I still think there is a duplicity of actions. Both "Copy as path" of Windows and the first action of the "Copy path" submenu of Shell, **give the same result: "Full path of the item (File/Folder)".**

![230520 SHELL 1 8 32_Copiar ruta_Detalle](https://github.com/moudey/Shell/assets/102802425/a71eb0d4-fc5d-4786-999e-a5f054ce7d49)

**Comment by moudey** [comment]
You can remove this item instead of moving it to "File Manage".
```
// satatic section
item(where=this.id==id.copy_as_path vis=0)
```

**Comment by dracp** [comment]
> The copy as path item is only available in Windows 10 or earlier when pressing Shift
> 
> You can remove this item instead of moving it to "File Manage".
> 
> ```
> // static section
> item(where=this.id==id.copy_as_path vis=0)
> ```

Thank you very much for answering. I take this opportunity to congratulate you for your great work.
Best regards.
