### ISSUE TITLE
Visual Desktop issues

### ISSUE THREAD

**Issue by AlecMcCutcheon** [moudey/Shell#27]
The background around my desktop icons keeps becoming black and then the wallpaper turns black and I have to restart file explorer to get it back. I has happened multiple times within just a few mins

**Comment by moudey** [comment]
Hi @AlecMcCutcheon,
I have tried Shell with Virtual Desktop on Windows x64 10/11 and the issue does not appear to me. Try using Shell with Virtual Desktop on a clean of Windows. there may be a conflict with a other program.

**Comment by moudey** [comment]
Hi @AlecMcCutcheon Please try this [bulld](https://github.com/moudey/Shell/files/10180947/shell-test.zip)

**Comment by moudey** [comment]
Hi @AlecMcCutcheon, Does this issue still appear?

**Comment by AlecMcCutcheon** [comment]
@moudey I don't see this Issue anymore
