### ISSUE TITLE
Include create a txt file of directory content

### ISSUE THREAD

**Issue by d3smo** [moudey/Shell#276]
Could it be possible to include a line to have the ability of creating a text file of the directory content. Like this cmd does
dir /b >filename.txt

**Comment by dracp** [comment]
> Could it be possible to include a line to have the ability of creating a text file of the directory content. Like this cmd does dir /b >filename.txt

On the web page (https://pacoportillo.es/informatica-basica/crear-listado-con-los-archivos-de-carpeta/) **I found a Script that directly executes the command "dir /b > list.txt".**

I have inserted a new line in the file "file-manage.nss" and it works correctly.

SHELL 1.8.38
//file.manage.nss

item(type='back.dir' title='Listado del directorio' image=[\uE0AD,#4CC2FE] cmd='D:\PROGRAMAS\PORTABLES\SHELL Menú Contextual\_TRADUCCIÓN - EDICIÓN SHELL\Listado de archivos.bat')


The argument of the command "cmd" is the 'Path of the script':D:\PROGRAMAS\PORTABLES\SHELL Menú Contextual\_TRADUCCIÓN - EDICIÓN SHELL\Listado de archivos.bat 

I have changed the name of the script "0000_copiarNombresArchivos_de_carpeta_a_txt.bat" to "Listado de archivos.bat"


![230801_SHELL 1 8 38_Listado de Archivos](https://github.com/moudey/Shell/assets/102802425/659a9dcf-ce2a-4a75-8fa7-ac6fde72de67)

**Comment by dracp** [comment]
> Could it be possible to include a line to have the ability of creating a text file of the directory content. Like this cmd does dir /b >filename.txt

Solved, thanks to the help of **Rubic** (Discord/Nilesoft Community)                                                                                                                                                                                                                                                                                                                

The bottom line, directly creates a listing of the directory items in a file titled "#Listado_Directorio.txt".

**item(type='back.dir' title='Listado del directorio' image=[\uE03B] cmd args=' /k (dir/b > #Listado_Directorio.txt) & exit')**

**Comment by d3smo** [comment]
Works perfectly, here is just an update to have an image working for all and english translation 

item(type='back.dir' title='File List to txt File' image=icon.new_file cmd args=' /k (dir/b > File_List.txt) & exit')
