### ISSUE TITLE
Missing icons for 'Sort by' & 'Group by' with non-English system language

### ISSUE THREAD

**Issue by VladWinner** [moudey/Shell#28]
![image](https://user-images.githubusercontent.com/13555921/186283635-810708ea-8655-4963-9f38-e4cdf7c6b50f.png)
`Sort by` (English) → `Сортировка` (Russian)
`Group by` (English) → `Группировка` (Russian)

---

Another bug:
![image](https://user-images.githubusercontent.com/13555921/186284196-c181727b-5457-4daa-a829-33aebace7fbd.png)
Should be `Терминал Windows` (Russian) instead of `ms-resource:AppStoreName`
and `Командная строка` (Russian) instead of `Command Prompt`
![image](https://user-images.githubusercontent.com/13555921/186284658-d91cb2c4-5568-4bf2-8dc0-8852d8991c86.png)

---
Shell 1.7
Windows 11 22622.575

**Comment by VladWinner** [comment]
P.S. I can help translate menu items if you can't fully extract strings from the official localization.

**Comment by moudey** [comment]
Hi @VladWinner, 

Shell uses language resource files used to fetch the titles of menu items for comparison with the current item's title.
It is assumed that the identifiers are fixed with any language on both.
Please attach these files to solve this issue.

```
windows\ru-R\Uexplorer.exe.mui
windows\system32\ru-RU\shell32.dll.mui
windows\system32\ru-RU\ExplorerFrame.dll.mui
```

You can use `id.command_prompt.title` instead of typing it manually.  
More about identifiers [https://nilesoft.org/docs/functions/id](https://nilesoft.org/docs/functions/id)

**Comment by VladWinner** [comment]
[ru-ru mui.zip](https://github.com/moudey/Shell/files/9412137/ru-ru.mui.zip)

**Comment by moudey** [comment]
They were found

```
shell32.dll.mui/menu/215/28673  "Сор&тировка"
shell32.dll.mui/menu/215/28676  "&Группировка"
```

Please check other items.

**Comment by VladWinner** [comment]
Missing icon for 'Rename':
![image](https://user-images.githubusercontent.com/13555921/186408464-afb5871f-38af-404b-a8fe-bfb42d3decd4.png)
`"Rename"→shell32.dll.mui/menu/216/28690  "Пе&реименовать"`

Duplicated names and icons (should be 'Share' & 'Send to'):
![image](https://user-images.githubusercontent.com/13555921/186409163-5f95082d-a9cb-4946-a0c9-4735227d2e2e.png)
`"Share"→explorerframe.dll.mui/stringtable/3121/49930  "Поделиться"`
`"Send to"→"Отправить как"`

Translation for 'Windows Terminal':
![image](https://user-images.githubusercontent.com/13555921/186411139-b2589e32-0210-41f8-b54e-5b0ec0764d05.png)
`"Windows Terminal"→explorer.exe.mui/stringtable/1377/22016  "Терминал Windows"`

Other translations:
`"Copy Path"→shell32.dll.mui/stringtable/1896/30329  "Скопировать путь"`

---
Other (not found) strings:
```
Full Path→"Полный путь"
Short Path→"Короткий путь"
Parent→"Расположение файла"
Name→"Имя"
Title→"Заголовок"
Extension→"Расширение"
Folder→"Папка"
Folders→"Папки"
Power→"Питание"
Sleep→"Спящий режим"
Hibernate→"Гибернация"
Shut down→"Завершение работы"
Restart→"Перезагрузка"
Apps→"Программы"
Terminal→"Терминал"
`"Note\nHold Shift key to run Terminal as administator"→"Примечание\nУдерживайте Shift для запуска от имени администратора"`
```

**Comment by moudey** [comment]
These items have been fixed:

```
 "Rename"→shell32.dll.mui/menu/216/28690 "Пе&реименовать"
 "Send to"→"Отправить как"
```

These items already exist:

```
id.share_with.title
id.share
"Share"→explorerframe.dll.mui/stringtable/3121/49930 "Поделиться"

id.windows_terminal.title
 "Windows Terminal"→explorer.exe.mui/stringtable/1377/22016 "Терминал Windows"

id.copy_path.title
 "Copy Path"→shell32.dll.mui/stringtable/1896/30329 "Скопировать путь"
```

**Comment by moudey** [comment]
Please test this issue with [shell 1.8 beta](https://nilesoft.org/download)

**Comment by moudey** [comment]
'Folders', 'Apps', 'Toggle Attributes' are manual entries

```
line 316 item(title='Apps' vis=label col)
line 332 menu(title='Folder' image=\uE1F4)
```
'File Explorer Options' not defined. It will be added later

**Comment by VladWinner** [comment]
> Duplicated names and icons (should be 'Share' & 'Send to'):

![image](https://user-images.githubusercontent.com/13555921/192371673-faeb240e-93d7-4385-af60-41efbf1ee4f4.png)

**Comment by moudey** [comment]
I think the entries are correct:

```
"Se&nd to", "О&тправить"
shell32.dll/Menu/223/79

"Share", "Поделиться"
explorerframe.dll/StringTable/3121/49928
```

**Comment by VladWinner** [comment]
Maybe Windows 11 specific issue

**Comment by moudey** [comment]
Hi @VladWinner Please try this [bulld](https://github.com/moudey/Shell/files/10180947/shell-test.zip)

**Comment by VladWinner** [comment]
Hello @moudey!

> Duplicated names and icons (should be 'Share' & 'Send to'):

It's not fixed
![image](https://user-images.githubusercontent.com/13555921/207393347-0d90e2ae-64dd-4bde-8483-afb16c0017fb.png)

> 'Folders', 'Apps' are also not translated

I can't test it in this build
![image](https://user-images.githubusercontent.com/13555921/207393512-b7baac42-1dfe-4636-be80-43ab678a197c.png)


> Missing icon for 'Open' & 'Open in a new tab' (when select folder)

It's not fixed
![image](https://user-images.githubusercontent.com/13555921/207393620-968fcd27-30ee-4160-82b2-4988b3cff3b1.png)

> Missing icons for 'File Explorer Options' 

It's not fixed
![image](https://user-images.githubusercontent.com/13555921/207395213-78c6b473-bcb6-40bc-8332-1372d864af71.png)

There are also missing icons when select .exe file: "Open file location", "Troubleshoot compatibility", "Pin to Start"
![image](https://user-images.githubusercontent.com/13555921/207394215-76554cb6-6dbc-4f8d-8882-b4d10a785b39.png)

**Comment by moudey** [comment]
I think there is a system issue in the "Share" and "Send" items with the same title in the default menu in Russian.

![Shell](https://user-images.githubusercontent.com/39198/207504347-9d5e7ac8-7f43-443f-81b7-45c961a40ac2.png)
![Default](https://user-images.githubusercontent.com/39198/207504363-da89602b-af72-4aa3-8eb9-cd2fedae305b.png)

**Comment by moudey** [comment]
Hello @VladWinner Please try this buid [shell-test.zip](https://github.com/moudey/Shell/files/10228663/shell-test.zip)

![test](https://user-images.githubusercontent.com/39198/207622715-8138b9d6-4f37-4a7b-9dc8-d558babbbbcc.png)

**Comment by VladWinner** [comment]
@moudey This one breaks explorer.exe loading so I can't check further

**Comment by moudey** [comment]
Please attach  `shell.log` file

**Comment by VladWinner** [comment]
Nothing special
[shell.log](https://github.com/moudey/Shell/files/10228944/shell.log)

**Comment by moudey** [comment]
Are you using the attached config file?

Just try these settings. It is best to try it on Windows Sandbox

```
shell
{
	set
	{
		theme.name="modern"
		exclude.where = !process.is_explorer
	}
}
```

**Comment by VladWinner** [comment]
Alright, it works but the context menu called by right-click on the taskbar is no longer available. 
Maybe it has something to do with W11 beta itself.

**Comment by moudey** [comment]
Shell replaces Taskbar menu with a custom one

Add this code to dynamic section for Taskbar menu

```
menu(where=@(sys.is11 and this.count == 0) type='taskbar' image=icon.settings expanded=true)
{
   item(title=id.task_manager.title image=\uE159 cmd='taskmgr.exe')
   item(title=id.taskbar_Settings.title sep=both image=inherit cmd='ms-settings:taskbar')
   item(title=id.settings.title image=inherit cmd='ms-settings:')
}
```
