### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by ReubenDollmanYT** [moudey/Shell#29]
Hi is there any easy way to force icons onto certan things as some apps dont show a icon and others also dont show

**Comment by moudey** [comment]
Hi, Please attach a screenshot because the link is not allowed.

**Comment by ReubenDollmanYT** [comment]
<img width="178" alt="TqVhZjGzvn" src="https://user-images.githubusercontent.com/28374251/186558327-830a5144-820d-4686-af19-acaad02edcf5.png">
<img width="222" alt="7irdkvgs9j" src="https://user-images.githubusercontent.com/28374251/186558336-1fc5b331-cc8a-4aaa-bb22-8269cc16c64f.png">

**Comment by moudey** [comment]
Use this code to search the item's title:

```
shell
{
    static
    {
        item(find='"7-zip"' image=\uE1A4)

        item(find='unpin from start menu' image=[\uE0C7, #f0f])
    }
}
```
The issue of not displaying images for some programs was already fixed a day ago.

**Comment by M7MDE7EGAZY** [comment]
how to change context icon colors as accent colorizer doesn't work with it?

**Comment by moudey** [comment]
>@M7MDE7EGAZY 
>how to change context icon colors as accent colorizer doesn't work with it?
```
default
{
    theme
    {
        //glyph=[color1, color2]
        glyph=[color.invert(color.accent), color.accent]
    }
}
```

This option will be moved in the next update to `theme.image.glyph`

**Comment by M7MDE7EGAZY** [comment]
![image](https://user-images.githubusercontent.com/76889809/197285903-62512175-b74f-44cb-a1da-ef910182cb3e.png)
there is too much space in the left of the icon

**Comment by M7MDE7EGAZY** [comment]
also how to know exact font name as i tried everything but nothing is working

**Comment by M7MDE7EGAZY** [comment]
how to add icons to the items that doesn't have icons? like NVidia control panel

**Comment by moudey** [comment]
> there is too much space in the left of the icon
```
theme
{
    item
    {
        // Increase or decrease space
        padding.left=10
        padding.right=10

        margin.left=4
        margin.right=4

        // Change background color of selected item
        back.select=#ff0000
    }

    // Change font and size
    font
    {
        name="Segoe Script"
        size=16
    }
}
```

**Comment by moudey** [comment]
>how to add icons to the items that doesn't have icons? like NVidia control panel
```
static
{
    item(find='NVidia control panel' image=[\uE260, #0f0])
}
```

**Comment by M7MDE7EGAZY** [comment]
when changing font name i try everything but nothing is working how to know exact font name ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by moudey** [comment]
>@M7MDE7EGAZY 
>when changing font name i try everything but nothing is working how to know exact font name ?

اسهل طريقة لمعرفة اسماء الخطوط من خلال برنامج المفكرة. اضغط  edit ثم اختار font ستجد اسماء الخطوط في خاصية family

![font](https://user-images.githubusercontent.com/39198/197398118-7d2f9854-52af-4102-a234-5250a66d6f37.png)

**Comment by M7MDE7EGAZY** [comment]
![image](https://user-images.githubusercontent.com/76889809/197401791-59c73ced-f965-4038-8de5-c68399f337d1.png)
جربتها و خدت اسم الخط نسخ و لصق و زي ما موضح في الصوره انا 1.8 بيتا في طريقة اخلي الفونت ديناميك زي 1.7 كنت لما اغير menu font في winaero يتغير معاها ؟

**Comment by moudey** [comment]
@M7MDE7EGAZY 
جربت خط "Segoe Script" وعمل معي.
جرب استخدام "Segoe Script" واخبرني بالنتيجة

**Comment by M7MDE7EGAZY** [comment]
![image](https://user-images.githubusercontent.com/76889809/197404427-f2a2fdb4-7724-406c-b05b-45dc419ef715.png)

**Comment by moudey** [comment]
@M7MDE7EGAZY 
بعد عمل التغيرات قم بأعادة تحميل ملف الاعداد عن طريق الضغط على left-click + right-click  
او قم بعمل restart explorer من خلال نافذة Shell

**Comment by M7MDE7EGAZY** [comment]
بالفعل اقوم بذلك بعد كل تغيير

**Comment by moudey** [comment]
@M7MDE7EGAZY 
انسخ ملف الاعداد لحفظ الاعدادات السابقة ثم ادخل الكود التالي فقط 
قم بتغير الخطوط في كل محاولة
ثم جرب تغير الاعدادات ل Shell في ال Windows Sandbox

```
shell 
{
    default
    {
        theme
        {
            font.name="Segoe Script"
        }
    }
}
```

**Comment by M7MDE7EGAZY** [comment]
![image](https://user-images.githubusercontent.com/76889809/197414604-0df295cb-2fba-44c8-9809-8680605a5aa9.png)
![image](https://user-images.githubusercontent.com/76889809/197414634-6d5ac743-e19f-45ba-9ea2-f75cb5385d16.png)
طب ممكن نخليها ديناميك زي الاصدارات السابقة ؟

**Comment by moudey** [comment]
> طب ممكن نخليها ديناميك زي الاصدارات السابقة ؟

كل الخيارات ديناميكية

هل جربت تغير حجم الخط؟
```
font.size=20
```

**Comment by M7MDE7EGAZY** [comment]
![image](https://user-images.githubusercontent.com/76889809/197415416-a8a0716d-625c-4936-9090-267cde7e8f96.png)
تغير الخط كان يعمل بشكل اوتوماتيكي في الاصدارات السابقه

**Comment by moudey** [comment]
يبدو ان الخط تغير حجمة للتأكيد قم بتغير الحجم ل 30
لم تظهر لدي هذه المشكلة رغم تجربتها على ويندوز 11 و 10 و 7
جرب هذا اخر تحديث لم ينشر بعد [shell.zip](https://github.com/moudey/Shell/files/9847427/shell.zip)
قم الاول بعمل الغاء تسجيل من نافذة شل ثم انسخ الملف لمجلد شل ثم تسجيل

**Comment by M7MDE7EGAZY** [comment]
![image](https://user-images.githubusercontent.com/76889809/197416013-88ba95a0-3db4-4ab5-8a89-7a77ec0a55b9.png)

**Comment by M7MDE7EGAZY** [comment]
![image](https://user-images.githubusercontent.com/76889809/197416173-c318f7a9-7202-40b1-88bf-87af02b316b5.png)
و هذا اصدار 1.7

**Comment by moudey** [comment]
@M7MDE7EGAZY 
مرحبا محمد ارجوا تجربة هذه التعديل [shell.zip](https://github.com/moudey/Shell/files/9847616/shell.zip)

**Comment by moudey** [comment]
@M7MDE7EGAZY
اعتقد انه تم حل مسألة الخط؟

**Comment by M7MDE7EGAZY** [comment]
انا اعتذر جدا عن تاخري في الرد بسبب الجامعه ة عدم تواجد اللابتوب معي.
بالفعل تم حل المشكلة بنجاح

**Comment by moudey** [comment]
لا عليك اخي الكريم بالتوفيق ان شاء الله

**Comment by SuperSayf** [comment]
> ![image](https://user-images.githubusercontent.com/76889809/197401791-59c73ced-f965-4038-8de5-c68399f337d1.png) جربتها و خدت اسم الخط نسخ و لصق و زي ما موضح في الصوره انا 1.8 بيتا في طريقة اخلي الفونت ديناميك زي 1.7 كنت لما اغير menu font في winaero يتغير معاها ؟

Could you send me your config file please?

**Comment by M7MDE7EGAZY** [comment]
> > ![image](https://user-images.githubusercontent.com/76889809/197401791-59c73ced-f965-4038-8de5-c68399f337d1.png) جربتها و خدت اسم الخط نسخ و لصق و زي ما موضح في الصوره انا 1.8 بيتا في طريقة اخلي الفونت ديناميك زي 1.7 كنت لما اغير menu font في winaero يتغير معاها ؟
> 
> Could you send me your config file please?

https://kingsalman-my.sharepoint.com/:w:/g/personal/mohamed20020093_ksiu_edu_eg/EQu3gl0z4fxHgftYRAhZeikBL6wARElhHg_99T1cMCA4jQ?e=lBuBWG
