### ISSUE TITLE
Shift+F10 works inconsistently in Explorer of Windows 11

### ISSUE THREAD

**Issue by tukangusil7** [moudey/Shell#293]
After unregister the Shell extensions, Shift+10 works inconsistently in Explorer of Windows 11. Sometimes it works, sometimes it doesn't.

How to fix this problem?

**Comment by moudey** [comment]
When Shell is unregistered, all its operations will stop.
Can you try on Windows Sandbox?

**Comment by tukangusil7** [comment]
I've checked in VM by comparing before and after snapshots of the system, it seems NileSoft unregisters cleanly.

I found this information on the web:

https://blogs.windows.com/windows-insider/2023/06/01/announcing-windows-11-insider-preview-build-23471/

Search for the "Shift + F10" on that web page.

I think it was a bug that Microsoft still hasn't fully resolved.
