### ISSUE TITLE
Compatibility issue with Stardock Fences

### ISSUE THREAD

**Issue by RuiNtD** [moudey/Shell#294]
Using Shell with [Stardock Fences][fences] causes an incompatibility issue where none of Fences' menus work correctly, since they end up using Shell's menus.

https://github.com/moudey/Shell/assets/1149870/034e59cb-b335-4414-b31c-080ba33dcaf1

[Fences]: https://www.stardock.com/products/fences/

**Comment by moudey** [comment]
Please refer to this topic #198
