### ISSUE TITLE
New File context menu issue

### ISSUE THREAD

**Issue by wolive-20** [moudey/Shell#299]
Using version 1.8.1 I use the following static entry to remove all Google shortcuts from the New File context menu:
item(find='Google*' in='New' vis=remove)

Using beta version 1.8.35 results in the following error:
[error] line[16] column[33], Property unexpected "shell.nss"

line[16] column[33] is the beginning of the **in='New' vis=remove)** part of the line

It would appear that the **in** property is no longer recognized. When this line is removed, version 1.8.35 works without a problem. I've tried different options including those mentioned in [https://github.com/moudey/Shell/discussions/113] but without success. Could you advise how I may achieve the same result as implemented in version 1.8.1.

**Comment by moudey** [comment]
Correct values:
```
vis=”remove”
vis=vis.remove
vis=0
```

**Comment by wolive-20** [comment]
Thanks for your reply. I've tried all three recommendations, however, the problem still persists. Even when using the most simplistic shell.nss file, the error always stays the same and points to the row and column where the in property begins.
The contents of my shell.nss file is:
import 'imports/images.nss'
item(type='back' find='Google*' in='new' vis="remove")

The log file is attached.
[shell.log](https://github.com/moudey/Shell/files/12029134/shell.log)

**Comment by moudey** [comment]
1.8.1
```
static
{
    item(type='back' find='Google*' in='new' vis="remove")
}
```

build 35
In the update, the sections were dropped and the static section was replaced by changing the identifier `item` to `modify` and `remove`
```
modify(type='back' find='Google*' in='new' vis="remove")
//or
remove(type='back' find='Google*' in='new')
```

**Comment by wolive-20** [comment]
Thank you very much. Using the new **modify** identifier instead of **item** has resolved the problem.  Much appreciated.
