### ISSUE TITLE
Expanded not working on top level

### ISSUE THREAD

**Issue by BergenSoft** [moudey/Shell#302]
I'd like to group a bunch of items and place bellow an separator.
My idea to do that was to collect all items I want, place them in one submenu, set here the seperator property and expand the menu.
But when using expanded on a top level menu, than the sub-items weren't shown.

Example:
```
shell
{
    // var, set, ...

    dynamic
    {
        menu(mode="multiple" title="Group1" pos=pos.top expanded=true sep=sep.bottom) { }
    } 

    static
    {
        item(find="open|run|execute" menu="Group1")
    }
}
```

Without the ```expanded``` property the menu is shown with the sub items.
With the ```expanded``` property all items are hidden.

This seems to be a bug to me.

Or is there any other way to group some items within the main context menu and place separator arroud?
The problem I was facing is, that I never know which of the items is the last shown.

**Comment by moudey** [comment]
Static items modify only system items and do not modify dynamic items

**Comment by moudey** [comment]
When the `expanded` property is used, the menu is replaced by sub-items

**Comment by BergenSoft** [comment]
This is what I‘ve expected. The menu „Group1“ should be replaced by the sub-items. But this is not the case in this example.

**Comment by moudey** [comment]
The `expanded` property only works with new items
