### ISSUE TITLE
documentation lacking, needs an example of "moving" an existing option.

### ISSUE THREAD

**Issue by Ryder17z** [moudey/Shell#308]
I occasionally use Autodesk Inventor and I want to effectively "move" the inventor-specific entries to a submenu.

That software adds 5 entries to the context menu in explorer when you rightclick on a folder. As I personally never really use these, I want them to exist in a submenu to reduce the clutter.

This is just one example but it's easy to come up with more.
(and no, there is no option when installing this software to not have it throw in these context menu things)

**Comment by RubicBG** [comment]
In order to be able to help as much as possible, I need two things:
- the version of Nilesoft Shell so I can know what syntax can be used and what features are available
- screenshot of Autodesk Inventor commands - this will help me be clearer in the examples

**Comment by Ryder17z** [comment]
I recently downloaded it, says 1.8.1

![image](https://github.com/moudey/Shell/assets/2000703/93813a32-c511-4aa7-ae3e-6e0edb5543b9)

**Comment by RubicBG** [comment]
in imports\static.nss add:
`item(find='Design Assistant|Pack and Go|iProperties|Purge*' menu=title.more_options) `
this will move all of them to "More Options" menu

if you want to move them to a new menu, you must first create it in

```
static
{
item(find='Design Assistant|Pack and Go|iProperties|Purge*' menu='new menu name')
}

dynamic
{
// create empty menu - not visible when empty
menu(mode="multiple" title='new menu name') { }
}
```
pay attention to static/dynamic in the files you edit

**Comment by Ryder17z** [comment]
I tried the second approach and it has no effect. I've tried adding it within shell{ } or adding it below, but neither works

the first solution works but items in that submenu are not sorted 
(i don't know how i would put everything after a separator but that would work fine)

**Comment by RubicBG** [comment]
I don't use Autodesk. I'm using the latest beta version of Nilesoft Shell, which has a slightly different syntax, which makes me improvise when giving the code:

```
item(find='Design Assistant' sep=sep.after pos=pos.bottom menu=title.more_options) 
item(find='Pack and Go|iProperties|Purge*' pos=pos.bottom menu=title.more_options) 
```

**Comment by Ryder17z** [comment]
Appending the above to the shell.nss file on version 1.8.40  also has no effect unfortunately.

I don't know how the context menu is stored other than that it's somewhere in the windows registry, I'd be happy to include details but I can't find these items if I search for "Purge" or "iProperties" as a string.

**Comment by RubicBG** [comment]
version 1.8.1 and 1.8.40 have different syntax:

modify(find='Design Assistant' sep=sep.after pos=pos.bottom menu=title.more_options)
modify(find='Pack and Go|iProperties|Purge*' pos=pos.bottom menu=title.more_options)

Also, the commands don't need to be stored in the registry - they are most likely read from some .dll file
