### ISSUE TITLE
"Send to" in the main POPUP

### ISSUE THREAD

**Issue by H5820121** [moudey/Shell#309]
Thanks for the great app!
1. I use "send to" a lot, so I need it to be in the main POPUP, how can I set it up?
2. Is it possible to apply MICA to your POPUP?

**Comment by RubicBG** [comment]
1.  this will return the SendTo menu to the main menu:
in \imports\modifications.nss - for debug versions 
or in \imports\static.nss - for release version (1.8.1)
find 'id.send_to,' and delete it, and reload the app
2.  I don't understand exactly what you want to do. if you explain in detail I will try to help

**Comment by H5820121** [comment]
Thanks for the kind reply!
I mean, is there any option to apply WIN11 Mica Backdrop effect or Acrylic or Blur Backdrop effect to your popup?

**Comment by H5820121** [comment]
<img width="398" alt="image" src="https://github.com/moudey/Shell/assets/105562828/b2dd1c35-77da-4557-b365-076dab0ce9c2">
Can you please guide me which line numbers I should change, and what to change exactly?
Thanks!

**Comment by H5820121** [comment]
1. I managed , blur and mica, worked great!
2. How can I remove from popup the 'copy paste delete cut change name'?
For me it's just a placeholder since I use keyboard shortcuts anyway.

**Comment by RubicBG** [comment]
you van use  \imports\static.nss - for release version (1.8.1), and add
item(mode=mode.multiple where=this.id( id.cut, id.copy, id.paste) vis=vis.remove)

you van use \imports\cleanup.nss - for debug versions, ) and add
modify(mode=mode.multiple where=this.id( id.cut, id.copy, id.paste) vis=vis.remove)

https://nilesoft.org/docs/functions/id

**Comment by H5820121** [comment]
Thank you!
By the way, I wanted to try 3 = acrylic as well, but I didn't understand what type of value I should write in the definition "tint color"
<img width="258" alt="image" src="https://github.com/moudey/Shell/assets/105562828/f07312da-28d3-4d20-b671-85c90124e24f">

But as I already wrote, "4 = mica"  works great for me.

**Comment by RubicBG** [comment]
i'm curious: how did you set up the mica

**Comment by H5820121** [comment]
<img width="394" alt="image" src="https://github.com/moudey/Shell/assets/105562828/93a508f5-aece-4c2d-b8b6-437a6e0ae630">
<img width="295" alt="image" src="https://github.com/moudey/Shell/assets/105562828/2822c239-fb22-4085-a418-6ddb11231cb3">
<img width="266" alt="image" src="https://github.com/moudey/Shell/assets/105562828/3f8912bb-bbce-439e-bd99-d0a4d29c29cd">
<img width="282" alt="image" src="https://github.com/moudey/Shell/assets/105562828/97163b5e-6128-41a5-877f-da1addfe1a83">

What with the  definition "tint color"?

**Comment by RubicBG** [comment]
I have no idea what exactly is meant by "tint color" - only moudey can answer accurately, but by tint color is meant a primary color (like red, blue, green, orange, violet...) with an additive pure white - I understand it as a lightened color

**Comment by H5820121** [comment]
>only moudey can answer accurately
How do you contact someone who can answer?

**Comment by RubicBG** [comment]
I really liked your question. The answer is: right here! He is currently building the next version of his program - the new program will have many, many new improvements - I just don't know if they will all be released at once, including new graphics manipulation options. I am personally looking forward to the new version!!! Instead of dealing with answers to "small" questions, he works on the "big" idea and appears here and on Discird once every 7-10 days. It will appear eventually

https://discord.com/channels/1106387012707168318/1106387015425069151

**Comment by RubicBG** [comment]
I could not set acrylic. if I succeed I will write here:
https://discord.com/channels/1106387012707168318/1139275510506082336

**Comment by H5820121** [comment]
>I could not set acrylic

I couldn't do that either, I think that in such a great and useful application, it needs to be fixed, maybe to consult with the experts on this in this forum https://github.com/Maplespe/ExplorerBlurMica and https://github.com/ALTaleX531/TranslucentFlyouts, I think they will be happy to help, for the sake of the matter I think that you should do it.
Thanks for everything!

**Comment by H5820121** [comment]
> he gives better ones. But now, so that people don't wait, I give the experience that I have

Your answers helped me a lot, and I'm sure others too!
And I really appreciate what you volunteer your time just to help others.
