### ISSUE TITLE
Help me to make these modifications 

### ISSUE THREAD

**Issue by Marvinoo** [moudey/Shell#316]
As title says, I'm just asking for some help to make the following modifications: 
1. Make the menus radius zero round/squared globally in all the menus (?)
~~2. How to change the font size and variant globally in all the menus also?~~
Thanks in advance.

**Comment by RubicBG** [comment]
I can try to help, but first I need to know which version you are using

**Comment by Marvinoo** [comment]
Latest

**Comment by RubicBG** [comment]
(I need to be more specific in my questions :) )
which version: the latest release version 1.8.1., or the latest debug version 1.8.40?

**Comment by Marvinoo** [comment]
> (I need to be more specific in my questions :) ) which version: the latest release version 1.8.1., or the latest debug version 1.8.40?

debug 1.8.40 with Theme Manager installed

**Comment by RubicBG** [comment]
if there is a Theme Manager it would be easy:
Font > size > value
Border > radius > value
Note that the change affects only those context menus that Nilesoft Shell App controls (via Windows ContextMenuHandlers). With some 3rd party apps this is not possible (at least for now)

If the answer is not this one, please explain in more detail with a specific situation and/or provide a screenshot

**Comment by Marvinoo** [comment]
![image](https://github.com/moudey/Shell/assets/45720537/6072ba3f-b52a-4d37-a8ba-e8791d94d4b9)
So the radius value is set to zero but as seen in the pic the borders are still roundy. 

> if there is a Theme Manager it would be easy: Font > size > value Border > radius > value Note that the change affects only those context menus that Nilesoft Shell App controls (via Windows ContextMenuHandlers). With some 3rd party apps this is not possible (at least for now)
> 
> If the answer is not this one, please explain in more detail with a specific situation and/or provide a screenshot

**Comment by RubicBG** [comment]
[theme-manager.mod.zip](https://github.com/moudey/Shell/files/12408807/theme-manager.mod.zip)
I added for radius options from 0 to 4, try with 0, and write back

**Comment by Marvinoo** [comment]
WORKED PERFECTLY! Thank You.

> [theme-manager.mod.zip](https://github.com/moudey/Shell/files/12408807/theme-manager.mod.zip) I added for radius options from 0 to 4, try with 0, and write back
