### ISSUE TITLE
Feature request : add opetion to change the title style case.

### ISSUE THREAD

**Issue by Marvinoo** [moudey/Shell#317]
An option to allow changing the style of title case while renaming items would be very useful.

**Comment by RubicBG** [comment]
If I understand you correctly, this is already there - see here: [If I understand you correctly, this is already there - see here: 

i```
tem
{
back
{
normal = color
select = color
normal_disabled = color
select_disabled = color
}
}
```

please confirm](https://nilesoft.org/docs/syntax/set)
item
{
back
{
normal = color
select = color
normal_disabled = color
select_disabled = color
}
}

please confirm

**Comment by Marvinoo** [comment]
No. I mean..
For example:
I've a new folder on desktop or anywhere.. and it's name is 'good music'
Now I need and option to appear on the right context menu that appear when I right click onthe folder , to allow changing the name case ..
Like upper case so it will become: 'GOOD MUSIC'
Title case so it will become: 'Good Music
Sentence case: 'Good music'
Random case : 'GoOd mUsIC'


Basically the option will have cascading menu that will have all these different cases to apply on any folder name or file name

**Comment by RubicBG** [comment]
I had started something similar but left it. I will try to finish it soon. You can wait when I'm done with the code, or we can comment it on discord:
https://discord.com/channels/1106387012707168318/

**Comment by Marvinoo** [comment]
> I had started something similar but left it. I will try to finish it soon. You can wait when I'm done with the code, or we can comment it on discord:
> https://discord.com/channels/1106387012707168318/

It's really good to know that there's something about this. I hope you finish that but I'm sorry I won't be able to use discord because I'm always in a work environment and not all the websites are accessable. I just thought to ask for this feature because in my work I do lot of organizational work on a computer so I do lot of file operations like the renaming and so on... May be I'll wait for the full code to be implemented in a future release. Thanks.

**Comment by moudey** [comment]
```
modify(find='good music' title=str.capitalize(this.title))
```

**Comment by Marvinoo** [comment]
So when we right -click on a file to rename it, can you please add option under 'attributes' and call it 'Change case'. And when we hover on this option it will show a sub-menu with these functions :
UPPERCASE
lowercase
Sentence case : First char in uppercase, rest in lowercase
Capitalize every word : First Char Of Every Word In Uppercase 
Random Case : cONveRT all naME'S LETTErS to it's LOwerCaSe or UpPERCAse EQuIVaLEnt wiTh RaNdom CASE sELECtION mEthOD.
![image](https://github.com/moudey/Shell/assets/45720537/7426488b-07c7-4f3f-b95c-49deab69afdd)

**Comment by RubicBG** [comment]
![image](https://github.com/moudey/Shell/assets/127151533/dd9fda4d-79ee-4fd9-b4ab-1912c977c4f7)
I'm working on this idea - some things are already working, others are working at 70% (I have to foresee a lot of exceptions), others I haven't started yet
