### ISSUE TITLE
[Question] The original "Properties" icon

### ISSUE THREAD

**Issue by AndresF2016** [moudey/Shell#318]
Hi, i want to restore the original "properties" icon, i miss the old one, and for me is more understandable the link of "Properties" with that icon than the current "wrench" icon...

Just a question, is there a way to restore or change the "Properties" Icon? For example, is a possible to change the "Properties" icon from "images.nss" file?

![example](https://github.com/moudey/Shell/assets/112676001/b153ca30-d280-4e0f-92f3-236e1d848da4)
![Captura de pantalla 2023-08-22 000200](https://github.com/moudey/Shell/assets/112676001/1dbf92f3-1752-4d0d-b83a-7471d502aa96)

**Comment by RubicBG** [comment]
this will replace the icon (ver > 1.8.1)
`modify(find='"properties"' image=\uE0F8)`

**Comment by OsakaRider** [comment]
add this under static in the Shell.nss worked for me.

`                item(where=this.id==id.properties image=\uE0C5)`
