### ISSUE TITLE
Item doublets 

### ISSUE THREAD

**Issue by mortensp** [moudey/Shell#320]
I have two issues:

1. How to avoid a given title to occcur more than once.
2. How to hide disabled items

Here is two screenshots - with and without Nelisoft Shell registred - and you se the problems with Notepat++.
Its in danish - sorry:

![image](https://github.com/moudey/Shell/assets/2102113/d19dec7c-df8b-4d46-93c7-fc1094a420ff)

![image](https://github.com/moudey/Shell/assets/2102113/4071f2dc-8afd-4f36-8103-36e98b6ac2fd)

**Comment by RubicBG** [comment]
1. Removing duplicate commands is not possible - it will be done later. For more information see:
https://discord.com/channels/1106387012707168318/1106390602964283483/threads/1142536977510567956
https://github.com/moudey/Shell/issues/300

about notepad++ see here:
https://discord.com/channels/1106387012707168318/1142556557075284130

2. hide disabled items:
```item(type='*' where=this.disabled vis=remove)```
