### ISSUE TITLE
Right clicking apps on the right third of taskbar makes shell open while it should only open the app's menu

### ISSUE THREAD

**Issue by aaronliu0130** [moudey/Shell#321]
![image](https://github.com/moudey/Shell/assets/11874211/a58052cf-6b8c-4e2c-944c-d86497278fa1)
This is the result of simply right clicking. The hover preview is uninteractable.
Windows 11 22H2 Shell 1.8.1 with Rectify11's config

**Comment by Peeveck** [comment]
![2023-09-03 201815](https://github.com/moudey/Shell/assets/118300943/00fbb4d3-3a58-4b85-a922-2beab9bd8d37)
Same thing here. Windows 11 23H2 Shell 1.8.1

**Comment by moudey** [comment]
This issue has been fixed and will be available in the next update

**Comment by aaronliu0130** [comment]
@moudey Still happens in 1.9
