### ISSUE TITLE
Extra space under 'Properties' if I right-click anything that's not a folder.

### ISSUE THREAD

**Issue by medovanx** [moudey/Shell#322]
There's an extra space under 'Properties' if I right-click anything that's not a folder.
This only happened after installing Shell.

Windows 11 Pro 22H2 Build 22621.2215
[Shell version 1.8.1](https://nilesoft.org/download/shell/1.8/setup.exe)

Here's a video for demonstration.

https://github.com/moudey/Shell/assets/29468096/e4524b1b-2186-4345-a216-bb7b08a477c5

**Comment by medovanx** [comment]
I have to add this line inside the `static` block of `shell.nss` to fix the issue.
`shell.nss` located at `"C:\Program Files\Nilesoft Shell\shell.nss"`

`item(type='file' where=this.disabled find='Edit with Notepad++' vis="remove")`

Then unregister shell via `"C:\Program Files\Nilesoft Shell\shell.exe"` and register it again.
That shall solve the issue.

But I believe that a fix shall be added to the compiled build by default for new people!

**Comment by moudey** [comment]
مرحبا @medovanx 
تم اصلاح هذه المسألة وهى متاحة في نسخة [التصحيح](http://nilesof.org/downloa/shell/debug.zip)

ويفضل إلغاء تسجيل امتداد NPP واضافته من خلال Shell

**Comment by medovanx** [comment]
> 

There's a misspelling in the link you provided, it isn't working, and I believe you should Include it in the installer available through the main page, most people download from there! 
Just my thoughts! And thank you for this awesome software.

**Comment by RubicBG** [comment]
https://github.com/moudey/Shell/discussions/305
