### ISSUE TITLE
Right click menu doesn't work with Stardock Fences program.

### ISSUE THREAD

**Issue by medovanx** [moudey/Shell#323]
Whenever I try to change the setting of `Lock Fences` or to open `Configure Fences` it has no effect at all.
**Note**: Fences is a program to organize icons on the desktop into collapsible folders or groups.

**Details**

- Windows 11 Pro 22H2 Build 22621.2215
- [Shell v1.8.1](https://nilesoft.org/download/shell/1.8/setup.exe)
- [Fences v4.21](https://www.stardock.com/products/fences/#purchase)

It works fine if I unregister Shell.

https://github.com/moudey/Shell/assets/29468096/bcebd129-729a-4a06-891f-44fdd37fe750

**Comment by moudey** [comment]
Please refer to this topic #294 #198
