### ISSUE TITLE
"Checked symbol" on Beyond compare context menu

### ISSUE THREAD

**Issue by Mark-Joy** [moudey/Shell#33]
Hello,
Thank you for the great app!!

I have an issue with "checked symbol" on Beyond compare context menu
The original does not have one.
It makes the left size of my menu unbalance.

![Shell0](https://user-images.githubusercontent.com/22109528/190815657-94ea91da-e145-4207-a103-5aedb30f0812.png) ![Shell](https://user-images.githubusercontent.com/22109528/190815744-f038489a-7473-4aa5-aafe-6ccb76491f7c.png)

Please let me know if I can fix this?

I found the taskbar's context menu is a  bit unbalance too.
![Shell1](https://user-images.githubusercontent.com/22109528/190818444-f0ff536b-1f78-42fe-8ab1-59fd9be20306.png)

Suggest to move the "checked symbol" to its icon's position when the item does not have it own icon.

**Comment by moudey** [comment]
A new option "theme-layout-align" has already been added to enable or disable this option.

**Comment by Mark-Joy** [comment]
> A new option "image-align" has already been added to enable or disable this option.

It's good to know that the issue was dealt with. I am new to Shell, can I know how to use this option?

**Comment by moudey** [comment]
This option and more layout options have been added in the next update
