### ISSUE TITLE
Goto - Documentation of how to GoTo a specific folder

### ISSUE THREAD

**Issue by SandeeepKiran** [moudey/Shell#331]
Goto - Documentation of how to GoTo a specific folder

Quite often we need to open a specific folder.
say mine is called "01_Conversations" and another called "Template"

"C:\Users\UserName\Desktop\01_Conversation"
and another
C:\Users\UserName\Desktop\WORK\My Team - Project - UserName's Files\02 - My Emails - Folder\My Project Setups\My Setup Template - UserName_edits.docx

Now,
I tried.
item(title='Conversations' image=inherit cmd=user.desktop.01_Conversations)
item(title='Conversations' image=inherit cmd=user.desktop.'C:\Users\UserName\Desktop\WORK\My Team - Project - UserName's Files\02 - My Emails - Folder\My Project Setups\My Setup Template - UserName_edits.docx')

and

item(title='Conversations' image=inherit cmd=C:\Users\UserName\Desktop\WORK\My Team - Project - UserName's Files\02 - My Emails - Folder\My Project Setups\My Setup Template - UserName_edits.docx)

item(title='Conversations' image=inherit cmd='C:\Users\UserName\Desktop\WORK\My Team - Project - UserName's Files\02 - My Emails - Folder\My Project Setups\My Setup Template - UserName_edits.docx')

No matter what, I could not get this to work as intended.
I tried searching the Documentations, but to not much avail

**Comment by kaser2010** [comment]
try this in goto file
`item(title='Name' image=\uE1F4 cmd='folder path')`
Just edit Name and folder path

**Comment by RubicBG** [comment]
cmd='folder path' only works for paths, if you want to open a file (because it sees '.docx') use:
cmd='app path' args='file path'

`item(title='Open Text document' cmd='notepad.exe' args='C:\test.txt')`
