### ISSUE TITLE
[Bug] Right clicking on taskbar items opens shell's context menu

### ISSUE THREAD

**Issue by pota2dev** [moudey/Shell#333]
**Sometimes, right-clicking on a taskbar item (not in empty space on taskbar), open's shell's taskbar context menu instead of the program's original context menu.** 

Example:
<img src="https://github.com/moudey/Shell/assets/36124755/66985b9a-e50b-4146-b511-8e77d7c61d58" width="30%" height="30%">

**Windows Version: 22H2 (Build 22621.2359)**
**App Version: 1.8.1**

**Comment by RubicBG** [comment]
which version of NS are you using?

**Comment by pota2dev** [comment]
> which version of NS are you using?

Version: 1.8.1

**Comment by pklion** [comment]
I have same problem. It always happens when I click on taskbar apps with its window(s) all minimized.

NS version: 1.8.1
winver: 23H2(22631.2338)

**Comment by pklion** [comment]
Oh maybe this is the same problem with #321

**Comment by RubicBG** [comment]
yes it is - on discord (https://discord.com/channels/1106387012707168318/) there are debug versions without this problem
