### ISSUE TITLE
[Bug] Menu opened from taskbar can be immediately closed

### ISSUE THREAD

**Issue by Chupakabra0** [moudey/Shell#334]
## Description
When you open context menu at taskbar and trying to get access to menu items, your menu can completly close. Next time it will work fine, as it has to be.

## How to reproduce?

https://github.com/moudey/Shell/assets/47476146/30a2b89f-643f-4bbf-8e21-ccef5e82fd64

**Explanation**: mouse left-clicking highlighted in yellow and right-clicking in blue. Desktop refreshing returns back the bug.

## Details:
- Windows 11 Pro 22H2 Build 22621.2283
- Nilesoft 1.8.1

I've also attached my menu-item files 'cause it might be my fault, or they could be useful for bug research (changed .nss file extension to .txt). As for me, there is nothing complex in them.

[browser.txt](https://github.com/moudey/Shell/files/12694082/browser.txt)
[develop.txt](https://github.com/moudey/Shell/files/12694079/develop.txt)
[games.txt](https://github.com/moudey/Shell/files/12694080/games.txt)
[life.txt](https://github.com/moudey/Shell/files/12694081/life.txt)

**Comment by RubicBG** [comment]
the problem has also appeared with other users - with two programs that try to change the Windows Shell at the same time

find which program does it and write back

**Comment by Chupakabra0** [comment]
I've completly forgotten about. Yes, I am using Start 11 (latest 1.47 Steam-version).

**Comment by RubicBG** [comment]
I don't remember if this problem was left to be solved after the next release version (the new version is built from the ground up and this problem may not exist then) or if it was fixed in one of the debug versions (https://discord.com/channels/ 1106387012707168318/1106387015425069151/1154640833396621413)

**Comment by Chupakabra0** [comment]
Ok, I'll check it out and let you know, if this bug is gone.

**Comment by Chupakabra0** [comment]
I tried the latest 47 debug-build and got "Register not complete error"

**Log**:
Nilesoft Shell
version 1.8.47 64-bit
support@nilesoft.org
https://nilesoft.org

Windows 11 Pro 64-bit, version 10.0.22621.2283
--------------------------------------------------------------------------------

2023-09-23 15:33:07 [error] Register not completed.

**Comment by RubicBG** [comment]
https://discord.com/channels/1106387012707168318/1106387015425069151/1154640833396621413

**Comment by Chupakabra0** [comment]
Oops, sorry 😅
After short adaptation of my files to new .nss syntax changes, that you had made, I tested it and bug still appeared in the same scenarios.
