### ISSUE TITLE
Image Index Not Working

### ISSUE THREAD

**Issue by bcrotty** [moudey/Shell#336]
I'm trying to put a certain Dropbox icon on a menu. I've tried both of the following, but the image is always the main program icon, not one of the other ones in the executable. Is there a different way I should do this?

- `image=image('C:\Program Files (x86)\Dropbox\Client\Dropbox.exe', 20)`
- `image=image.res('C:\Program Files (x86)\Dropbox\Client\Dropbox.exe', 20)`

![image](https://github.com/moudey/Shell/assets/6155964/a33fbd1e-e3f9-4fb1-ba4a-eae8a5e3dbc9)

**Comment by moudey** [comment]
Are you using the debug version?

**Comment by bcrotty** [comment]
I'm using 1.8.1 from winget.

**Comment by moudey** [comment]
please update to 1.9 and test it

**Comment by bcrotty** [comment]
Still not working on 1.9. Here's my code:

```
modify(find='View in Dropbox' menu='Dropbox')
modify(find='Copy Dropbox link' menu='Dropbox')
modify(find='Version history' menu='Dropbox')
menu(title='Dropbox' image=image('C:\Program Files (x86)\Dropbox\Client\Dropbox.exe', 21)) {}
```

Everything works except it still just uses the main icon instead of the indexed one.

**Comment by moudey** [comment]
Try this until it fixes
```
menu(title='Dropbox' image='C:\Program Files (x86)\Dropbox\Client\Dropbox.exe,2')) {}
```

**Comment by bcrotty** [comment]
That worked with a small typo fixed:

`menu(title='Dropbox' image=image('C:\Program Files (x86)\Dropbox\Client\Dropbox.exe,2')) {}`

Thanks!
