### ISSUE TITLE
'Edit with Notepad++' now greyed out after update to 1.9.0.

### ISSUE THREAD

**Issue by mike6041** [moudey/Shell#338]
'Edit with Notepad++' now greyed out after update to 1.9.0.
Appears to be all text file types (.txt, .ini, .cfg, etc.)
Reverting to 1.8.1 resolves the issue.
Completely stock config with no changes.

![Screenshot 2023-09-30 193350](https://github.com/moudey/Shell/assets/115667510/bd28ff78-a3e0-4ef2-88ed-6ba84f76711b)

**Comment by krystofkrticka** [comment]
I also have this issue and it's extremely annoying and frustrating because notepad++ is my editor of choice for config files.

**Comment by moudey** [comment]
This command will enable Notepad++ item.
```
modify(find="Edit with Notepad++" vis=1)
```

Or unregister "NppShell.dll"and create a custom item using this example:
```
item(title="Edit with Notepad++" admin=key.lbutton() image cmd='path\to\Notepad++' args='@sel.path')
```

**Comment by mike6041** [comment]
That's fixed it, thanks!

**Comment by pa-0** [comment]
sorry to revive a closed issue, but rather than enable an additional menu item, is it possible to set which app the "Edit" command calls?  Currently, it runs MS Notepad, even when default app is different.

**Comment by pa-0** [comment]
Referring to this item: 
![image](https://github.com/user-attachments/assets/b0668fae-7a35-402f-b2ac-def37da69a1c)

**Comment by RubicBG** [comment]
Changing an item's command is not possible with NS; the only option is to edit the registry, but you can create a "duplicate" item with NS and replace the original one.

**Comment by pa-0** [comment]
Should I just go through the .nss files and find the code for the original and edit it, or is there a better way to replace it?

**Comment by RubicBG** [comment]
i need to add 2 lines of code to a nss file 
- one to create new item:
```js
item(title='Edit 1' type='file' find='.txt|.log|.reg|.nss' pos=1 image cmd='notepad' args=sel(true)) // works for certain extensions
```
or
```js
item(title='Edit 2' type='file' where=io.meta(sel, 'System.ItemType')=='Text Document' pos=1 image=image.glyph(\uE0A1) cmd='notepad' args=sel(true)) // works for all windows text types
```
and replace `notepad` with the path of the program that you want to use (if the new app have "complex" commands for passing the file you need to change `args` as well)
the other changes like `title`, `pos`, `image`, conditions are optional

- second is to remove the system one 
```js
remove(find='"Edit"' where=this.sys) // removes it
```
or
```js
remove(find='"Edit"' where=this.sys and !keys.shift()) // hide it - shows with shift key if needed
```
or 
```js
remove(where=this.sys and str.replace(this.title, '&', '')=='Edit' and str.contains('.txt|.log|.reg|.nss|', sel.file.ext +'|'))  // removes it only for certain extensions
```

**Comment by pa-0** [comment]
Thank you!
