### ISSUE TITLE
Support FreeCommander?

### ISSUE THREAD

**Issue by Mark-Joy** [moudey/Shell#34]
Is it possible to make this app work in FreeCommander?

**Comment by moudey** [comment]
This will be supported in the future but currently the focus is on supporting and improving Windows File Explorer context menus

**Comment by moudey** [comment]
Please test this [build](https://github.com/moudey/Shell/files/10127710/shell-test.zip) 

Comment this line to enable shell with FreeCommander
```
exclude.where = !process.is_explorer
```

**Comment by ThePython10110** [comment]
Works great for me (Windows 10, Tablacus Explorer).
