### ISSUE TITLE
Pin/Unpin from Quick Access missing

### ISSUE THREAD

**Issue by HammerOfDaGods** [moudey/Shell#341]
I have made registry edits to add some custom menu options for myself, but nothing affecting Quick Access, and it works properly in the default Windows menu, but not in the Nilesoft Shell menu.

Original Windows menu
![image](https://github.com/moudey/Shell/assets/94164260/6816e848-e7cc-4c87-abb2-e6970e8d74a7)
Nilesoft Shell menu
![image](https://github.com/moudey/Shell/assets/94164260/663bc988-b4ef-42ca-bbee-69c66d7b2737)
(It is also not in any of the sub-menus)

**Comment by moudey** [comment]
Open "imports/modify.nss" file, replace "Pin//Unpin" with "Pin/Unpin".

Save changes, Restart explorer.

**Comment by HammerOfDaGods** [comment]
> Open "imports/modify.nss" file, replace "Pin//Unpin" with "Pin/Unpin".
> 
> Save changes, Restart explorer.

Ty! Fixed it immediately. Is there a place this is documented so I can avoid posting a bug in the future? I looked a bit, on the nilesoft.org/docs for example, but didn't find anything. I'm happy to dig and fix stuff myself without bothering dev's, I just need a place to dig.

**Comment by moudey** [comment]
> Also this worked in the past without any modification required. Did something change in an update?

Yes, there were some changes, and we forgot to modify some items to be compatible with the latest updates.

**Comment by Xarishark** [comment]
Can you please push the update to fix this problem because I have clients using the app because the love it and they freaked out when they saw they have no way to unpin something while they use it. (you can still drag to pin)
