### ISSUE TITLE
"Edit with Notepad++" option is greyed out

### ISSUE THREAD

**Issue by Flax4** [moudey/Shell#347]
When using this Shell under Windows 10 (works under Windows 11), my option to open a file with notepad++ is greyed out and can't be clicked, with default context menu it works just fine. Is this an issue with this shell or is it a issue on Notepad++ side? I guess this issue is more of a curious question more so then a problem for me.

Shell:
![image](https://github.com/moudey/Shell/assets/50862920/307f7a06-0174-441c-9ba7-205e485f79b5)

Default:
![image](https://github.com/moudey/Shell/assets/50862920/dbe230d8-7a2f-49cd-b713-89712a0147d8)

**Comment by Flax4** [comment]
> try: `modify(find='Notepad' vis='true')` 

This fixed it, thank you!

**Comment by nohart** [comment]
> try: `modify(find='Notepad' vis='true')` or remove it and create new one: https://discord.com/channels/1106387012707168318/1142556557075284130/1142556557075284130

What file do you put the code in?

**Comment by RubicBG** [comment]
copy the code at the end in \imports\modify.nss file - save and reload the app with ctrl right click

**Comment by nohart** [comment]
Nice! That worked. Thank you

**Comment by DuckMan128** [comment]
First thought which came to my mind was: Are the NP++ against Palestinians sovereignty?
