### ISSUE TITLE
Mica Effect Not Working

### ISSUE THREAD

**Issue by Name12312** [moudey/Shell#348]
mica effect is not working in latest 1.9 update

**Comment by RubicBG** [comment]
I tested and it works for me. send me the code file for Mica Effect

**Comment by moudey** [comment]
Add this code at the bottom of 'shell.nss' file
```
theme
{
	name="modern"
	dark=auto
	background
	{
		color=auto
		opacity=0
		effect=3
	}
}
```
Save changes, press <kbd>CTRL</kbd> + <kbd>RIGHT-CLICK</kbd> to reload settings.

For more please watch this video https://www.youtube.com/watch?v=sjHPWLCLqyw
