### ISSUE TITLE
Variable -  when to use @

### ISSUE THREAD

**Issue by Mark-Joy** [moudey/Shell#36]
Looking at here: https://nilesoft.org/docs/syntax/variables and inside shell.shl
I dont know when I should use @

**Comment by moudey** [comment]
It is used specifically in single quotes to denote it as an syntax expression
```
var {
    message='Windows type @sys.type' // result: Windows type 64
}
```
more about [string expression](https://nilesoft.org/docs/expressions/string)

**Comment by Mark-Joy** [comment]
Thank you!! I understand now
