### ISSUE TITLE
Shell not applying to default desktop context menu

### ISSUE THREAD

**Issue by kianagit** [moudey/Shell#361]
So, ive seen a few issues here with this specific problem, one of them suggesting to run `shell.exe -r -treat` and one that says to just... reinstall it... But none of these seem to work

The Desktop will show the default windows11 context menu (with "show more options") when clicked normally. When shift-clicked (aka opening "show more options" just in quick) it shows the shell menu.

I suppose this is due to some new windows update, because i am pretty sure it worked before.

**Comment by Qynklee** [comment]
Windows 11 just update to 22621.2506, it has more new changes with new Windows Explorer. I think nileshell need time to create update for this.
https://support.microsoft.com/help/5031455

**Comment by cmdshft** [comment]
I am having this same issue now. However, I did notice that it was working fine earlier today, now I cannot seem to get it running like I am used to. Was working fine on 2H23, but somehow no longer. I did get it to work again but then after restarting it seemed to revert back to the way you are experiencing. Cannot seem to find how I got it to work again.

**Comment by RubicBG** [comment]
A user with a similar problem, where `shell.exe -r -treat` did not work, I advised him to make Windows not use the modern context menu by changing the registry - this way, the NS more easily takes control of the Shell components. Try this: https://www.sordum.org/14479/windows-11-classic-context-menu-v1-2/  (this app only changes the registry without having to understand much)
