### ISSUE TITLE
No "pin to start" in the right click menu

### ISSUE THREAD

**Issue by ThiccNippls** [moudey/Shell#363]
I've been trying to locate the pin to start in the right click menu but there seems to be none
![Screenshot 2023-10-29 054545](https://github.com/moudey/Shell/assets/105832318/d5f07f6a-8137-491c-8888-afde7b0df2e5)

**Comment by RubicBG** [comment]
send me the file: ...\imports\modify.nss

**Comment by ThiccNippls** [comment]
[modify.zip](https://github.com/moudey/Shell/files/13220848/modify.zip)

**Comment by ThiccNippls** [comment]
> send me the file: ...\imports\modify.nss

[modify.zip](https://github.com/moudey/Shell/files/13220871/modify.zip)

**Comment by RubicBG** [comment]
https://github.com/moudey/Shell/issues/341#issuecomment-1747754752
or delete this:
```JS
modify(find="unpin" pos="bottom" menu="Pin//Unpin")
modify(find="pin" pos="top" menu="Pin//Unpin")
```

**Comment by ThiccNippls** [comment]
done, nothing happened
![Screenshot 2023-11-02 043848](https://github.com/moudey/Shell/assets/105832318/0ad3ab00-0803-472f-84c2-532cb74f8276)
