### ISSUE TITLE
Default modify.nss has a typo for "Pin/Unpin" menu

### ISSUE THREAD

**Issue by ozGarius** [moudey/Shell#365]
I couln't find the manu to pin things to the taskbar or to remove folders from "quick access"

looks like in modify.nss there's a typo:
```
modify(find="unpin" pos="bottom" menu="Pin//Unpin")
modify(find="pin" pos="top" menu="Pin//Unpin")
```

Changing it to:
```
modify(find="unpin" pos="bottom" menu="Pin/Unpin")
modify(find="pin" pos="top" menu="Pin/Unpin")
```
fixed the issue

**Comment by RubicBG** [comment]
https://github.com/moudey/Shell/issues/341

https://nilesoft.org/download#canary
