### ISSUE TITLE
When explorer.exe is launched with arguments, Shell will prevent it from exiting normally

### ISSUE THREAD

**Issue by infernoboy** [moudey/Shell#37]
Launching explorer.exe with arguments (e.g. `explorer.exe /select,C:\Windows`) will prevent it from being exited when closing the window that spawns. This appears to be due to Shell. CPU usage is a constant 12% for me and I have to manually exit the extra processes.

The menu itself does work, though.

Edit: Each time explorer is spawned with arguments, a new processes consuming ~12% CPU will remain active. Normally, the process uses 0% CPU once the window is closed and exits after ~1 minute.

![Screenshot (1)](https://user-images.githubusercontent.com/25857/190884229-f414963f-40e2-4f75-81ae-14fc3ecd00c4.png)

**Comment by moudey** [comment]
This issue has already been fixed in the next update

**Comment by moudey** [comment]
Please test this issue with [shell 1.8 beta](https://nilesoft.org/download)

**Comment by moudey** [comment]
Hi @infernoboy, Is this issue still persisting in version 1.8 beta

**Comment by infernoboy** [comment]
CPU usage issue is resolved. Still not closing, but that seems to be something else now. Thank you.

**Comment by moudey** [comment]
I have done the following experiments:
- I opened folder in a new process separately. The process was terminated ~1 minute after the window was closed.
- I opened folder with `explorer.exe  select,C:\Windows`. The process was terminated ~1 minute after the window was closed.
- I repeated the commands, but with some of them and ended in the same previous cases.

Can you try it in Windows Sandbox

**Comment by infernoboy** [comment]
It does seem to be working as expected now and explorer.exe is closing.

**Comment by juicetoon** [comment]
I seem to be getting a similar issue again - 1.8.1.

Restarting explorer fixes it.
