### ISSUE TITLE
[General Question] How do i change the glyph size?

### ISSUE THREAD

**Issue by AndresF2016** [moudey/Shell#375]
General question, is there a way to change the size of the glyphs (icons)? Since the 1.9 version, the glyphs looked a bit small than usual, i was checking on the documents about customize the context menu and there's a line where it says "Scale" on "Image" group line..![image](https://github.com/moudey/Shell/assets/112676001/7b0dbf4f-47ea-4f82-b244-dddd79008bc8)

I tried to change the size of the glyphs and nothing changed, my question again is, is there really a way to change the glyphs size and make it more bigger? Here's an example what i mean, the Windows 11 native context menu have the glyphs a bit more bigger than the Shell 1.9.10, and i want to replicate the size of the glyphs...
![example](https://github.com/moudey/Shell/assets/112676001/a4a7cfae-8d64-4664-aa93-6c8a6b4a0a00)

**Comment by RubicBG** [comment]
try with 
```
font
	{
		size = 17
	}
```
