### ISSUE TITLE
recycle bin disabling bug....

### ISSUE THREAD

**Issue by VenusGirl** [moudey/Shell#376]
After installing SHELL 1.9.10, there is a bug where the recycle bin is greyed out and not working.

Even after uninstallation, the recycle bin is not restored.

![이미지 00x](https://github.com/moudey/Shell/assets/53147200/aadcf12e-0862-4857-b493-90c1e744b299)

**Comment by RubicBG** [comment]
https://github.com/moudey/Shell/issues/368

**Comment by VenusGirl** [comment]
// modify(type="recyclebin" where=window.is_desktop and this.id==id.empty_recycle_bin pos=1 sep vis=true)
modify(type="recyclebin" where=window.is_desktop and **this.name=="휴지통 비우기"** pos=1 sep vis=true)

I replaced it with but it doesn't work.

**Comment by RubicBG** [comment]
try first:
`modify(type="*" find="휴지통 비우기"  vis=true)`
if works change it to:
`modify(type="recyclebin" find="휴지통 비우기"  pos=1 sep vis=true)`

**Comment by VenusGirl** [comment]
Thank you.
Both will activate the recyclebin.

Should I modify the script of **Shell/config/ko/imports/modify.nss** like this?



modify(type="*" find="휴지통 비우기"  vis=true)
![Shell이미지 002](https://github.com/moudey/Shell/assets/53147200/f300029b-b441-4529-ae8d-de1c9dae63ef)

modify(type="recyclebin" find="휴지통 비우기"  pos=1 sep vis=true)
![Shell이미지 003](https://github.com/moudey/Shell/assets/53147200/4f9861af-e00f-487f-b1d7-e733fc682dd4)

**Comment by RubicBG** [comment]
type="*" - this is to remove any constraints, but it is not good syntax

regardless of whether the trash is empty the command will be available

the problem is in windows:
https://answers.microsoft.com/en-us/windows/forum/all/recycle-bin-of-windows-10-not-working-proparly/175614ef-234d-47cf-a9b4-43e01810da43
hope this helps

**Comment by CRiS-SVRS** [comment]
> type="*" - this is to remove any constraints, but it is not good syntax
> 
> regardless of whether the trash is empty the command will be available
> 
> the problem is in windows: https://answers.microsoft.com/en-us/windows/forum/all/recycle-bin-of-windows-10-not-working-proparly/175614ef-234d-47cf-a9b4-43e01810da43 hope this helps

in my case, shell v1.9.10 is the problem. uninstalled it, recycle bin works as expected. installed again v1.9, it works as expected. if i upgrade to v1.9.10 again, the problem returns.

**Comment by akr-18** [comment]
Problem for me is also shell v1.9.10 (with latest Versions of Win10 and Win11). No problem with the previous versions. I've uninstalled shell and will wait until this issue is solved. Recycle bin works without shell v1.9.10.

**Comment by moudey** [comment]
@akr-18 Please test canary version https://nilesoft.org/download#canary

**Comment by VenusGirl** [comment]
In my case, Win 11 stable, RP, Beta, Dev, Canary all didn't work

modify(type="*" find="휴지통 비우기"  vis=true)

modify(type="recyclebin" find="휴지통 비우기"  pos=1 sep vis=true)

After modifying to , it all worked normally.

**Comment by dracp** [comment]
> @akr-18 Please test canary version https://nilesoft.org/download#canary

**Shell Canary 1.9.11** / Windows 11 Pro 23H2 22631.2861

Recycle bin, full.
"Empty Recycle Bin" option, disabled.
**It still doesn't work.**


![231214_Papelera de reciclaje_No funciona](https://github.com/moudey/Shell/assets/102802425/daeb4266-16b2-4c26-b659-e827f1b8a386)

**Comment by SaiyajinK** [comment]
> In my case, Win 11 stable, RP, Beta, Dev, Canary all didn't work
> 
> modify(type="*" find="휴지통 비우기" vis=true)
> 
> modify(type="recyclebin" find="휴지통 비우기" pos=1 sep vis=true)
> 
> After modifying to , it all worked normally.

thx

```
modify(type="*" find="Vider la corbeille" vis=true)
modify(type="recyclebin" find="Vider la corbeille" pos=1 sep vis=true)
```

(this solves the main function but when the trash is emptied, you can empty it indefinitely because "Empty trash" always remains active even when it is empty) 👍🏻

**Comment by RubicBG** [comment]
can someone test it:
https://discord.com/channels/1106387012707168318/1112126326665650176/1190658405644374066

**Comment by snuuuy** [comment]
> can someone test it: https://nilesoft.org/download#canary changes: https://discord.com/channels/1106387012707168318/1112126326665650176/1190658405644374066
![image](https://github.com/moudey/Shell/assets/143854508/0ec15f69-795b-4511-83ba-5e4a69ca3cb1)

Does not work
Shell Canary 1.19.12 / Windows 11 Home 23H2 22631.2861

**Comment by moudey** [comment]
Please try Canary build 13
https://nilesoft.org/download#canary

**Comment by CRiS-SVRS** [comment]
> Please try Canary build 13 https://nilesoft.org/download#canary

it now works. thank you

**Comment by VenusGirl** [comment]
Normal operation on Windows 11 Canary 12H3 26016.1012

Canary build 13 : [https://nilesoft.org/download#canary](https://nilesoft.org/download#canary)

Before emptying the recyclebin
![Shell1](https://github.com/moudey/Shell/assets/53147200/525d733c-97eb-409c-b7ec-c6a8de657394)

After emptying the recyclebin
![Shell2](https://github.com/moudey/Shell/assets/53147200/e8d8ee02-0afa-4581-8256-f2f27ff3c3f4)
