### ISSUE TITLE
copy as path option for wsl or linux option

### ISSUE THREAD

**Issue by shafschwd** [moudey/Shell#38]
As the name suggest add a option to 
`file manage` > `copy path`  > `wsl full path` and `wsl parent`

example
```
windows
G:\manifests\s\Starship\Starship\1.10.3
```

```
wsl
/mnt/g/manifests/s/Starship/Starship/1.10.3
```

is this possible?

**Comment by moudey** [comment]
```
item(
    title = "WSL Path"
    cmd=@sys.copy(path.separator(path.join("mnt", path.name(sel.root),str.sub(sel.path,3)), "/"))
)
```

**Comment by shafschwd** [comment]
🤩 works like a charm thanks

**Comment by shafschwd** [comment]
sorry i closed it before even testing it there are some problem i found 

1. there needs to be a slash before `mnt` like this `\mnt` other this error shows up

![image](https://user-images.githubusercontent.com/35454710/191149350-efdde110-9177-4398-9c4b-bd5259124bbf.png)

2. drive letter needs to be lower case 

![image](https://user-images.githubusercontent.com/35454710/191149535-c7f2cde5-970e-438c-9df0-b4f24e820dca.png)

3.if there is a space between folder name it'll show a error if the file name is `test tt`   you have to write it like cd `test\ tt/`

![image](https://user-images.githubusercontent.com/35454710/191151031-338f2780-34ac-4259-b597-0e6656a2ee46.png)

4. related to 3 if there are multiple spaces between file you have to write like this `System\ Volume\ Information/` basically you need to end folders last word with `/` and before that `\`

![image](https://user-images.githubusercontent.com/35454710/191151494-e3d90002-9c5f-4ca0-b279-7baf4d64c121.png)

thats all i found after a little bit of digging

**Comment by moudey** [comment]
Use stl.lower to convert chars to lowercase 
```
str.lower(path.name(sel.root))
```
Use str.replace to replace space with "\ "
```
str.replace(sel.path, ' ', '\ ')
```

**Comment by shafschwd** [comment]
> Use str.lower to convert chars to lowercase
> 
> ```
> str.lower(path.name(sel.root))
> ```
> 
> Use str.replace to replace space with "\ "
> 
> ```
> str.replace(sel.path, ' ', '\ ')
> ```

```
item(title = "WSL Path"cmd=@sys.copy(path.separator(path.join("/mnt", str.lower(path.name(sel.root)),str.replace(sel.path, ' ', '\ ')), "/")))
```
everytime i try to copy path it crashes the explorer

**Comment by moudey** [comment]
There is a bug in `str.replace` function that will be fixed in the next update

**Comment by moudey** [comment]
`str.replace` function bug has been fixed

**Comment by shafschwd** [comment]
aight waiting for the update 😄

**Comment by moudey** [comment]
`path.wsl` function has been added to help convert the path to wsl path

```
path.wsl(sel.path)
```

**Comment by shafschwd** [comment]
> `path.wsl` function has been added to help convert the path to wsl path
> 
> ```
> path.wsl(sel.path)
> ```
> 
> [shell 1.8 beta](https://nilesoft.org/download)

thank you so much

**Comment by shafschwd** [comment]
im kinda confused how do i add it like this `item(title='wsl' cmd=@path.wsl(sel.path))` ?

**Comment by shafschwd** [comment]
or like i did before
 `item(title = "WSL Path"cmd=@sys.copy(path.separator(path.join("/mnt", str.lower(path.name(sel.root)),str.replace(sel.path, ' ', '\ ')), "/")))`

**Comment by moudey** [comment]
```
item(title='wsl' cmd=@path.wsl(sel.path))
```

**Comment by shafschwd** [comment]
i dont know what im doing wrong here.


https://user-images.githubusercontent.com/35454710/192671811-d3fda6b1-19f3-4606-a085-58480486b644.mp4

and alsi do we have a discord server?

**Comment by moudey** [comment]
Use `sys.copy` function to copy the path to the clipboard
```
item(title='wsl' cmd=@sys.copy(path.wsl(sel.path)))
```

**Comment by shafschwd** [comment]
works perfectly thank you so much sorry for bothering you so much with this 😥.
although not related to this issue do you have a docs for the new stuff added on 1.8 and how to customise it.
i wanna decrease margin/padding from the sides of context menu container is there a doc u can point me to.

**Comment by machsix** [comment]
Just an update, with the lastest version, this works
```
		item(mode="single" title=@path.wsl(sel.path) cmd=command.copy(path.wsl(sel.path)))
```
