### ISSUE TITLE
theme didn't refresh after changing

### ISSUE THREAD

**Issue by caodoc** [moudey/Shell#381]
i changed & saved settings in theme.nss but the it didn't changed

before the change:
![image](https://github.com/moudey/Shell/assets/72246940/653b68a5-a327-4a0c-a8cf-908d5f2e6bd5)

after the change:
![image](https://github.com/moudey/Shell/assets/72246940/e7c759f1-f8b0-4e6b-b807-feb8a005f7da)

**Comment by moudey** [comment]
After save changes, restart explorer to reload settings.

**Comment by caodoc** [comment]
> After save changes, restart explorer to reload settings.

thank you, it worked.

**Comment by RubicBG** [comment]
you can also look into this
https://discord.com/channels/1106387012707168318/1139275510506082336/1155924668914610187
