### ISSUE TITLE
Some Missing Options

### ISSUE THREAD

**Issue by RandomGuy117** [moudey/Shell#386]
When you hover over new in the context menu. You get all the options except "Create Shortcut", which is available in the original windows context menu:

![image](https://github.com/moudey/Shell/assets/124488563/3104d996-acbf-40ea-9e3a-6f8587f91788)

Pin to Start Menu Option is also missing here :

![image](https://github.com/moudey/Shell/assets/124488563/831a5986-c4d0-4c17-9706-861c8e40a276)

**Comment by YisusChrist** [comment]
Another issue I notice is that the Vscode option is not grouped inside the 'Develop' category and that category is missing from the options list. It should appear this way by default:

<img width="264" alt="image" src="https://github.com/moudey/Shell/assets/58041337/2e72c3f7-8e90-4cc2-94b7-9d3258ac2f27">

I did a clean installation with the default settings and that module does not appear to be loading properly. Is there any way to group the options manually inside existing categories or create new ones?

**Comment by RubicBG** [comment]
https://github.com/moudey/Shell/issues/341#issuecomment-1747754752
https://github.com/moudey/Shell/issues/346


> When you hover over new in the context menu. You get all the options except "Create Shortcut", which is available in the original windows context menu:
> 
> ![image](https://private-user-images.githubusercontent.com/124488563/292835531-3104d996-acbf-40ea-9e3a-6f8587f91788.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE0NTUsIm5iZiI6MTcwMzY5MTE1NSwicGF0aCI6Ii8xMjQ0ODg1NjMvMjkyODM1NTMxLTMxMDRkOTk2LWFjYmYtNDBlYS05ZTNhLTZmODU4N2Y5MTc4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxNTMyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDJmZjdjYzI0Y2VkODgzOTgyNjkzYmRkNDM0YjJiMmZhZmJiMWNkYWU3YzZlMWY4MGRhYzk0ODhlYjdmNzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gbcz815J5d4hhJg00vvcdd3Ni1Sgk-Ty_kTsM7Sl3zQ)
> 
> Pin to Start Menu Option is also missing here :
> 
> ![image](https://private-user-images.githubusercontent.com/124488563/292840143-831a5986-c4d0-4c17-9706-861c8e40a276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE0NTUsIm5iZiI6MTcwMzY5MTE1NSwicGF0aCI6Ii8xMjQ0ODg1NjMvMjkyODQwMTQzLTgzMWE1OTg2LWM0ZDAtNGMxNy05NzA2LTg2MWM4ZTQwYTI3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxNTMyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmY2ODllZDlmYWI1NjRkNzVlNzA5MjczNzUxOGU1Y2NiMmE2YzMxNDYxNTMzMTJjZWMzNjZkN2E1OTMwY2Q0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OZ5o_8MvUbczg-FRKu_Br8zfJjU9-xD813B5yOv3Gbk)

**Comment by RubicBG** [comment]
> When you hover over new in the context menu. You get all the options except "Create Shortcut", which is available in the original windows context menu:
> 
> ![image](https://private-user-images.githubusercontent.com/124488563/292835531-3104d996-acbf-40ea-9e3a-6f8587f91788.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE5MjcsIm5iZiI6MTcwMzY5MTYyNywicGF0aCI6Ii8xMjQ0ODg1NjMvMjkyODM1NTMxLTMxMDRkOTk2LWFjYmYtNDBlYS05ZTNhLTZmODU4N2Y5MTc4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxNTQwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzM3OTFkOTM3OTM5MTJjNjk0YjNhMjZkNTY2NmUwOGNhY2Q2Yjc2OGZkN2NjMDI5MDI0M2I0YmYyYWMyNTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LyQUjwE_sTNdj7pHFCA2l7ywwEHwzvBJ-9DSFXPkcM4)
> 
> Pin to Start Menu Option is also missing here :
> 
> ![image](https://private-user-images.githubusercontent.com/124488563/292840143-831a5986-c4d0-4c17-9706-861c8e40a276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE5MjcsIm5iZiI6MTcwMzY5MTYyNywicGF0aCI6Ii8xMjQ0ODg1NjMvMjkyODQwMTQzLTgzMWE1OTg2LWM0ZDAtNGMxNy05NzA2LTg2MWM4ZTQwYTI3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxNTQwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTE2NjQ4OGI1MGRmYzQ5YTE4OWQ1ZjZhNTA2Y2E5ZmYwOGU5OWExYThiYzEyYzExY2ViNzU0NmM1NjIyZjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pEz_zcfA23CvqEUpSLGpgJdAZUji4cv8T7lsHjtm0Io)

https://github.com/moudey/Shell/issues/341#issuecomment-1747754752
https://github.com/moudey/Shell/issues/346

**Comment by RubicBG** [comment]
> Another issue I notice is that the Vscode option is not grouped inside the 'Develop' category and that category is missing from the options list. It should appear this way by default:
> <img alt="image" width="264" src="https://private-user-images.githubusercontent.com/58041337/292934224-2e72c3f7-8e90-4cc2-94b7-9d3258ac2f27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE5MjcsIm5iZiI6MTcwMzY5MTYyNywicGF0aCI6Ii81ODA0MTMzNy8yOTI5MzQyMjQtMmU3MmMzZjctOGU5MC00Y2MyLTk0YjctOWQzMjU4YWMyZjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1NDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYTQwYWFjZDYyZjU2MmQxNzE2Mzg2OWM5Mjc3ODlhMDI4Njg0MDcwYjRkMDlhNTU3ZGFhYTM0ZWYyYjMxODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXO1NB-GCkuCRtpQz25pRni5z0TwKPeiPRoNSyDmAaw">
> 
> I did a clean installation with the default settings and that module does not appear to be loading properly. Is there any way to group the options manually inside existing categories or create new ones?

the menu is hidden by default - not everyone uses this menu. you can show it with SHIFT+CLICK
or
edit` \imports\develop.nss`: delete `vis=key.shift()` from
`menu(mode="multiple" title='&Develop' vis=key.shift() sep=sep.bottom image=\uE26E)`

**Comment by RandomGuy117** [comment]
> > Another issue I notice is that the Vscode option is not grouped inside the 'Develop' category and that category is missing from the options list. It should appear this way by default:
> > <img alt="image" width="264" src="https://private-user-images.githubusercontent.com/58041337/292934224-2e72c3f7-8e90-4cc2-94b7-9d3258ac2f27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2OTE5MjcsIm5iZiI6MTcwMzY5MTYyNywicGF0aCI6Ii81ODA0MTMzNy8yOTI5MzQyMjQtMmU3MmMzZjctOGU5MC00Y2MyLTk0YjctOWQzMjU4YWMyZjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1NDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYTQwYWFjZDYyZjU2MmQxNzE2Mzg2OWM5Mjc3ODlhMDI4Njg0MDcwYjRkMDlhNTU3ZGFhYTM0ZWYyYjMxODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXO1NB-GCkuCRtpQz25pRni5z0TwKPeiPRoNSyDmAaw">
> > I did a clean installation with the default settings and that module does not appear to be loading properly. Is there any way to group the options manually inside existing categories or create new ones?
> 
> the menu is hidden by default - not everyone uses this menu. you can show it with SHIFT+CLICK or edit` \imports\develop.nss`: delete `vis=key.shift()` from `menu(mode="multiple" title='&Develop' vis=key.shift() sep=sep.bottom image=\uE26E)`


Thanks a lot. Feeling good after fixing it myself :). 

The Shortcut Option:
![image](https://github.com/moudey/Shell/assets/124488563/366eb392-ea57-454c-8b74-57368dd9f567)

The Pin Option: 
![image](https://github.com/moudey/Shell/assets/124488563/4db8ac6d-a57a-4e81-9c66-c8256b7abcd4)
