### ISSUE TITLE
Incompatibility with TeraCopy

### ISSUE THREAD

**Issue by hboyd2003** [moudey/Shell#387]
When using Shell, the context menus in the Teracopy GUI stop showing text with their entries. You are still able to click on an entry but the context menu is stuck at minimum width with no text.

<details>
  <summary>Without Nilesoft Shell</summary>

![image](https://github.com/moudey/Shell/assets/8950185/b9b48dbe-f89d-461d-b178-f0f27bfcec7e)
</details>

<details>
  <summary>With Nilesoft Shell</summary>

![Screenshot 2023-12-27 113823](https://github.com/moudey/Shell/assets/8950185/b9ce6b86-28f2-4541-b5a9-279d8bd55814)

</details>
<details>
  <summary>Desktop for reference:</summary>

![image](https://github.com/moudey/Shell/assets/8950185/c9eee86d-6167-4fdb-8878-a509d31b0b80)
</details>

**Comment by RubicBG** [comment]
add in shell.nss
`exclude.where = !process.is_explorer`

**Comment by RubicBG** [comment]
![image](https://github.com/moudey/Shell/assets/127151533/84ed382a-b48a-423d-8eed-b04b7ebe95f8)
this is better: `exclude.where = str.contains(window.title, 'TeraCopy')`

**Comment by RubicBG** [comment]
![image](https://github.com/moudey/Shell/assets/127151533/53dcb2a0-3d5b-4931-9153-da44b5ac6e31)
this is better:
`exclude.where = !process.is_explorer and str.contains(window.title, 'TeraCopy')`

**Comment by hboyd2003** [comment]
@RubicBG I have just realized that I had removed the ```!process.is_explorer``` a long time ago as I was playing around with it. So there is not actual need for another exclusion or in other words there is no actual incompatibility.
