### ISSUE TITLE
Directory Opus support

### ISSUE THREAD

**Issue by shifterest** [moudey/Shell#39]
Would it be possible to use Nilesoft Shell context menus with DOpus?

**Comment by moudey** [comment]
Only Windows File Explorer is supported. But in the future, other programs will be supported

**Comment by moudey** [comment]
@shifterest  Please test this [build](https://github.com/moudey/Shell/files/10127710/shell-test.zip) 

Comment this line to enable shell with other programs
```
exclude.where = !process.is_explorer
```

**Comment by shifterest** [comment]
Commented out the line, restarted DOpus. Doesn't seem to work with DOpus 12.29.

**Comment by JoyHak** [comment]
I also like the idea of integrating the beautiful Nilesoft shell into other file management applications: Directory Opus, Xyplorer file manager, everything search, Flow launcher search, ...
