### ISSUE TITLE
Blank context menu inside TreeSize Free

### ISSUE THREAD

**Issue by iamkyaru** [moudey/Shell#390]
In TreeSize Free, using rightclick for opening the context menu is not working as supposed to. A blank context menu appears, that is still clickable, though blank.

<img src="https://github.com/moudey/Shell/assets/28540206/12e5b604-7b4e-433c-b722-9111ce8561c3" width="220">

What I already tried is to exclude it in the configuration file `shell.nss`, which for me looks like this:

```
settings
{
        // *SNIP*
	exclude.where = !process.is_explorer and (str.start(window.title, 'TeraCopy') or str.start(window.title, 'TreeSize'))
	// *SNIP*
}
```

Though it didn't work as I expected it to work. I kept the config with the default settings, except for the key `exclude.where` inside the `settings` section.

**Comment by moudey** [comment]
Try  with `process.name` or `process.path`
```js
exclude.where = !process.is_explorer and (str.start(window.title, 'TeraCopy') or str.start(process.name,"TreeSize"))
```

**Comment by RubicBG** [comment]
I don't use TreeSize and have no way to check: if this syntax works alone:
`exclude.where = !process.is_explorer and str.start(process.name, "TreeSize")`

PS: the case with TeraCopy: if !process.is_explorer is removed when you are in a folder in explorer and the name of this folder starts with TeraCopy (not that anyone names their folders to start with TeraCopy :) ) - it will also not have NS
![image](https://github.com/moudey/Shell/assets/127151533/0d74ca3a-9721-4a08-a5b3-0448e8340e3d)

**Comment by iamkyaru** [comment]
Maybe then it's better to check the process for TeraCopy too, right?
