### ISSUE TITLE
Underline access keys don't work

### ISSUE THREAD

**Issue by ABAL1412** [moudey/Shell#391]
When I enable the option "**_Underline access keys when available_**" in settings, it doesn't work. I'm on **Windows 10 22H2**.
![image](https://github.com/moudey/Shell/assets/135466317/9a020423-60c1-45bb-9f0f-90e25cd6fa7d)
![image](https://github.com/moudey/Shell/assets/135466317/1dbe2a64-5bed-485e-83c5-dbd1c7192b3b)

**Comment by RubicBG** [comment]
NS has its own settings:
https://nilesoft.org/docs/configuration/themes
// prefix value [auto, 0 = dont display,  1 = display, 2 = ignore]
		prefix = 1
there is also an option to link the two settings: when you change the settings in the windows panel, they can be reflected in NS directly

**Comment by ABAL1412** [comment]
Thank you! But how can I link the two settings? Sorry but I'm not good at programming. I'm not an English native speaker either. I can't find it on your web.

**Comment by RubicBG** [comment]
it is nowhere - a new logic has yet to be created. when I'm ready I'll write.
or 
come to NS Discord Channel: https://discord.com/channels/1106387012707168318/

**Comment by RubicBG** [comment]
add this line to shell.nss:
```JS
theme.item.prefix=if(str.equals(reg.get('HKEY_CURRENT_USER\Control Panel\Accessibility\Keyboard Preference', 'On'), 1), 1,'')
```
reload NS (or restart the explorer)
the next time you change the Windows setting, you only need to reload the NS

there are other ways to achieve the result
- to make a command in the context menu to reload the settings
- to set the setting independently when opening the context menu, but there will be a visible result from the next opening of the menu (cannot be done globally - this can be done only for a certain situation: only on the desktop, or only on the taskbar, or only in e-explorer ...)
