### ISSUE TITLE
Window Spotlight not working as intended 

### ISSUE THREAD

**Issue by AverageBlank** [moudey/Shell#393]
Hello, I have installed Nilesoft Shell and am experiencing a problem regarding windows spotlight.
When Windows Spotlight is set as the source for wallpapers, it creates an icon on your desktop called "Learn about this picture" which you can right click allowing you to change the wallpaper.
However, with Nilesoft the right click menu for windows spotlight isn't showing up.

This is with Nilesoft Disabled.
![image](https://github.com/moudey/Shell/assets/112507212/723c0f20-f995-4dc2-9cc5-918957da2a37)

This is with Nilesoft Enabled.
![image](https://github.com/moudey/Shell/assets/112507212/f90d6722-2358-4098-ae70-e677ece31bf9)

**Comment by RubicBG** [comment]
https://github.com/moudey/Shell/issues/354

**Comment by RubicBG** [comment]
https://nilesoft.org/download#canary
with the canary version you can achieve the following result
![image](https://github.com/moudey/Shell/assets/127151533/380f6c8b-f39d-4807-84ec-df0fc7c1ff9d)

**Comment by AverageBlank** [comment]
I see, thank you.

**Comment by RubicBG** [comment]
[AverageBlank](https://github.com/AverageBlank) which version of windows do you have?

**Comment by Rus1anB** [comment]
Unfortunately, the problem persists. I have no "Switch to next picture" option in the context menu from Shell :(

Canary version 1.9.14, Windows 11 Pro 23H2 22631.3085

**Comment by KarmaMole** [comment]
> https://nilesoft.org/download#canary with the canary version you can achieve the following result ![image](https://github.com/moudey/Shell/assets/127151533/380f6c8b-f39d-4807-84ec-df0fc7c1ff9d)

Can you explain how you got this result? I've got canary installed and it still doesn't work. Did you add anything to the config files?

**Comment by RubicBG** [comment]
Windows improve the "modern" Spotlight context menu, but cripple the "legacy" one - only the command `open` is present. (the screenshot is old)
https://github.com/RubicBG/Nilesoft-Shell-Snippets/blob/main/ext.desktop/sys.spotlight.md
I recreated the commands as best I could

**Comment by KarmaMole** [comment]
> Windows improve the "modern" Spotlight context menu, but cripple the "legacy" one - only the command `open` is present. (the screenshot is old) https://github.com/RubicBG/Nilesoft-Shell-Snippets/blob/main/ext.desktop/sys.spotlight.md I recreated the commands as best I could

So many snippets!!! Thanks!!!

**Comment by KarmaMole** [comment]
> Windows improve the "modern" Spotlight context menu, but cripple the "legacy" one - only the command `open` is present. (the screenshot is old) https://github.com/RubicBG/Nilesoft-Shell-Snippets/blob/main/ext.desktop/sys.spotlight.md I recreated the commands as best I could

I'm not sure what I'm doing wrong? 

I put the sys.spotlight.nss in the imports folder, and added a line to import it into shell.nss - but it's not working :( 

Help?

**Comment by RubicBG** [comment]
first - open shell.log file with any editor and see if there is a info about the problem

**Comment by KarmaMole** [comment]
> first - open shell.log file with any editor and see if there is a info about the problem

Nope - nothing useful: 

Nilesoft Shell
version 1.9.17 64-bit
support@nilesoft.org
https://nilesoft.org

Windows 11 Pro 64-bit, version 10.0.26100.3915
--------------------------------------------------------------------------------

2025-05-15 13:56:39 [info] Register completed successfully.
2025-05-15 13:56:41 [info] Restart Explorer.
2025-05-15 14:25:38 [info] Unregister completed successfully.
2025-05-15 14:25:39 [info] Restart Explorer.
2025-05-15 14:26:04 [info] Register completed successfully.
2025-05-15 14:26:05 [info] Restart Explorer.
2025-05-15 22:49:34 [info] Unregister completed successfully.
2025-05-15 22:49:35 [info] Restart Explorer.
2025-05-15 22:49:37 [info] Register completed successfully.
2025-05-15 22:49:38 [info] Restart Explorer.

**Comment by RubicBG** [comment]
i double check the snippet - it must show something
change 
`$sp_default_type  = sel.type==0 and wnd.is_desktop and sel.raw=='::{2cc5ca98-6485-489a-920e-b3e88a6ccce3}'`
to 
`$sp_default_type  = wnd.is_desktop`
this will add the menu to all objects on desktop - only to check if the snippets works

**Comment by KarmaMole** [comment]
Changed it, and it's still not showing up anywhere, and no info about it in shell.log: 

Nilesoft Shell
version 1.9.17 64-bit
support@nilesoft.org
https://nilesoft.org

Windows 11 Pro 64-bit, version 10.0.26100.3915
--------------------------------------------------------------------------------

2025-05-15 13:56:39 [info] Register completed successfully.
2025-05-15 13:56:41 [info] Restart Explorer.
2025-05-15 14:25:38 [info] Unregister completed successfully.
2025-05-15 14:25:39 [info] Restart Explorer.
2025-05-15 14:26:04 [info] Register completed successfully.
2025-05-15 14:26:05 [info] Restart Explorer.
2025-05-15 22:49:34 [info] Unregister completed successfully.
2025-05-15 22:49:35 [info] Restart Explorer.
2025-05-15 22:49:37 [info] Register completed successfully.
2025-05-15 22:49:38 [info] Restart Explorer.
2025-05-17 18:14:56 [info] Unregister completed successfully.
2025-05-17 18:14:57 [info] Restart Explorer.
2025-05-17 18:15:03 [info] Register completed successfully.
2025-05-17 18:15:04 [info] Restart Explorer.


![Image](https://github.com/user-attachments/assets/c567cdea-11bc-4bf9-837d-fcd7d9e6043b)

**Comment by KarmaMole** [comment]
And in case you're wondering: 

import 'imports/terminal.nss'
import 'imports/file-manage.nss'
import 'imports/develop.nss'
import 'imports/goto.nss'
import 'imports/taskbar.nss'
import 'imports/sys.spotlight.nss'

It's there, and in the imports folder.

**Comment by KarmaMole** [comment]
> compress everything and send it - i have tested it with new profile and works

[Shell.zip](https://github.com/user-attachments/files/20271986/Shell.zip)

**Comment by KarmaMole** [comment]
> compress everything and send it - i have tested it with new profile and works

Did this help at all :) ?

**Comment by RubicBG** [comment]
sorry for the late reply
as you archived it everything in shell.nss is missing:
`import 'imports/sys.spotlight.nss'`
after I added it and restarted explorer.exe the snippet works
