### ISSUE TITLE
Can't Get Open in Terminal to Open as Admin

### ISSUE THREAD

**Issue by bcrotty** [moudey/Shell#396]
I'm trying to modify the Open in Terminal command to optionally be able to run as admin when shift is pressed, similar to how it's done in terminal.nss. Here's my code:

```
$tip_run_admin=["Press SHIFT key to run as administrator"]
$has_admin=key.shift() or key.rbutton()
modify(find="Open in Terminal" tip=tip_run_admin admin=has_admin cmd='wt.exe' arg='-d "@sel.path\."')
```

When I put that in, Shell doesn't load. I've tried several other variations, but I can't seem to make it work.

It does work like this:

```
$tip_run_admin=["Press SHIFT key to run as administrator"]
$has_admin=key.shift() or key.rbutton()
remove(find="Open in Terminal")
item(where=package.exists("WindowsTerminal") title="Open in Terminal" tip=tip_run_admin admin=has_admin image='@package.path("WindowsTerminal")\WindowsTerminal.exe' cmd='wt.exe' arg='-d "@sel.path\."')
```

What can I change about the first code block to make it work?

**Comment by RubicBG** [comment]
modify() can neither modify the command nor overwrite it: it cannot see the command. This also includes "run as admin". 

so asked this question nothing can be done

**Comment by bcrotty** [comment]
Understood. Thanks!
