### ISSUE TITLE
I want to do 2 things

### ISSUE THREAD

**Issue by Marvinoo** [moudey/shell#4]
1- To remove 'development' & 'nilesoft shell' from context menu.
2- Rename 'customize this folder' item to only 'customize'.
Thanks in advance and for your work on this wonderful app!

**Comment by moudey** [comment]
1- These items are indicative and optional that you can delete. 

2- You can rename this item by the following code:
```
static {
   item(find='customize this folder' title='Customize')
}
```

**Comment by Marvinoo** [comment]
> 1- These items are indicative and optional that you can delete.

Please tell me how as I've zero knowledge about that code language and I tried removing portions of the code but didn't make it.
> 
> 2- You can rename this item by the following code:
> 
> ```
> static {
>    item(find='customize this folder' title='Customize')
> }
> ```
THANKS A LOT!

**Comment by moudey** [comment]
Items can be ignored by multi-Line comment
```
/*
menu(title='nilesoft shell')
{
    item(...)
    item(...)
}
*/
```
