### ISSUE TITLE
Hide some items in a sub-menu

### ISSUE THREAD

**Issue by wolive-20** [moudey/Shell#40]
Hi,

I would like to hide only the Google items in the 'New' context sub-menu but can't seem to figure out how to reference the sub-menu items. I would appreciate your assistance if this could be achieved.

Many thanks in advance

![image](https://user-images.githubusercontent.com/36878140/191576514-528d840d-3407-42e3-a616-419f930be41e.png)

**Comment by moudey** [comment]
Currently only top level menu items are customized, I'll try to target other levels later.

**Comment by moudey** [comment]
Hi @wolive-20,

Modification of sub-items is supported by this command
```
static
{
    item(find='shortcut' in='/new' vis=remove)
    item(find='rar|cab' in='/7-zip/open archive' vis=disabled)
}
```
You can use this feature in the next update

**Comment by zilpe** [comment]
Hi @moudey, thank you so much for this! Is it possible to move sub-items to the main menu? For example, moving '/7-zip/open archive' to the main menu. Thanks again.

**Comment by moudey** [comment]
Hi @zilpe 
This feature will be added later

**Comment by moudey** [comment]
@wolive-20 Please test this [build](https://github.com/moudey/Shell/files/10127710/shell-test.zip) 

add this code to static items
```
static
{
    item(find='google' in='/new' vis=remove)
    item(find='rar|cab' in='/7-zip/open archive' vis=disabled)
}
```

**Comment by wolive-20** [comment]
Hi @moudey - I've downloaded the test build and added the static entries below to the shell.nss file. Unfortunately it does not work. 

static
{
      item(find='Shortcut' in='/new' vis=remove)
      item(find='Google Docs' in='/new' vis=disabled)
      item(find='Google Sheets' in='new' vis=remove)
}

![Image_007 (02-12-2022)](https://user-images.githubusercontent.com/36878140/205287511-2aa22cc7-88aa-4d1e-862a-999bfc729693.png)

**Comment by moudey** [comment]
@wolive-20 Sorry try [this](https://github.com/moudey/Shell/files/10142067/shell-test.zip)

**Comment by wolive-20** [comment]
Hi @moudey - The latest version works perfectly, thank you very much.

static
    {
        item(find='Shortcut' in='/new' vis=disabled)
        item(find='Google*' in='/new' vis=remove)
    }

![Image_011 (02-12-2022)](https://user-images.githubusercontent.com/36878140/205326485-ec17ea0f-fbcc-4c7d-84bd-c2c2553d1414.png)
