### ISSUE TITLE
Recycle Bin doesn't work on another system language 

### ISSUE THREAD

**Issue by drMikeMiles** [moudey/Shell#406]
when I change the system language to Uk, the "empty trash" item is not active, but if I change to Eng everything is fine, how i can fix that?
![1 1](https://github.com/moudey/Shell/assets/66922497/050f6d95-50e6-4c29-83fa-dc26854dce3a)
![1 2](https://github.com/moudey/Shell/assets/66922497/d6474c68-583b-4d48-a8b5-b1b8b1e72d2f)

**Comment by RubicBG** [comment]
**Shell Canary build 13** https://nilesoft.org/download#canary

- Fix Recycle bin issue
- Fix internal bugs
