### ISSUE TITLE
Transparency effects do not work in 1.8 Beta

### ISSUE THREAD

**Issue by kronuschan** [moudey/Shell#41]
Hello, after some quick tests with 1.8 beta, I've discovered that none of the effects under background work correctly, aside from auto. Setting it to 1 through 5 makes all context menus look like this:

![image](https://user-images.githubusercontent.com/108924641/192375017-8fc47d3f-e45c-4d34-8b14-133cc406c5a3.png)

Then, when I also tune opacity alongside, it looks like this:

![image](https://user-images.githubusercontent.com/108924641/192375218-a15da753-26af-4abb-9c99-39d233db0f1e.png)

The menu does go transparent, ish.

When I use opacity with the effect set to auto, there is no transparency at all, and the menu is fully opaque.

**Comment by moudey** [comment]
Increasing the opacity will cause the transparency to fade

```
theme
{
    background
    {
        opacity = 0 // transparent background
        effect = ["acrylic", auto, 50]
    }
	
    item
    {
        back
        {
            normal = 0	// transparent
            normal-disabled = 0
        }
    }
}
```

**Comment by moudey** [comment]
mica and tabbed not supported yet. only transparent, blur, and acrylic

**Comment by moudey** [comment]
https://nilesoft.org/blog/shell-version-1-8-beta
