### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by kaser2010** [moudey/Shell#411]
The problem is explained in the video
Shell Canary build 14

https://github.com/moudey/Shell/assets/18640442/52c0968c-1bca-47ee-8977-f892fc18b9ed

Shell Canary build 13 No problem

**Comment by RubicBG** [comment]
it's because of the scroll indicator, which is still not working properly - the problem is being worked on

**Comment by kaser2010** [comment]
Thanks
I'm waiting

**Comment by RubicBG** [comment]
can you try with this file: [6619C47311114EE7B92579E4BDC5F025.zip](https://github.com/moudey/Shell/files/14226079/6619C47311114EE7B92579E4BDC5F025.zip)
source: https://discord.com/channels/1106387012707168318/1106387015425069151/1205112441760129085

**Comment by kaser2010** [comment]
> can you try with this file: [6619C47311114EE7B92579E4BDC5F025.zip](https://github.com/moudey/Shell/files/14226079/6619C47311114EE7B92579E4BDC5F025.zip) source: https://discord.com/channels/1106387012707168318/1106387015425069151/1205112441760129085

Thank you it works now
