### ISSUE TITLE
Dark mode not working with latest update

### ISSUE THREAD

**Issue by vikingnope** [moudey/Shell#418]
Dark mode does not seem to be working after 1.9.15:

![image](https://github.com/moudey/Shell/assets/81376423/8b737457-9ab4-47dd-835c-c4d74e2752c1)

**Comment by moudey** [comment]
Open "imports/theme.nss" and change `dark` option to `default` or `auto`
```
dark = default
```
Save changes, press <kbd>CTRL</kbd> + <kbd>RIGHT-CLICK</kbd> to reload settings.

**Comment by vikingnope** [comment]
That seems to have worked for me, thanks

**Comment by stamminator** [comment]
@moudey The workaround is much appreciated, but ideally, either the legacy `sys.dark` should continue to be honored or the install/update process should find and replace instances of the legacy value with the new one. Just a suggestion for future updates.

**Comment by Alhlhli** [comment]
https://github.com/moudey/Shell/issues/435#issuecomment-2453614897
