### ISSUE TITLE
Style issues in 1.8 beta

### ISSUE THREAD

**Issue by M7MDE7EGAZY** [moudey/Shell#42]
**changing font in 1.8 beta not working but working with 1.7 & have context item height issue while still no transparency or mica & icons can't be colored with colorize like the explorer**

**Comment by moudey** [comment]
Hi Mohamed,

> changing font in 1.8 beta not working but working with 1.7

Font options have been moved to the theme scope.

> have context item height issue while still no transparency or mica

Mica and Tabbed are not currently supported. 

To make background of menu item transparent, change normal color opacity value to `0`.

```
shell  {
    default  {
        theme  {

            font-name="Segoe Script"
            font-size=20

            item {
                // transparent background of item 
                back-normal=0

                // Change height of item
                padding.top=3 
                padding.bottom=3
            }
        }
    }
}
```

Please attach a screenshot of the other issues

**Comment by shafschwd** [comment]
how do i reduce padding from the side of the container?

![image](https://user-images.githubusercontent.com/35454710/193463122-721f8f6a-1e95-433d-bdb6-e17f19eca93d.png)

**Comment by moudey** [comment]
Hi @shafschwd Use `margin` or `padding` option to reduce or increase the space
```
default  {
    theme  {
        item {
            padding.left=10
            padding.right=10
            // or
            padding = [10, auto]   // [left = 10 and right = 10, top = default and bottom = default]

            // or use margin option
            margin=[10, auto]   // [left and right, top and bottom]
        }
    }
}
```

**Comment by M7MDE7EGAZY** [comment]
how to use these options all is see is
shell.dll
shell.exe
shell.log
shell.shl
readme.txt

________________________________

**Comment by moudey** [comment]
> how to use these options all is see is shell.dll shell.exe shell.log shell.shl readme.txt

These options are set in [shell.shl](https://nilesoft.org/docs/syntax) file.

**Comment by M7MDE7EGAZY** [comment]
is it edited via notepad or custom app ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by moudey** [comment]
> is it edited via notepad or custom app ? Get Outlook for Android<https://aka.ms/AAb9ysg>

`shell.shl`  is a text format.  You can use Notepad or your favorite text editor.

**Comment by M7MDE7EGAZY** [comment]
thanks a lot

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by shafschwd** [comment]
> Hi @shafschwd Use `margin` or `padding` option to reduce or increase the space
> 
> ```
> default  {
>     theme  {
>         item {
>             padding.left=10
>             padding.right=10
>             // or
>             padding = [10, auto]   // [left = 10 and right = 10, top = default and bottom = default]
> 
>             // or use margin option
>             margin=[10, auto]   // [left and right, top and bottom]
>         }
>     }
> }
> ```

there's still a padding idk what im doing wrong

![image](https://user-images.githubusercontent.com/35454710/193698745-c3974214-eccf-48b5-b9f5-8c14e11bba2d.png)

![image](https://user-images.githubusercontent.com/35454710/193698771-cc45033c-d8c1-4e3b-a1a2-290ffbb59831.png)

**Comment by moudey** [comment]
@shafschwd Uncomment the code to be executed.  After saving the changes, `right click`+`ctrl` to reload the settings

**Comment by shafschwd** [comment]
holy shit im so dumb i thought that that was some kind of parameter or something since commenting uses `//` since there was no syntax highlighting. so sorry for wasting your time 😥.

**Comment by moudey** [comment]
You can use C/C++, C# or javascript syntax highlighting when opening shell.shl in vscode. :)

**Comment by fatguy666** [comment]
Mahmoud, any idea how I can stop the text being cut off here?

I love being able to skin the old context menu, not fussed about all the other (very impressive) stuff so I've basically commented everything out apart from the "default" section.

![image](https://user-images.githubusercontent.com/11232882/193947053-7599fe9c-e3c8-4944-bb29-1b765325f4b4.png)

**Comment by fatguy666** [comment]
@moudey yes, 1.8 beta as Windows latest update broke my 1.7 so I went to reinstall and noticed the beta was available. Yeah, I have scaling in Windows set to 300% as I site about 2.5m away from a 4K TV.

Thanks, I'll have a play about with it tonight.

**Comment by M7MDE7EGAZY** [comment]
![image](https://user-images.githubusercontent.com/76889809/197339142-5db8297d-5fcd-4444-9faa-ccecd4c39a92.png)
styling isn't applied in start11 taskbar

**Comment by davidlieberman** [comment]
What settings should I change if I want the old 1.7 auto theme back on 1.8 Beta? I'm having trouble reverting the new context menu boarder margin (although setting those params to enabled=0 doesn't seem to remove it) and item hover blue highlighting to how they were before updating today.

**Comment by moudey** [comment]
Hi @davidlieberman 

> 1.8 beta changes
The following options have been moved to theme scope: (item, font, border shadow, separator, symbol)
```
theme
{
    name = auto
    dark = auto

    border-padding = [4, 4]  // This option has been moved to layout-padding in the next update

    item
    {
        back-select = [#f00, 50] // [color, opacity] highlighting
        padding = [10, 2] 
        margin = [0, 2]
    }
}
```
There are still some changes with the new update

**Comment by Traxmaeus** [comment]
Hey @moudey, first of all I want to say that **Shell** is amazing and you did **amazing job!**

I was searching in docs and here (git) to resolve the issue with padding/scaling on Windows 22H2 22621.819
and found this thread where you are mentioning possible solutions to the issue : quoting
> default {
>     static.auto=0
>     static=0
>     dynamic=0

I've tried this solution although with not positive results:

1. The issue still persists (text is cut because of scaling)
2. Taskbar menu stop working completely

I just wanted to ask you if there are any alternatives or it's necessary to wait for a Shell Update.

- **Shell version** - 1.8
- **Win version** - Windows 22H2 22621.819
- **Desktop Resolution** - 2560x1440
- **Windows Scaling** - 125% (_No custom scaling value_)
- **Windows Text Scaling** - 100% (_Default_)

### My Padding & Margin settings in **shell.shl**

```
item
{
	text.normal=[#fff, 20]
	text.select=[auto, 50]
	back
	{
	//normal = 0
	//normal-disabled = 0			
	select = [#197896, 75]
	select-disabled = [#fff, 15]
	}

				
	padding = [left, top, right, bottom]
	padding.left = 6
	padding.right = 64
	padding.top = 2
	padding.bottom = 2

	margin = [left, top, right, bottom]
	margin.left = 8
	margin.right = 8
	margin.top = 2
	margin.bottom = 2
```

![explorer_lGOtrpJOb6](https://user-images.githubusercontent.com/74116678/206321300-ddb0a95b-84c9-4537-8dae-449b04291cb0.gif)

**Comment by Traxmaeus** [comment]
@moudey I've tested the build that you've sent me!

- The text is scaled properly now.
- The padding looks proper.
- Taskbar scaling and padding looks properly scaled too.

![explorer_eoDL0s0FwU](https://user-images.githubusercontent.com/74116678/206325061-589352a6-875d-4df9-9c85-1f58845a86e6.gif)
