### ISSUE TITLE
After uninstalling, somehow the nilesoft context menu is back for the taskbar

### ISSUE THREAD

**Issue by wbkang** [moudey/Shell#420]
I am running Windows 11 Version 23H2 (OS Build 22631.2792).

As you can see below, even after uninstalling it, the nilesoft context menu is back for the taskbar.

![image](https://github.com/moudey/Shell/assets/1643598/0c573ec2-a564-4134-a3bf-bf5ca127d07e)

When this happens, it overrides the context menu for individual programs as well but only half (?) of the taskbar.

Up to the 4th item from the left, the normal context menu works:
![image](https://github.com/moudey/Shell/assets/1643598/902cd652-aa81-4db5-8c24-20902ba80f05)

From the 5th item and on, somehow the uninstalled shell context menu comes back and it's impossible to use the normal context menu:

![image](https://github.com/moudey/Shell/assets/1643598/57463ab6-a169-4e7a-9293-d26e90efcfe4)

I've tried reinstalling the latest shell and uninstalling, rebooting, but it somehow comes back after a reboot. What could I do to revert this back to the original context menu?

**Comment by vikingnope** [comment]
Did you try unregistering it?

![image](https://github.com/moudey/Shell/assets/81376423/3307a5b2-3a2d-42a2-9ba2-f526971c6077)

**Comment by moudey** [comment]
You should have uninstalled any old version before updating.  Look in the ProgramFiles folder for the old Shell version and uninstall it

**Comment by wbkang** [comment]
@moudey thank you I was able to find a stray installation from a long time ago.
