### ISSUE TITLE
[error] line[1] column[1], Identifier config unexpected "static.nss"

### ISSUE THREAD

**Issue by rayshabh** [moudey/Shell#422]
**Nilesoft Shell
version 1.9.15 64-bit**

Whenever I'm trying to import `static.nss ` in `shell.nss` file by adding a line in the file `import 'imports/modify.nss'`, I get an error 
`[error] line[1] column[1], Identifier config unexpected "static.nss"`.

### The script in static.nss: 
```
static
{	
	item(where=this.title.length > 25 menu=title.more_options)
	item(find='"graphics options"|"graphics properties"' image=\uE0EE)
}
```

By the way, the `static.nss` import was working fine in the **previous version** of nilesoft shell.

Please guide me to fix it!

**Comment by RubicBG** [comment]
this syntax `static{ }` is no longer used (last used in version 1.8.1). Delete it

**Comment by rayshabh** [comment]
> this syntax `static{ }` is no longer used (last used in version 1.8.1). Delete it

Okay, now I'm able to import without error but the effect is not working. I'm trying to achieve is to replace the icons of Intel Graphics Properties and Graphics Options in the context menu with some other icon.

Is there some mistake in the script? Btw, I removed the `static{ }` from static.nss file.

**Comment by RubicBG** [comment]
Graphics Properties and Graphics Options are in "more option" menu or in the main menu?

**Comment by rayshabh** [comment]
> Graphics Properties and Graphics Options are in "more option" menu or in the main menu?

Hope this helps!
![Screenshot (38)](https://github.com/moudey/Shell/assets/43938393/8f7aac2d-1c5c-4503-9acd-b4c47629587a)

**Comment by moudey** [comment]
The `static { }` section was removed and the items tag was changed to `modify`

To change the icon, use this command
```js
modify(find='Graphics Properties' image=#f00)
```

Save changes, Restart explorer to reload settings.
