### ISSUE TITLE
[Info]Source of Shell icons

### ISSUE THREAD

**Issue by boromyr** [moudey/Shell#429]
@moudey I wanted to ask what is the source of the fluent icons used in the Shell context menu, as I couldn't find them in the repository, and if it was possible to download them. Thank you.

**Comment by RubicBG** [comment]
https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font

> Segoe Fluent Icons is a type of font created by Microsoft. Instead of letters and numbers, it contains symbols and icons. These icons are designed to be used in user interfaces of software and applications. They're part of Microsoft's Fluent Design System, which is all about making interfaces easy to use and consistent across different Microsoft products like Windows, Office, and others. The goal is to give users a smooth and intuitive experience, no matter which Microsoft product they're using.
... and they can not be downloaded

**Comment by H1DDENADM1N** [comment]
https://aka.ms/SegoeFonts

**Comment by boromyr** [comment]
Thank you very much!

**Comment by H1DDENADM1N** [comment]
https://learn.microsoft.com/en-us/windows/apps/design/downloads/#fonts
