### ISSUE TITLE
22H2: Shell no longer overrides right click

### ISSUE THREAD

**Issue by JordanAnthonyKing** [moudey/Shell#43]
Hi, as of upgrading to 22H2 the default context menu is shown on right click for files, folders, and the desktop. Taskbar works as normal.

The 'Show more options' in the default context menu that would usually open the legacy context menu opens the nilesoft shell.

I have tried uninstalling and reinstalling.

Is this fixed in 1.8?

**Comment by moudey** [comment]
Hi, After upgrading to 22H2,  registry key `HKEY_CLASSES_ROOT\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}` is modified to default. 
You just need to re-register Shell by opening shell.exe with administrator privileges and then register with restart Explorer.
