### ISSUE TITLE
[Question] accessing certin menus

### ISSUE THREAD

**Issue by CatsArmy** [moudey/Shell#430]
im trying to add stuff to the Start menu but i cant find how i would do that anywhere in the forum or documents

**Comment by RubicBG** [comment]
The Start menu cannot be configured via NS. 

Commands can be added in the context menu on the desktop or on the taskbar

**Comment by CatsArmy** [comment]
> The Start menu cannot be configured via NS.
> 
> Commands can be added in the context menu on the desktop or on the taskbar

![image](https://github.com/moudey/Shell/assets/104517593/51f6b5b4-c988-4c4c-b76a-613b6ca7170b)
ah i see thank you good to know i would add that into the docs personally as like one of these^^^ info bubbles

**Comment by CatsArmy** [comment]
Guess this issue can be closed.
