### ISSUE TITLE
notepad++ is disabled

### ISSUE THREAD

**Issue by dijkstar0317** [moudey/Shell#431]
![2](https://github.com/moudey/Shell/assets/143583985/074ce3bc-e675-4911-979f-f0bec0ab3c4e)

**Comment by RubicBG** [comment]
modify(find="Notepad" vis=true)

**Comment by dijkstar0317** [comment]
> `modify(find="Edit with Notepad" vis=true)`
> 
> change search string "Edit with Notepad"

**Comment by Gaobo-Hp1** [comment]
> `modify(find="Edit with Notepad" vis=true)`
> 
> change search string "Edit with Notepad"

hello, Which file should I modify？

**Comment by RubicBG** [comment]
open `\imports\modify.nss` in text editor, like `notepad.exe`
copy the code at the end of the file, save it, reload the app with `ctrl+right click` or restart `explorer.exe`

**Comment by Gaobo-Hp1** [comment]
> open `\imports\modify.nss` in text editor, like `notepad.exe` copy the code at the end of the file, save it, reload the app with `ctrl+right click` or restart `explorer.exe`

I copy the code and restart `explorer.exe`, the `edit with notepad++` is still disabled, maybe I need to restart my computer?

**Comment by dijkstar0317** [comment]
![image](https://github.com/moudey/Shell/assets/143583985/d681eb20-95bb-407c-8688-0a9e28cba5e0)
like it , it's OK!

**Comment by Gaobo-Hp1** [comment]
> ![image](https://private-user-images.githubusercontent.com/143583985/310024732-d681eb20-95bb-407c-8688-0a9e28cba5e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjQ4MDMsIm5iZiI6MTcwOTYyNDUwMywicGF0aCI6Ii8xNDM1ODM5ODUvMzEwMDI0NzMyLWQ2ODFlYjIwLTk1YmItNDA3Yy04Njg4LTBhOWUyOGNiYTVlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwNzQxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDZjNTQxYmNiNDQzYzEwNWNiZDQ5MDJhMmQ3MzJhYTExNWNhNTExZTg5NTUxNTc0NmUwMjg2N2Q1YmFmNDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XULAqEcp3w7kuFciVTEBIPkWd_ySlwXyPBLFZWIl4qg) like it , it's OK!

OK， it's work . thanks

**Comment by n8petersen** [comment]
> `modify(find="Edit with Notepad" vis=true)`
> 
> change search string "Edit with Notepad"

This worked for me, thanks @RubicBG

**Comment by Dev123456689** [comment]
@dijkstar0317 Please close this issue if solved.
