### ISSUE TITLE
Win + X + U + (u,s,r,i) not working.

### ISSUE THREAD

**Issue by AverageBlank** [moudey/Shell#436]
Hey, Prior to using nilesoft shell, I used to shutdown my computer using Win + X + u + u,
but this is not working after I have switched to nilesoft shell.
![image](https://github.com/moudey/Shell/assets/112507212/2a2a839a-60c2-4519-a11f-385c276d0f3c)

**Comment by RubicBG** [comment]
os? os build number? do you use additional software to change the Taskbar?

**Comment by AverageBlank** [comment]
Hey! I use explorer patcher to change the taskbar to make it look like the win 10 one, but prior to that as well the shortcut key wasn't working. 
![image](https://github.com/moudey/Shell/assets/112507212/7aed92a9-5367-4c2b-a30d-ee20c63be5ac)

**Comment by RubicBG** [comment]
![image](https://github.com/moudey/Shell/assets/127151533/1c706894-02ef-486e-a7a6-f41fa04ee0f4)
In order for letter navigation to be possible, the underline of the letters must be visible. Use:
```JS
item
{
prefix = 1
}
```
https://nilesoft.org/docs/configuration/themes
By default underlining is activated with Shift key, but in this case you have a combination with WIn key. Thus, underlining will always be displayed on all menus. if you want it to be displayed only in the WIn+X menu, in theory there is a possibility, but I have to experiment first

**Comment by AverageBlank** [comment]
Hey, I have added the given code to shell.nss in C:\Program Files\Nilesoft Shell

It doesn't seem to work, I have re-registered as well as restarted explorer.

**Comment by RubicBG** [comment]
not in shell.nss, you must add the code in imports\theme.nss - keep the structure: https://nilesoft.org/docs/configuration/themes
if you can't get a result, send the theme.nss file, I will edit it and send it back to you

**Comment by AverageBlank** [comment]
Hey, I have tried 2 different methods in the teme.nss, but none of them give me the expected result, here's what I tried.
```
theme
{
	name="modern"
	dark=auto
	background
	{
		color=auto
		opacity=auto
		effect=auto
	}
	image.align=2
}
item
{
prefix = 1
}
```

as well as 

```
theme
{
	name="modern"
	dark=auto
	background
	{
		color=auto
		opacity=auto
		effect=auto
	}
	image.align=2
	item
	{
	prefix = 1
	}
}
```

**Comment by RubicBG** [comment]
the second one has the correct syntax. I tested different situations with different settings, but for me, as soon as prefix=1 everything works as it should

**Comment by AverageBlank** [comment]
Weird, again if explorerpatcher is disabled it seems to be working. 
But as soon as I enable it it stops working. 

Please, let me know if any updates.

**Comment by AverageBlank** [comment]
Hey, upon reinstalling both nilesoft(canary) and explorer patcher, and using the prefix=1, everything is working as expected.
Thank you.
