### ISSUE TITLE
Separate menu options for the Taskbar and Start Menu

### ISSUE THREAD

**Issue by PoloniumRain** [moudey/Shell#439]
NS has the same menu options for both the Taskbar and Start Menu. So all of the Taskbar options are added to the top of the context menu for the Start Button. Because of this some options are duplicated and obviously you cannot customise the menu options for one of them without affecting the other. 

So in my case i have these duplicates (i'm using StartAllBack here)...

![StartMenu](https://github.com/moudey/Shell/assets/50634894/8136fcff-7ee8-4b7b-9475-796e2ca2147c)

The Start Menu should have it's own separate menu options when right clicking on it, just like a stock install of Windows does.

Love this program btw :) I've tried many similar alternatives and NS is the best.

Edit: Oh and there's an [error on your site](https://nilesoft.org/download) with the latest version, under Changes: 

> Version 1.9.15 02/14/2023

Isn't that meant to say 2024?

**Comment by RubicBG** [comment]
The class name for the start button and taskbar are the same for StartAllBack. To avoid this you can add `where=window.parent.name!='Shell_TrayWnd'` as a condition.

open `imports\taskbar.nss` and replace
`where=@(this.count == 0)`
with
 `where=@(this.count == 0) and (window.parent.name!='Shell_TrayWnd')`

**Comment by PoloniumRain** [comment]
Ah so it was StartAllBack causing the issue! And thanks @RubicBG that worked great :)  

Btw i use Start11 V2 on my main Win11 PC, but it has replaced NS with the Start11 context menu on both the Taskbar and Start. 
Is it possible to get the NS menu working on the Taskbar/Start button?

**Comment by RubicBG** [comment]
![image](https://github.com/moudey/Shell/assets/127151533/f0b88eb3-1162-483d-bbaf-0bf1aabae04d)

**Comment by PoloniumRain** [comment]
No idea how i missed that.... 

After doing the above NS will now work on the Taskbar central area, but not the sides of the Taskbar, so it wont work when right clicking on the time/date, notification, volume, and network icons, and the Start Menu. Instead it looks like it's showing the default Windows 11 context menu. 

This is my taskbar.nss file:

```
menu(type="taskbar" vis=key.shift() or key.lbutton() pos=0 title=app.name image=\uE249)
{
	item(title="config" image=\uE10A cmd='"@app.cfg"')
	item(title="manager" image=\uE0F3 admin cmd='"@app.exe"')
	item(title="directory" image=\uE0E8 cmd='"@app.dir"')
	item(title="version\t"+@app.ver vis=label col=1)
	item(title="docs" image=\uE1C4 cmd='https://nilesoft.org/docs')
	item(title="donate" image=\uE1A7 cmd='https://nilesoft.org/donate')
}
menu(where=@(this.count == 0) type='taskbar' image=icon.settings expanded=true)
{
	item(title=title.desktop sep image=icon.desktop cmd=command.toggle_desktop)
	item(title=title.settings image=icon.settings(auto, image.color1) cmd='ms-settings:')
	item(title=title.control_panel image=\uE0F3 cmd='shell:::{5399E694-6CE5-4D6C-8FCE-1D8870FDCBA0}')
	item(title=str.res('regedit.exe,-16') sep=before image cmd='regedit.exe')
	item(title=title.task_manager image=icon.task_manager cmd='taskmgr.exe')
	item(title=title.taskbar_Settings sep=before image=inherit cmd='ms-settings:taskbar')
	item(title='Start11' image=icon.properties cmd='C:\Program Files (x86)\Stardock\Start11\Start11Config.exe') 
	item(vis=key.shift() title=title.exit_explorer cmd=command.restart_explorer)
}
```

**Comment by RubicBG** [comment]
NS can't modify them - they are not shell components

**Comment by PoloniumRain** [comment]
That's a shame. Thanks for all the help, i'll close this now.

**Comment by RubicBG** [comment]
What you described about the work of the NS is completely true. But it's not a "real problem", rather missing futures/functionality.

Starting with Windows 11, Microsoft is trying to replace shell components - in Taskbar, the "modern" context menu, and many others.

One of them is the address bar in Windows Explorer
![image](https://github.com/moudey/Shell/assets/127151533/32c9ac0b-cc90-4dab-88a9-6d950857f8ba)
I was able to edit it and not only with icons, I added more commands. 
![image](https://github.com/moudey/Shell/assets/127151533/689edea1-fc44-4436-b2c1-97c64d4afd23)
I was going to share the information and Microsoft released another update and this is no longer possible, not for Windows 11
![image](https://github.com/moudey/Shell/assets/127151533/8252fa3d-6aac-494b-950c-ece6d5b2f121)
They both look similar, but the "old" menu is made up of 100% shell components that NS can edit them, the "new" menu doesn't use the same components. Тhere are tools on the internet that recognize shell components and give additional information about them - but they don't recognize the "new" menu at all

Тhe above example is easier to explain than the taskbar. The "old" taskbar is made up of different shell components and each has its own menus (This is the ExplorerPatcher win 10 taskbar. The tool recognizes 4 components - marked in a red rectangle and I can even make them invisible temporarily)   
![Recording 2024-03-18 131939](https://github.com/moudey/Shell/assets/127151533/6d06b491-3a19-4eb0-8420-f00e3722d28c)
The "new" Taskbar on Windows 11 is recognized as a single object, and does not use shell components - only a "frame"/container to place the "new" taskbar in place of the "old" taskbar. People complain that Microsoft has cut functionality in Windows 11, but they are rebuilding everything from scratch

moudey has somehow managed to show an editable context menu on the taskbar, but there is still no logic built in how to recognize individual components when they are not shell components

A new version of the NS is being built which will be more flexible, with it there is a greater probability that this will also be achievable. For the moment it is not even an alpha version and nothing can be configured on it yet - nevertheless, moved commands work.
![image](https://github.com/moudey/Shell/assets/127151533/52058cab-fcd4-4b73-8e0f-903090a1d028)

**Comment by PoloniumRain** [comment]
Thanks for taking the time to clearly explain all that. I'm definitely looking forward to that new version of NS, but as MS continue replacing shell components this could be a big problem for NS and similar tools. Hopefully more workarounds are found...

Suppose i'll close this issue again :)
