### ISSUE TITLE
Doesn't replace windows default context menu through file pickers

### ISSUE THREAD

**Issue by ourslfs** [moudey/Shell#44]
Pretty much as the title says

<details><summary>screenshot</summary>
<p>

![image](https://user-images.githubusercontent.com/78319733/194722396-634073d2-1e36-42e6-9469-aa4686685ec6.png)

</p>
</details>

**Comment by moudey** [comment]
Hi @ourslfs, Currently only supports popup menu from processor `explorer.exe`
your popup menu run from processor `SystemSettings.exe > rundll32.exe`

**Comment by moudey** [comment]
Hi @nicholas-ochoa 
Yes, there will be an expansion in the future and it is being worked on carefully to avoid conflict with the addition of exceptions options.

**Comment by moudey** [comment]
Shell has been extended to include system menus that were included by a third party

![MENU-0000000003C21733](https://user-images.githubusercontent.com/39198/199547920-14082eff-6285-4a2a-978f-9a5e8d6863d3.png)

**Comment by moudey** [comment]
Hi @ourslfs, @nicholas-ochoa Please try this [bulld](https://github.com/moudey/Shell/files/10180947/shell-test.zip)

Remove this line or ignor it by add `//`  like this:
```
// exclude.where = !process.is_explorer
```

**Comment by nicholas-ochoa** [comment]
That seems to have fixed the issue, although I can't seem to use my existing configuration with it. Even with a lot of tweaks to fix the errors reported in the log, it seems like the overall syntax has changed?
