### ISSUE TITLE
[Question] Creating File with custom name

### ISSUE THREAD

**Issue by lunatic-gh** [moudey/Shell#443]
I'm wondering... If i use `io.directory.create("SomeName")`, it will open a prompt asking for the name (where `SomeName` is the default input).
Is there something like this for files as well? I'm asking because the default context menu does exactly this for both folders and files, while using `io.file.create("SomeName")` does not open a a prompt at all.

**Comment by RubicBG** [comment]
```JS
item(title='Blank File' image=\uE10E cmd=io.file.create('blank', null, true))
```
or 
```JS
item(title='New File' image=\uE10E cmd=if(input("Nilesoft Shell","new file name...")==1, io.file.create(input.result), msg('no input')))
```

**Comment by lunatic-gh** [comment]
Awesome, thanks!

Additionally, is there any information specifically about what "commands" exist, like for example `io.file.create()`, or are those taken from some specific lang (dotnet or smt)?

**Comment by lunatic-gh** [comment]
NVM, found exactly this on the wiki under "functions". Thanks!
