### ISSUE TITLE
Dual monitor context menu size display abnormally.

### ISSUE THREAD

**Issue by iray1024** [moudey/Shell#448]
### Shell in 1080p monitor:
![shell_1080p_看图王](https://github.com/moudey/Shell/assets/49387318/857a2ff6-87bb-42e0-a365-e1e29aee0fc7)

### Shell in 4k monitor:
![shell_4k_看图王](https://github.com/moudey/Shell/assets/49387318/41dbe09b-8440-4925-91e9-06e2b5de4e93)

### win11 context menu in 1080p monitor:
![win11_1080p_看图王](https://github.com/moudey/Shell/assets/49387318/0fb928f4-8b26-4c9f-9972-87cf10250fa7)

### win11 context menu in 4k monitor:
![win11_4k_看图王](https://github.com/moudey/Shell/assets/49387318/0289c093-7831-41a0-b230-85fe7e4dda62)

Due to image scaling, it may not appear very obvious, but in reality, it is displayed very small on a 4k monitor, while the context menu of Win11 is of the same size.

**By the way**, I am a 1080p resolution laptop connected to a 4k monitor via HDMI

**Comment by RubicBG** [comment]
https://nilesoft.org/docs/configuration/themes
use:
```JS
font 
{
size=if(sys.is_primary_monitor, auto, 20)
}
```
adjust the size by changing the number 20

**Comment by iray1024** [comment]
> https://nilesoft.org/docs/configuration/themes use:
> 
> ```js
> font 
> {
> size=if(sys.is_primary_monitor, auto, 20)
> }
> ```
> 
> adjust the size by changing the number 20

wow, it works well, I think the reason for my problem is that I previously set it to:
font 
{
    size=16
}

thanks RubicBG.

**Comment by iray1024** [comment]
> https://nilesoft.org/docs/configuration/themes use:
> 
> ```js
> font 
> {
> size=if(sys.is_primary_monitor, auto, 20)
> }
> ```
> 
> adjust the size by changing the number 20

wow, it works well, I think the reason for my problem is that I previously set it to:
font 
{
    size=16
}

thanks RubicBG.
