### ISSUE TITLE
[Suggestion] Add Scoop installation instructions to Downloads page and Installation doc.

### ISSUE THREAD

**Issue by Zliced13** [moudey/Shell#45]
Hey @moudey

Do you know about a package manager for Windows 10 & 11 called [Scoop](https://scoop.sh/)?
It's a command line application that allows users to install a wide variety of programs into their system. 
Anyway, Scoop has an app manifest for Nilesoft Shell that allows users of Scoop to install Nilesoft Shell from your website.
You can see right here for yourself: https://scoop.sh/#/apps?q=nilesoft+shell&s=2&d=1&o=true

Scoop installation instructions:
```
scoop bucket add extras
```
```
scoop install nilesoft-shell
```

**Comment by moudey** [comment]
Hi @Zliced13, Thank you for this contribution, I will include this command on download and docs page.

**Comment by Zliced13** [comment]
Your welcome!
