### ISSUE TITLE
Latest shell version no longer respects system theme

### ISSUE THREAD

**Issue by Ravencentric** [moudey/Shell#452]
System:

    Edition: Windows 11 Pro
    Version: 23H2
    Installed on: ‎04-‎09-‎2023
    OS build: 22631.3374
    Experience: Windows Feature Experience Pack 1000.22688.1000.0

Shell version: `1.9.15`

Shell.nss (untouched, default)

    settings
    {
    priority=1
    
    exclude.where = !process.is\_explorer
    
    showdelay = 200
    
    // Options to allow modification of system items
    
    modify.remove.duplicate=1
    
    tip.enabled=true
    }
    
    import 'imports/theme.nss'
    import 'imports/images.nss'
    
    import 'imports/modify.nss'
    
    menu(mode="multiple" title="Pin/Unpin" image=icon.pin)
    {
    }
    
    menu(mode="multiple" title=title.more_options image=icon.more_options)
    {
    }
    
    import 'imports/terminal.nss'
    import 'imports/file-manage.nss'
    import 'imports/develop.nss'
    import 'imports/goto.nss'
    import 'imports/taskbar.nss'

![image](https://github.com/moudey/Shell/assets/78981416/e050a509-c48b-488b-b66f-47c43485f551)

**Comment by RubicBG** [comment]
https://github.com/moudey/Shell/issues/435
https://github.com/moudey/Shell/issues/412
https://github.com/moudey/Shell/issues/418
