### ISSUE TITLE
File browser crashes when right-clicking the quick access button

### ISSUE THREAD

**Issue by speedlorenzo12** [moudey/Shell#456]
right clicking on a quick access file shows me the classic right button and after 5 seconds it crashes the file explorer and reloads it
win 11: 23h2 22631.3447
shell canary:1.9.14 (If you want more information I'll gladly give it to you)

**Comment by RubicBG** [comment]
can you take a screenshot of "quick access"

**Comment by speedlorenzo12** [comment]
I dont have time to take the schreenshot

**Comment by speedlorenzo12** [comment]
https://th.bing.com/th/id/R.720671ae8fe0e01b8cb16264ada8447f?rik=1a3%2fm%2b2V2qAnCg&pid=ImgRaw&r=0&PC=EMMX01

**Comment by RubicBG** [comment]
I have not encountered such a problem. But your explorer is not the standard one for Windows 11 either.
- which program did you use to tweak the explorer?
- does the problem occur on all of the "quick access" items or only some? What about the "Acceso rápido"?
- take a screenshot of the content menu without NS

**Comment by speedlorenzo12** [comment]
![Screenshot 2024-04-13 1254342](https://github.com/moudey/Shell/assets/111771663/19e0b9ea-b32e-44d9-9609-a334491e03ca)
(whit all of this part)

**Comment by RubicBG** [comment]
- check shell.log - if there is an error described, share it
- edit the shell.nss file with this:
```JS
settings
{
priority=1
exclude.where = !process.is_explorer
showdelay = 200
}
import 'imports/images.nss'
```
This will reduce the use of all secondary functions - write if the problem is still there. Don't forget to make a copy of shell.nss to restore it back.

**Comment by speedlorenzo12** [comment]
I discovered before it is most likely a Windows 11 problem, given that when I click, it shows other options the same problem happens
![IMG_20240416_193019.jpg](https://github.com/moudey/Shell/assets/111771663/dcb7e34a-ec85-4df6-b623-a772f7f4fd39)

**Comment by speedlorenzo12** [comment]
I tried autoruns to solve the problem, and I found the cause, it is a service called NVIDIA Display Shell Extension, what could I do to solve this service too? reviewing things in general, the strange thing is that the service is from nvidia and I use radeon, probably the software was not uninstalled and was causing the problem, thanks for the support
