### ISSUE TITLE
Better Customization?

### ISSUE THREAD

**Issue by keplerHaloxx** [moudey/Shell#462]
The way to customize the app is really annoying and I'd rather not go through the effort. Could there not be an options place where you can toggle on and off different features? Also it automatically defaults to the Windows 10 context menu items but with the Windows 11 look - I don't understand why. I like the Windows 11 one way more and I want to keep it as that but with some extra features that I want to add.

**Comment by Dev123456689** [comment]
This can be solved by offering some pre-installed themes to choose from and giving a gui for tinkering some basic options such as fonts, font color, background color, border color, opacity, etc. 
**Note:** i am not a dev working on Nilesoft Shell, just a Nilesoft Shell user suggesting solutions to the devs.

**Comment by RubicBG** [comment]
there is a settings/theme manager, it's not perfect but it works
![image](https://github.com/moudey/Shell/assets/127151533/5081dba6-ed8e-45d4-bafb-3b05228f7cbf)
download from here:
https://discord.com/channels/1106387012707168318/1139275510506082336/1155924668914610187
install info:
https://discord.com/channels/1106387012707168318/1139275510506082336/1179379922297430077

when it comes to the functional part - It is possible to make a simple GUI command builder, but it will only be able to create commands, not а menu. It is not possible to make an editor that recognizes the syntax - once the commands are created, they must be manually edited.

**Comment by Crocodile73** [comment]
is there a working link for this?

**Comment by RubicBG** [comment]
> is there a working link for this?

I can upload the file over the weekend.

**Comment by RubicBG** [comment]
https://github.com/RubicBG/Nilesoft-Shell-Snippets-Collections/blob/main/theme-manager.nss
