### ISSUE TITLE
[Website] Google Safe Browsing report

### ISSUE THREAD

**Issue by bivashy** [moudey/Shell#466]
Google Safe Browsing probably reported https://nilesoft.org as unsafe.

I've created this issue because I've not found similar reports, and wanted to inform the project maintainer.

Info from: https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fnilesoft.org%2F&hl=en
![image](https://github.com/moudey/Shell/assets/85439143/300e0a66-f2a6-4cb1-acc8-3e571069e9da)

Please contact Google Safe Browsing to avoid losing visitors.

**Comment by moudey** [comment]
So nilesoft.org was blocked out of the blue for imaginary malware reasons and of course there is no human support at Google. Any tips?

**Comment by znbaboy** [comment]
> So nilesoft.org was blocked out of the blue for imaginary malware reasons and of course there is no human support at Google. Any tips?

They support Palestine. Thats the tip

**Comment by moudey** [comment]
> They support Palestine. Thats the tip\n\nWonder if they were hacked

All the free people of the world support Palestine and reject genocide, and we will remain so forever and we will not forget.

**Comment by bivashy** [comment]
Update 
![IMG_20240515_132002](https://github.com/moudey/Shell/assets/85439143/1d597466-6807-40f2-8932-e0a85b34e20d)
