### ISSUE TITLE
How can I delete the delete option in the context menu

### ISSUE THREAD

**Issue by dentistfrankchen** [moudey/Shell#474]
I want to hide the "delete" option in context menu, how can I do this?

**Comment by dimateos** [comment]
There might be a way to do it by using non languange dependant strings, but you can match anything with "find"

For example in spanish:

    remove(find = '"Copiar"')
    remove(find = '"Cortar"')
    remove(find = '"Pegar"')
    remove(find = '"Abrir"')
    remove(find = '"Editar"')
    remove(find = '"Eliminar"')
    remove(find = '"Cambiar nombre"')
    
 Those are exact matches due to the "", drop them for partial matches,.
 You can also use wildcards with "*"
