### ISSUE TITLE
How would I add a menu option that allows for creating file hashes?

### ISSUE THREAD

**Issue by Zliced13** [moudey/Shell#48]
Hello there!

I would like to be able to add a file-hashing submenu into the Nilesoft context menu, specifically below the **file manage** submenu. How would I do that?
![image_9](https://user-images.githubusercontent.com/101912712/198189881-32aa849c-fe81-4224-8431-7ba36e6d0f30.png)

Also, which programming language should I use for **shell.shl**? I am having a hard time understanding how everything works here, C# seems to be only working one for me currently.
![(VSCodium)R403U2_10-26-2022](https://user-images.githubusercontent.com/101912712/198191554-c970f478-1dd2-45f9-98fa-1e4164be7e26.jpg)

**Comment by moudey** [comment]
>I would like to be able to add a file-hashing submenu into the Nilesoft context menu, specifically below the file manage submenu. How would I do that?

Put this code after a"file manage"
```
menu(title="file-hashing")
{
    item(title="md5" cmd='md5 command')
    item(title="sha1" cmd='sha1 command')
    item(title="sha256" cmd='sha256 command')
}
```

>Also, which programming language should I use for shell.shl? I am having a hard time understanding how everything works here, C# seems to be only working one for me currently.

Shell has a very simple script to make it flexible in handling and it's a bit like javascript, C#, C/C++

**Comment by Zliced13** [comment]
Thank you @moudey. This helped me by a lot, have a great day.
