### ISSUE TITLE
Can i remove system options?

### ISSUE THREAD

**Issue by not-nef** [moudey/Shell#49]
I want to have a clean context menu with only the things i need. Can i remove system options such as View, Sort by and group by with shell? I think these are system options because i couldnt find them in shell.shl.

**Comment by moudey** [comment]
Yes, you can remove or modify any menu item
```
static
{
    item(find='view' vis=remove)
    // or remove multiple items by one line
    item(find='view|sort by|group by' vis=remove)
}
```

**Comment by not-nef** [comment]
Thank you! 🙏🙏🙏
