### ISSUE TITLE
Disable corner rounding

### ISSUE THREAD

**Issue by ReginaLain** [moudey/Shell#490]
Hey, everybody. Can you tell me how to remove the rounded edges of the context menu? I use version 1.9.15
I found a theme from 2022, but when I try to copy text from there to the configuration file, I get the standard Windows 10 menu.

**Comment by moudey** [comment]
```js
theme
{
    border.radius = 0
}
```

**Comment by ReginaLain** [comment]
Thank you, that's just what I need.
![Screenshot 2024-07-20 161815](https://github.com/user-attachments/assets/8b518389-df4c-45e6-976c-f52496c94aaf)
