### ISSUE TITLE
[Fixed in 1.9.17] Taskbar context menu titles are broken on Windows 11 Dev 26120.1252

### ISSUE THREAD

**Issue by CatPieLeaf** [moudey/Shell#495]
# Fixed in Canary version 1.9.17.
### Update your Nilesoft shell to get this fixed.

![image](https://github.com/user-attachments/assets/b0d39fb9-06d2-42b3-8e68-6402dda89edb)

Some text is missing on nilesoft shell taskbar context menu in Windows 11 24H2 Insider (Dev channel) 26120.1252

# Updated temporary workaround:
Thanks to RubicBG

> (change your taskbar.nss to this)

```
menu(type="taskbar" vis=key.shift() or key.lbutton() pos=0 title=app.name image=\uE249)
{
	item(title="config" image=\uE10A cmd='"@app.cfg"')
	item(title="manager" image=\uE0F3 admin cmd='"@app.exe"')
	item(title="directory" image=\uE0E8 cmd='"@app.dir"')
	item(title="version\t"+@app.ver vis=label col=1)
	item(title="docs" image=\uE1C4 cmd='https://nilesoft.org/docs')
	item(title="donate" image=\uE1A7 cmd='https://nilesoft.org/donate')
}
menu(where=@(this.count == 0) type='taskbar' image=icon.settings expanded=true)
{
	menu(title="Apps" image=\uE254)
	{
		item(title='Paint' image=\uE116 cmd='mspaint')
		item(title='Edge' image cmd='@sys.prog32\Microsoft\Edge\Application\msedge.exe')
		item(title='Calculator' image=\ue1e7 cmd='calc.exe')
		item(title=str.res('regedit.exe,-16') image cmd='regedit.exe')
	}
	menu(title='Windows' image=\uE1FB)
	{
		item(title='Cascade' cmd=command.cascade_windows)
		item(title=str.res('C:\Windows\explorer.exe', -538) cmd=command.Show_windows_stacked)
		item(title=str.res('C:\Windows\explorer.exe', -536) cmd=command.Show_windows_side_by_side)
		sep
		item(title=str.res('C:\Windows\explorer.exe', -537) cmd=command.minimize_all_windows)
		item(title='Restore all windows' cmd=command.restore_all_windows)
	}
	item(title=title.desktop image=icon.desktop cmd=command.toggle_desktop)
	item(title=title.settings image=icon.settings(auto, image.color1) cmd='ms-settings:')
	item(title=str.res('C:\Windows\explorer.exe', -22001) sep=both image=icon.task_manager cmd='taskmgr.exe')
	item(title='Taskbar settings' sep=both image=inherit cmd='ms-settings:taskbar')
	item(vis=key.shift() title='Exit Explorer' cmd=command.restart_explorer)
}
```

Nilesoft shell is just failing to get the text for the entries. these settings just apply the text to the entries manually.

**Comment by win98se** [comment]
Can confirm on 26100.1297.

**Comment by CatsArmy** [comment]
Can confirm as well I suspect it could be that window changed the internal name of those names

**Comment by CHminggao** [comment]
same on 26100.1301

**Comment by RubicBG** [comment]
can someone upload "C:\Windows\System32\shell32.dll" and "C:\Windows\explorer.exe"

**Comment by CatPieLeaf** [comment]
> can someone upload "C:\Windows\System32\shell32.dll" and "C:\Windows\explorer.exe"

[shell32+explorer.zip](https://github.com/user-attachments/files/16493980/shell32%2Bexplorer.zip)

**Comment by RubicBG** [comment]
> 26120.1330

and this one pls "C:\Windows\en-US\explorer.exe.mui"

**Comment by ararezaee** [comment]
[explorer files.zip](https://github.com/user-attachments/files/16532973/explorer.files.zip)


> and this one pls "C:\Windows\en-US\explorer.exe.mui"

There you go both files from 26100.1301 which has the same issue

**Comment by RubicBG** [comment]
all 71 ids responsible for Windows 10 and 11 taskbar context menu names have been removed. 
even though the names don't come out, do the commands all execute?
```item(title=str.res('C:\Windows\explorer.exe', -535))
item(title=str.res('C:\Windows\explorer.exe', -536))
item(title=str.res('C:\Windows\explorer.exe', -537))
item(title=str.res('C:\Windows\explorer.exe', -538))
item(title=str.res('C:\Windows\explorer.exe', -22001))
```
![image](https://github.com/user-attachments/assets/ab46bef6-5a70-47b8-91cc-2bdd0a432b5a)
Only those names can be retrieved under those ids. Regardless of whether there is a name/text match these are not the names of the commands ("Show windows side by side" not the same as "Show windows s&ide by side")

**Comment by CatPieLeaf** [comment]
![image](https://github.com/user-attachments/assets/f74eae8e-392b-40c8-9ccc-fd9cf3e45f69)

**Comment by CatsArmy** [comment]
Yeah they work just no name really weird choice form Microsoft with all the talk about backwards compatibility

**Comment by moudey** [comment]
This issue has been fixed in [Canary version 1.9.17](https://nilesoft.org/download#canary) with an fallback title.

**Comment by CatPieLeaf** [comment]
1.9.17 not pushed yet? latest canary still 1.9.16

**Comment by CatsArmy** [comment]
Nope I have . 17 don't know why it don work for you

**Comment by henk911** [comment]
same here

**Comment by Tetroner9** [comment]
Task Manager text missing even after applying the taskbar.nss edit by @RubicBG
