### ISSUE TITLE
Taskbar right-click

### ISSUE THREAD

**Issue by AulysV** [moudey/shell#5]
Hello, when I right click on an app opened in the taksbar, it opens de Shell contrext menu... It doesn't show the "Close app" button. Maybe it can be a new feature.

**Comment by moudey** [comment]
> Hello, when I right click on an app opened in the taksbar, it opens de Shell contrext menu... It doesn't show the "Close app" button. Maybe it can be a new feature.

Shell should not appear in the area between the start button and open programs.
Please attach a screenshot of this issue and tell us which version of Windows you are using.

Thanks

**Comment by moudey** [comment]
Hello @AulysV
Is this issue still with you?

**Comment by AulysV** [comment]
Hello,

Sorry, I didn’t see your reply.
The issue seems to be fixed

Thanks,

Aulys

De : Mahmoud ***@***.***>
Envoyé le :lundi 13 juin 2022 13:48
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [moudey/shell] Taskbar right-click (Issue #5)


Hello @AulysV<https://github.com/AulysV>
Is this issue still with you?
