### ISSUE TITLE
`modify` does not work for symlinks

### ISSUE THREAD

**Issue by LucasOe** [moudey/Shell#531]
Modifying items using `modify` does not work for symlinks.

# Steps to reproduce

1. Create a symlink for a file
2. Add `modify(where=this.id(id.send_to) vis=vis.remove)` to your `shell.nss`
3. Reload the context menu using `Ctrl+Right Click` or by restarting the Explorer
4. Open the context menu for the symlink. "Send To" is still visible

The same probably applies to hard links and junctions, but I haven't tested this.

**Comment by RubicBG** [comment]
NS has a number of standardized types it works with: https://nilesoft.org/docs/configuration/properties#type. When you don't specify the type NS works with the default ones: File Dir Drive Namespace. Symbolic link do not fall into any of the standard types

use: 
```modify(where=this.id(id.send_to) type='*' vis=vis.remove)```
or a short syntax:
```remove(where=this.id(id.send_to) type='*')```

**Comment by LucasOe** [comment]
@RubicBG Thanks, I didn't know this, that resolves my problem!
