### ISSUE TITLE
Question regarding PR review process

### ISSUE THREAD

**Issue by Nagidrop** [moudey/Shell#551]
I have been Nilesoft Shell user for quite some time. It has saved me from the sluggish Windows defaults, drastically enhanced my experience and boosted my productivity through customizations. I'm so grateful that you made this wonderful software free to use without any charges :D

Lately I noticed it has been open-sourced for almost a year. With a quick glimpse through the PRs, I promptly spotted these 2 conflicting ones that you merged without comments: [#529](https://github.com/moudey/Shell/pull/529/commits/6f865d38980c797c213d26c2b57c5fa65f94452e) and [#530](https://github.com/moudey/Shell/pull/530/commits/180283d07d2c9080da88a04f374874a84f98bed7). It seems that you merged these without reviewing. If it keeps on occuring, I'm concerned about Shell's quality being degraded in the long run.

As a loyal user and supporter of Shell project, I want to raise and make aware of this issue, to help Nilesoft Shell development and ensure it isn't stalled or degraded after merging new PRs. I would love to hear your thoughts :D

**Comment by moudey** [comment]
Hi @Nagidrop, Thank you for your interest and concern. Editing configuration files for other languages has not been reviewed yet. However, this issue has been overcome in version 1.9.19 now that the language has been separated from the configuration file code, which will make it easier to add other languages without editing the configuration file.

**Comment by Nagidrop** [comment]
> Hi @Nagidrop, Thank you for your interest and concern. Editing configuration files for other languages has not been reviewed yet. However, this issue has been overcome in version 1.9.19 now that the language has been separated from the configuration file code, which will make it easier to add other languages without editing the configuration file.

Sounds great. I'd love to see further development, and contribute when possible.
