### ISSUE TITLE
see more (...) in file explorer always extends to top

### ISSUE THREAD

**Issue by roubilibo** [moudey/Shell#557]
hi.
I don't know if this is a bug from nilesoft shell or from windows 11 24h2 but the appearance of my file explorer becomes like this after the update
![image](https://github.com/user-attachments/assets/1fb2b51f-fc01-48ae-b283-df9a0341cd43)

thx

**Comment by RubicBG** [comment]
I had it at first, but it went away on its own - I guess Microsoft fixed it with an update.

**Comment by roubilibo** [comment]
Thanks a ton! Now I can finally sleep without my brain pulling an all-nighter. 😄
