### ISSUE TITLE
Unable to Convert String to Integer

### ISSUE THREAD

**Issue by Edwinfitz** [moudey/Shell#558]
Hi,

I can't seem to figure out how to convert a string into an integer.

I've poured through the documentation and tried every trick I could think of,
but integers always seem to be converted to a string, rather than the other way round.

In my specific case I am trying to pass the values given from **regex.matches** to **color.rgba**. Let's say
the values **'23'**, **'48'**, and **'128'** as an example. In theory this would work great, but seemingly
because regex returns strings, **color.rgba** cannot process them, and in turn makes the background black.

Any second opinions on this issue would be a great help.

I apologize in advance if this is the incorrect place to ask this kind of question.

Thanks.
```
theme
{
	// theme.name = auto, classic, white, black, or modern
	name = "modern"

	// view = auto, compact, small, medium, large, wide
	view = view.small
	dark = !reg.get('HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize', 'SystemUsesLightTheme')

	$bgColor = reg.get('HKCU\Control Panel\Colors', 'Window')
	$bgColorRGB = regex.matches(bgColor, '[0-9]{1,3}')

	background
	{
		color = color.rgba(bgColorRGB[0], bgColorRGB[1], bgColorRGB[2], 255)
		opacity = 100
		effect = 0
	}
}
```

**Comment by RubicBG** [comment]
`toint`
```js
theme.background.color = color.rgba(toint(bgColorRGB[0]), toint(bgColorRGB[1]), toint(bgColorRGB[2]), 50)
```
also the fort parameter is `alpha`: 0-100

**Comment by Edwinfitz** [comment]
This works perfectly. Thanks for your help.
