### ISSUE TITLE
Explorer Cpu usage spikes up and fan ramps up.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [moudey/Shell#56]
I had to open shell as admin and click restart Explorer.

**Comment by moudey** [comment]
What is the version used?  Do you find high consumption in the explorer processor?

**Comment by PhoenixCODE2322** [comment]
> What is the version used? Do you find high consumption in the explorer processor?

v 1.7 , got it from winget. Yes the explorer process is causing the issue.

**Comment by moudey** [comment]
This issue has been fixed in version 1.8 beta.
Please refer this [topic](https://github.com/moudey/Shell/issues/37)

**Comment by PhoenixCODE2322** [comment]
ok , will do
