### ISSUE TITLE
Theme Not applying correct

### ISSUE THREAD

**Issue by Crocodile73** [moudey/Shell#566]
Been using this in the theme.nss for ages. Just changing the colours when needed. No ideal what is going on now, if its windows update or what, but it displays wrong in 1.9.15 now, and not at all in 1.9.18.

Solved for 1.9.15

**Comment by PsychoticChemist** [comment]
How did you solve it? Here's a link to my issue post, was your problem similar to mine? https://github.com/moudey/Shell/issues/659
