### ISSUE TITLE
Latest version 1.9.18 blocked by Windows Security

### ISSUE THREAD

**Issue by philberndt** [moudey/Shell#567]
Downloaded from the web https://nilesoft.org/download version 1.9.18 is blocked by Windows Security

> Detected: Trojan:Win32/SuspExecRep.A!cl
> Status: Removed
> Date: 28.11.2024 10:31
> Details: This program is dangerous and executes commands from an attacker.
> Affected items:
> file: C:\Users\Phil\Downloads\setup-x64.msi
> webfile: C:\Users\Phil\Downloads\setup-x64.msi|https://nilesoft.org/download/shell/1.9.18/setup-x64.msi|pid:7648,ProcessStart:133772599119056218

Tried installing with winget and my PC restarted automatically.
```

Name           Id             Version Source
---------------------------------------------
Nilesoft Shell Nilesoft.Shell 1.9.18  winget
```

Canary version is version 1.9.18 also downloaded from https://nilesoft.org/download does not trigger Windows Security.

**Comment by jmwatte** [comment]
Same thing here. Even after Winget uninstall and install. Getting it straight from the website and Windows Security blocks it.

**Comment by jmwatte** [comment]
is fixed now.

**Comment by xsm2** [comment]
@philberndt If the problem is resolved you should close the issue

**Comment by philberndt** [comment]
Fixed.
