### ISSUE TITLE
Right click or opening something in taskbar explorer restarting automatically 

### ISSUE THREAD

**Issue by droosmo** [moudey/Shell#57]
When i try to open my pinned apps in taskbar or i try to right click in taskbar for task manager the explorer restart automatically!!

**Comment by moudey** [comment]
What is the version of Shell and the version of Windows and do you use other programs to modify the taskbar?

**Comment by droosmo** [comment]
> What is the version of Shell and the version of Windows and do you use other programs to modify the taskbar?

Shell version 1.7
Windows 11 22H2 build 22621.819

**Comment by moudey** [comment]
@droosmo 

Do you use other tools to modify the taskbar?

> Shell version 1.7

Please try version 1.8 beta .

**Comment by moudey** [comment]
اخي ادريس هناك تحسينات في اصدار 1.8 بيتا ارجوا تجربتها. يفضل التجربة في Windows Sandbox

**Comment by droosmo** [comment]
> اخي ادريس هناك تحسينات في اصدار 1.8 بيتا ارجوا تجربتها. يفضل التجربة في Windows Sandbox

حسنا اخي محمود سوف اجربها وشكرا جزيلا لك على حسن المعاملة وايضا على تطويرك لهذا البرنامج الرائع يومك سعيد 😊

**Comment by NetBod** [comment]
HI, I have this same issue, started a few window ver updates ago. Shell ver 1.8 in use.  Confirmed if I unregister Shell the issue does not occur. Do not use anything else to modify the task bar. Win ver 22H2 (OS Build 25247.1000)

**Comment by moudey** [comment]
@droosmo  @NetBod Please try this [build](https://github.com/moudey/Shell/files/10098525/shell.zip)

**Comment by moudey** [comment]
@NetBod Do you use taskbar modification software?

**Comment by NetBod** [comment]
HI, As I already said no do not use any taskbar modification software, just run up a Windows sandbox and test 1.7 - 1.8 and the test build happens in all 3 the test build one is un-usable as it just keeps restarting explorer all the time. Also, windows did an update ion reboot of main PC (and in sandbox)  to version 22H2 (OS Build 25252.1000) and problem still happens.

**Comment by moudey** [comment]
@droosmo, @NetBod Please test this [build](https://github.com/moudey/Shell/files/10127710/shell-test.zip)

**Comment by NetBod** [comment]
Hi, tried this new build on normal PC I use and it is a lot better, but problem still happening, but longer time between explorer restarting, seen explorer restart on both right and left hand mouse clicks on the task bar or icon in the task bar. Not tried it a Window Sandbox yet, will try and test in that tomorrow and update.

**Comment by dillan4561** [comment]
> @droosmo, @NetBod Please test this

im also getting the same issue, and this does not help it, still crashing immediatly after the 2nd click of right clicking or left clicking,

if you right click the taskbar to get the menu then go off the taskbar and then go back on it and right click again the whole explorer crashes, and it does it every single time,

**Comment by moudey** [comment]
> > @droosmo, @NetBod Please test this
> 
> im also getting the same issue, and this does not help it, still crashing immediatly after the 2nd click of right clicking or left clicking,
> 
> if you right click the taskbar to get the menu then go off the taskbar and then go back on it and right click again the whole explorer crashes, and it does it every single time,

I upgraded Windows to the latest version 25252.1010 and the issue appeared

**Comment by moudey** [comment]
@droosmo, @NetBod , @dillan4561 Please try [this](https://github.com/moudey/Shell/files/10142067/shell-test.zip)

**Comment by dillan4561** [comment]
> @droosmo, @NetBod , @dillan4561 Please try [this](https://github.com/moudey/Shell/files/10142067/shell-test.zip)

This fixes it completely for me,

Thanks

**Comment by NetBod** [comment]
Hi, sorry never time to run in Sandbox, but the new build you posted appears to be all OK, but why is the new version not reading the .shi cfg file, it reads the. NSS cfg file. and if I put my config in that nss file it fails to load with an error Invalid config file message in the log.

**Comment by moudey** [comment]
>@NetBod but why is the new version not reading the .shi cfg file, it reads the. NSS cfg file. and if I put my config in that nss file it fails to load with an error Invalid config file message in the log.

Ext of config file has been changed to `NSS`. New changes only in `default` section. It will be explained in the documentation with the next release.
