### ISSUE TITLE
help,what are the shutdown and restart commands?

### ISSUE THREAD

**Issue by Tgkkez** [moudey/Shell#576]
item(title='关机' image=\uE12F cmd='C:\Windows\System32\shutdown.exe -s -t 0')
item(title='重启' image=\uE1DB cmd='C:\Windows\System32\shutdown.exe -r -t 0')
I want to add shutdown and restart commands in the taskbar, I use cmd command, but it doesn't work, I want to know in this software to shut down and restart the system is what command, thank you

**Comment by Tgkkez** [comment]
I want to know the command of shut down, restart, sleep, hibernate

**Comment by RubicBG** [comment]
```js
// try
cmd='C:\Windows\System32\shutdown.exe' args='-r -t 0')
// or
cmd='shutdown.exe'  args='-r -t 0')
```
https://discord.com/channels/1106387012707168318/1233094583953653830/1233094583953653830

**Comment by Tgkkez** [comment]
> ```js
> // try
> cmd='C:\Windows\System32\shutdown.exe' args='-r -t 0')
> // or
> cmd='shutdown.exe'  args='-r -t 0')
> ```
> 
> https://discord.com/channels/1106387012707168318/1233094583953653830/1233094583953653830

It works! However, I have a network problem here and it is not convenient to connect to discord, thank you very much, this software is very useful and has solved many problems for me!
