### ISSUE TITLE
OneDrive - Locations Incorrect

### ISSUE THREAD

**Issue by Sp5rky** [moudey/Shell#58]
Shell Version: 1.7
Windows Version: Win 11 21H2
OneDrive Version: Build 22.227.1030.0001 (64-bit)

I noticed when trying to make a OneDrive location saved locally on my machine that the location of "Always keep on this device" it's under the More Options while the Free up Space/View Online have their own section also missing icons compared to Original Windows 11 Context menu.

![context](https://user-images.githubusercontent.com/29722511/202913496-37372361-9297-4b77-a44a-965ac673d79a.png)
![context2](https://user-images.githubusercontent.com/29722511/202913497-b84f3219-20b0-433b-bbe6-3d40d25a6fbc.png)
![context3](https://user-images.githubusercontent.com/29722511/202913951-3a11c9d8-93f0-475b-b06d-f80757c09c6e.png)

**Comment by moudey** [comment]
OneDrive menu items in the classic context menu do not have an icon.
But you can assign an icon to each item through this example
```
static
{
	item(find='free up space' image=\uE09C)
	item(find='always keep on this device' image=\uE09D)
}
```
![onedrive](https://user-images.githubusercontent.com/39198/202915344-df512312-40c8-4aed-802b-9353aac0b49b.png)

**Comment by Sp5rky** [comment]
That's great, Worked perfectly.

However due to this line `item(where=this.title.len > 20 tip=this.title parent=@id.more_options.title)` the context item is being moved commenting out this gets it to display correct. What's the best way to find the title.id so I can filter out the "always keep on this device"

```
item(find='free up space' image=\uE09C)
item(find='always keep on this device' image=\uE09D parent=?)
item(find='view online' image=\uE09C)
```

![image](https://user-images.githubusercontent.com/29722511/202920551-9b4e3ecf-403c-4768-8a44-54547494cef3.png)

**Comment by moudey** [comment]
Skip "always keep on this device" item
```
item(where=this.title.len > 20 && this.title != "always keep on this device" 
    tip=this.title parent=@id.more_options.title)
```

These items can be moved to a special OneDrive submenu
```
item(find='"free up space"|"view online"|"always keep on this device"' parent="OneDrive")
item(find='"OneDrive"' image=image=\uE09D sep)
```

**Comment by Sp5rky** [comment]
!= works perfectly, however, the second batch of code seems to not load the shell anymore and reverts to old context menu.

**Comment by moudey** [comment]
> != works perfectly, however, the second batch of code seems to not load the shell anymore and reverts to old context menu.

correct code
```
item(find='"OneDrive"' image=\uE09D sep)
```
