### ISSUE TITLE
Where to find all the glyphs addresses? 

### ISSUE THREAD

**Issue by Marvinoo** [moudey/shell#6]
- So I want to assign some of these beautiful [icons/glyphs](https://github.com/moudey/shell/raw/main/templates/themes/images/columns.png) for my customized menu items but I don't know how to address them? Not in the documentation.
- The option ['glyph explorer'](https://i.imgur.com/d7dcq5d.png) does not exist in my Shell menu of taskbar? 
- I noticed that Shell does not affect some of the default Windows menus (i.e. [Right-click menu on the explorer's top controls bar](https://i.imgur.com/IvDv7m7.png), Context menus of the address bar [1](https://i.imgur.com/E9NRNkj.png) & [2](https://i.imgur.com/LcRkdbi.png). So are there any plans to cover such menus in the future? 

Thank you.

**Comment by moudey** [comment]
• I will make a gallery of glyphs soon so you can choose the icons.

For now you can refer to the glyph template in this [link](https://github.com/moudey/shell/blob/main/templates/glyphs.shl)

• You can copy the glyph template to shell.shl for it to work.

• Currently main explorer and taskbar context menus are supported. There are plans to include all the explorer context menus with more options for filtering by window type.

**Comment by moudey** [comment]
There is a glyphs embedded in the shell that are used on supported versions of Windows that are used by default .

More about glyphs [Segoe MDL2 Assets](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font), [Segoe Fluent Icons](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font)

Use other external glyphs You can use this function
```
image.glyph(\uE006, "Segoe Fluent Icons")
image.glyph(\uE006, #f00, "Segoe MDL2 Assets")
```

**Comment by Marvinoo** [comment]
Pardon my limited understanding for this matter.
So I followed this [link](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font) and intended to use that great set of glyphs but I don't seem to understand how to make them work. 
So first, I [downloaded the font](https://download.microsoft.com/download/8/f/c/8fc7cbc3-177e-4a22-af48-2a85e1c5bffb/Segoe-Fluent-Icons.zip), installed it on my Win10 and tried to use the [unicode points](https://i.imgur.com/SbRA6NY.png) inside of my Shell.shl to show the relevant icons in my windows context menu but failed to do that. 

So once and for all, please show me _by code snippet_ as an example how to replace that [default 'Refresh' icon](https://i.imgur.com/iIz5GBO.png) from Shell by the ['Sync' icon from Segoe Fluent Icons?](https://i.imgur.com/WOp5t9d.png)

I'll use your snippet as a template guide to make any other icon changes. Thanks a lot in advance.

**Comment by moudey** [comment]
Sorry, there is an issue that default shell glyphs skip user entered fonts, corrected with addition of image.fluent and image.mdl shortcut function,

```
static 
{
    item(where=@(this.id == id.refresh) image=@image.glyph(\uE895, "Segoe Fluent Icons"))
    item(where=@(this.id == id.refresh) image=image.glyph(\uE895, #f00, "Segoe MDL2 Assets"))

    //or

    item(where=@(this.id == id.refresh) image=@image.fluent(\uE895))
    item(where=@(this.id == id.refresh) image=@image.mdl(\uE895))

    //or
    //This function gives priority to "Segoe Fluent Icons" if present then "Segoe MDL2 Assets"
    item(where=@(this.id == id.refresh) image=@image.segoe(\uE895) ) 
}
```

This update will be released this week.

**Comment by moudey** [comment]
Glyphs issue fixed, and support for most File Explorer context menus.

**Comment by moudey** [comment]
> Pardon my limited understanding for this matter. So I followed this [link](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font) and intended to use some of that great set of glyphs but I don't seem to understand how to make them work. So first, I [downloaded the font](https://download.microsoft.com/download/8/f/c/8fc7cbc3-177e-4a22-af48-2a85e1c5bffb/Segoe-Fluent-Icons.zip), installed it on my Win10 and tried to use the [unicode points](https://i.imgur.com/SbRA6NY.png) inside of my Shell.shl to show the relevant icons in my windows context menu but failed to do that.
> 
> So once and for all, please show me _by code snippet_ as an example how to replace that [default 'Refresh' icon](https://i.imgur.com/iIz5GBO.png) from Shell by the ['Sync' icon from Segoe Fluent Icons?](https://i.imgur.com/WOp5t9d.png)
> 
> I'll use your snippet as a template guide to make any other icon changes. Thanks a lot in advance.

@Marvinoo You can now change the icon of the refresh item through the following functions

```
shell {
    static {
        // by built-in glyphs
        item(where=@(this.id == id.refresh) image=\uE1AB))
        // or
        item(where=@(this.id == id.refresh) image=@image.segoe(\uE895))
    }
}
```

Work is currently underway to create a gallery of embedded glyphs.

**Comment by moudey** [comment]
@Marvinoo You can now explore glyphs through [this ](https://nilesoft.org/gallery/glyphs) link
