### ISSUE TITLE
Missing glyphs? Please help

### ISSUE THREAD

**Issue by xarathos517** [moudey/Shell#60]
I'm at my wits end trying to troubleshoot this on my own so I figured I'd just ask if anybody has any ideas. The glyphs don't appear to work for me at all. 

![image](https://user-images.githubusercontent.com/27585237/204107414-8cd26ae7-009b-4fec-a797-4a2ed32a9875.png)

Running 1.7 stable, but I tried the beta and it didn't make any difference for me. I know it's probably something really dumb on my end, I've just run out of ideas for things to try. Thanks in advance for any help.

**Comment by moudey** [comment]
What version of Windows are you using?

**Comment by xarathos517** [comment]
Windows 11 Pro 21H2

**Comment by moudey** [comment]
Uninstall Shell and restart Windows. Then install it again.

Do glyphs appear in Shell window?

**Comment by xarathos517** [comment]
Uninstalled, rebooted, checked again. They do not, no. Didn't before either, in either version.

![image](https://user-images.githubusercontent.com/27585237/204109852-bcd9ad27-3964-4b24-9b0b-45bcc82d0502.png)

**Comment by moudey** [comment]
Please Try it in Windows Sandbox

**Comment by xarathos517** [comment]
Problem persists in the Sandbox environment. 

![image](https://user-images.githubusercontent.com/27585237/204110763-23c13f7f-d32b-43cf-861b-7d00e931845f.png)

**Comment by spaceCabbage** [comment]
i just installed on win11 22h2 and im getting the same bug

**Comment by moudey** [comment]
@xarathos517  @spaceCabbage 
Please try this [build](https://github.com/moudey/Shell/files/10098507/shell.zip)

**Comment by spaceCabbage** [comment]
![image](https://user-images.githubusercontent.com/85190787/204141085-20d677ea-57ba-4ce6-82e7-2226161cb4ad.png)
got this error when trying to extract, wont work with winrar either

**Comment by moudey** [comment]
[shell.zip](https://github.com/moudey/Shell/files/10098525/shell.zip)

**Comment by spaceCabbage** [comment]
still missing glyphs 🤷

**Comment by moudey** [comment]
@spaceCabbage Please attach `shell.log` file

**Comment by xarathos517** [comment]
New build still has the missing glyphs for me, too. Log file attached

[shell.log](https://github.com/moudey/Shell/files/10098899/shell.log)

**Comment by droosmo** [comment]
i think you have a problem in the system font please check your font **SegoeUi** **Emoji** or remplave it with the original font...

**Comment by xarathos517** [comment]
I checked the relevant fonts - SegoeUI Emoji, Segoe Fluent Icons, Segoe MDL2 Assets just in case. All appear to be installed correctly. Still no glyphs in the program or menus. Are there any other prerequisites I could be missing?

**Comment by moudey** [comment]
The glyphs will be replaced with a dynamic svg to add more elegant custom images

**Comment by moudey** [comment]
@xarathos517 Please test this [build](https://github.com/moudey/Shell/files/10127710/shell-test.zip)

**Comment by xarathos517** [comment]
That seems to work perfectly thank you!

**Comment by moudey** [comment]
@spaceCabbage Please test this [build](https://github.com/moudey/Shell/files/10127710/shell-test.zip)
