### ISSUE TITLE
Shell causing more than one file explore to appear in task manager all using lots of CPU%

### ISSUE THREAD

**Issue by otherside1** [moudey/Shell#62]
![Screenshot_20221127_102050](https://user-images.githubusercontent.com/94060774/204165171-3724acfd-dbad-4f62-885c-5cef08b14001.png)

This issue started when I installed Shell and when i removed it a day ago it stoped doing this

Win11 22H2

**Comment by moudey** [comment]
@otherside1 Are you using version 1.8 beta?

**Comment by otherside1** [comment]
Thanks that fixed it
