### ISSUE TITLE
Should scale according to display resolution and scaling.

### ISSUE THREAD

**Issue by rp1231** [moudey/shell#63]
My laptop display is 2560x1600 and at the windows recommended 150% scalling.
And my external monitor connected to my desktop is 1920x1080 at the windows recommended 100% scaling.

The desktop context menu looks fine on my laptop display but looks very large and not that crisp on the external display.

Don't know if this is because of the difference in resolutions or the difference in scaling settings.

**Comment by moudey** [comment]
I haven't addressed this issue yet because there is no additional screen that I can test on.  But I will try to buy another one soon to fix it.

**Comment by moudey** [comment]
@rp1231 Good. Taskbar issue on the second screen has also been fixed

**Comment by moudey** [comment]
Currently, some issues are being fixed, and a copy will be attached for you to review your issue.

**Comment by moudey** [comment]
@rp1231 Please test this [build](https://github.com/moudey/Shell/files/10127710/shell-test.zip)
