### ISSUE TITLE
Nvidia control panel icon is white for some reason in the 1.8 beta version

### ISSUE THREAD

**Issue by rp1231** [moudey/Shell#66]
Nvidia control panel icon is white on right clicking on the desktop for some reason in the 1.8 beta version

**Comment by SaiyajinK** [comment]
I have a similar problem also on beta 1.8 :

![Shell-nvidia_icon_ko](https://user-images.githubusercontent.com/105972098/209420208-bc3bfef0-d876-47b3-8f3e-c2cd9b1abae7.png)

I have no icon on the line.

I looked on my side and in the **shell.shl** at **line 289** we have: 

`menu(title=id.control_panel.title image='imageres.dll,-27' )`

@moudey can we set up a path that points to an .ico file on a hard disk and not to the imageres.dll file ? 
because no matter what number or what path we put no icon appears.

**Comment by moudey** [comment]
Hi @SaiyajinK Try this [build](https://github.com/moudey/Shell/files/10299005/shell-test.zip)

**Comment by SaiyajinK** [comment]
> Salut @SaiyajinKEssayez cette [ version ](https://github.com/moudey/Shell/files/10299005/shell-test.zip)

with this version the icon is present again :

![lnEdL0OAz5](https://user-images.githubusercontent.com/105972098/209472619-dd3cb940-4535-4e6c-9c2d-ce783393edbe.png)

unfortunate that this version does not take into account customization with **shell.shl** 

I hope the next version will include the fix + customization!

Merry christmas ! ++

**Comment by moudey** [comment]
The configuration file extension has been changed to `.nss`. With the addition of many new features and the `import` feature that breaks up the work of the configuration file and makes it more flexible.

**Comment by moudey** [comment]
![](https://user-images.githubusercontent.com/39198/209474948-08b104be-876e-48a9-8cf6-6bf1b2876cc9.png)
Automatically add an icon to the menu item, such as the one highlighted in red.
Open `imports/images.nss` file and find the `undo` id and add the name as shown in the following code
```
undo, 'annuler la suppression'
{
....
}
```

**Comment by SaiyajinK** [comment]
@moudey I'm new to coding and I'm going a little "without really knowing what I'm doing" hahaha ^^"
With **shell.shl** from the first beta I find myself there easily but there I have the impression that it is more complicated... I do not know why lol

In the recent version with now the **taskbar_11.nss** I managed to add menus back (go to /Terminal)

![vmware_dpFIyDgCNB](https://user-images.githubusercontent.com/105972098/209483113-6b7ce499-2ca9-4fc4-aa67-82cd47764575.png)

however when I try to incorporate file management there must be a problem as the shell no longer shows up

I copy/paste this code in the file but it no longer works after saving and restarting the explorer

```
menu(type='file|dir|drive|namespace|back' mode=multiple title='Gestion de fichiers' image=\uE0F8)
{
menu(separator=after title='Copier le chemin' image=@icon.copy_path)
{
item(where=@sel.count > 1 title='Copy (@sel.count) items selected' cmd=@sys.copy(sel(false, "\n")))
item(mode=single title="Chemin complet" tip=[sel.path, 0,0] cmd=@sys.copy(sel.path))
item(mode=single type='file|dir|back.dir' where=@sel.short.len!=sel.path.len title="Short Path" tip=[sel.short, 0,0] cmd=@sys.copy(sel.short))
item(mode=single type='file' separator=before find='.lnk' title='open file location')
separator
item(mode=single where=@sel.parent.len>3 title="Chemin racine" tip=[sel.parent,0,0] cmd=@sys.copy(sel.parent))
separator
item(mode=single type='file|dir|back.dir' title="Copier le nom et l'extension du fichier" tip=[sel.file.name,0,0] cmd=@sys.copy(sel.file.name))
item(mode=single type='file' where=@sel.file.len != @sel.file.title.len title="Copier le nom du fichier" tip=[sel.file.title,0,0] cmd=@sys.copy(sel.file.title))
item(mode=single type='file' where=@sel.file.ext.len>0 title="Copier l'extension du fichier" tip=["  " + sel.file.ext + "  ",0,0] cmd=@sys.copy(sel.file.ext))
}
separator
item(type='file|dir|back.dir|drive' title='Prendre possession' image=@icon.shield admin
cmd-line='/K takeown /f "@sel.path" @if(sel.type==1,null,"/r /d y") && icacls "@sel.path" /grant *S-1-5-32-544:F @if(sel.type==1,"/c /l","/t /c /l /q")')
separator
menu(title='Options de bascule' image=\uE1AC)
{
item(title='Afficher/masquer les fichiers système' image=\uE12E cmd='@sys.togglehidden')
item(title='Afficher/masquer les extensions de fichiers' image=icon.show_file_extensions cmd='@sys.toggleext')
}
			
menu(type='file|dir|back.dir' mode=single title='Basculer les attributs')
{
var { atrr = io.attributes(sel.path) }
item(title='Caché' checked=@io.attribute.hidden(atrr)
cmd args='/c ATTRIB @if(io.attribute.hidden(atrr),"-","+")H "@sel.path"' window=hidden)
				
item(title='Système' checked=@io.attribute.system(atrr)
cmd args='/c ATTRIB @if(io.attribute.system(atrr),"-","+")S "@sel.path"' window=hidden)
					
item(title='Lecture-seule' checked=@io.attribute.readonly(atrr)
cmd args='/c ATTRIB @if(io.attribute.readonly(atrr),"-","+")R "@sel.path"' window=hidden)
					
item(title='Archive' checked=@io.attribute.archive(atrr)
cmd args='/c ATTRIB @if(io.attribute.archive(atrr),"-","+")A "@sel.path"' window=hidden)
separator
item(title="Date de création :" keys=io.dt.created(sel.path, 'y/m/d') cmd=@io.dt.created(sel.path,2000,1,1))
item(title="Dernière modification :" keys=io.dt.modified(sel.path, 'y/m/d') cmd=@io.dt.modified(sel.path,2000,1,1))
item(title="Dernier accès :" keys=io.dt.accessed(sel.path, 'y/m/d') cmd=@io.dt.accessed(sel.path,2000,1,1))
}

menu(mode=single type='file' find='.dll|.ocx' separator=before title='Register Server' image=\uea86)
{
item(title='Register' admin cmd='regsvr32.exe' args='@sel.path.quote')
item(title='Unregister' admin cmd='regsvr32.exe' args='/u @sel.path.quote')
}

menu(mode=single type='back')
{
menu(separator=before title='Nouveau dossier' image=\uE0E5)
{
item(title='Jour de la semaine' cmd=@io.dir.create(sys.datetime("ymdHMSs")))
item(title='Identificateur GUID' cmd=@io.dir.create(str.guid))
}
				
menu(title='Nouveau fichier' image=\uE108)
{
var { dt = sys.datetime("ymdHMSs")}
item(title='Fichier .txt' cmd=@io.file.create('@(dt).txt', 'Hello World!'))
item(title='Fichier .xml' cmd=@io.file.create('@(dt).xml', '<root>Hello World!</root>'))
item(title='Fichier .json' cmd=@io.file.create('@(dt).json', '[]'))
item(title='Fichier .html' cmd=@io.file.create('@(dt).html', "<html>\n\t<head>\n\t</head>\n\t<body>Hello World!\n\t</body>\n</html>"))					
}
}
}
```

look : 

![vmware_qfyduY0yfb](https://user-images.githubusercontent.com/105972098/209483242-792bed7c-fdfa-4be8-82dc-756c687cc359.png)

really strange... an idea ?

it would be nice to have the same default menus as on the old version (contextual menu and taskbar) at first launch and we configure it as we wish afterwards

**Comment by moudey** [comment]
These commands have been moved to the command scope so an error occurs.

```
sys.copy to command.copy
sys.togglehidden to command.togglehidden
sys.toggleext to command.toggleext
```
The way the following property values are written has also been changed.
```
mode=mode.single 
or
mode="single"

vis=vis.remove
or
vis="remove"
```
The `default` section has also been changed to `set`.
```
set
{
    theme
    {
        name="modern"
        dark=true
        background.effect = 3
    }
}
```
All changes will be documented.

The configuration file can now be split and made more flexible, see the following example.
```
dynamic
{
    import 'imports/file-mange.nss'
    import if(sys.is11 and this.count == 0, 'imports/taskbar_11.nss')
}
```

file-mange.nss
```
menu(type='file|dir|drive|namespace|back' mode=mode.multiple title='Gestion de fichiers' image=\uE0F8)
{
    menu(separator=after title='Copier le chemin' image=@icon.copy_path)
    {
        item(where=@sel.count > 1 title='Copy (@sel.count) items selected' cmd=@command.copy(sel(false, "\n")))
        item(mode=single title="Chemin complet" tip=[sel.path, 0,0] cmd=@command.copy(sel.path))
        item(mode=single type='file|dir|back.dir' where=@sel.short.len!=sel.path.len title="Short Path" tip=[sel.short, 0,0] cmd=@command.copy(sel.short))
        item(mode=single type='file' separator=before find='.lnk' title='open file location')
        separator
        item(mode=single where=@sel.parent.len>3 title="Chemin racine" tip=[sel.parent,0,0] cmd=@command.copy(sel.parent))
        separator
        item(mode=single type='file|dir|back.dir' title="Copier le nom et l'extension du fichier" tip=[sel.file.name,0,0] cmd=@command.copy(sel.file.name))
        item(mode=single type='file' where=@sel.file.len != @sel.file.title.len title="Copier le nom du fichier" tip=[sel.file.title,0,0] cmd=@command.copy(sel.file.title))
        item(mode=single type='file' where=@sel.file.ext.len>0 title="Copier l'extension du fichier" tip=["  " + sel.file.ext + "  ",0,0] cmd=@command.copy(sel.file.ext))
    }
    separator
    item(type='file|dir|back.dir|drive' title='Prendre possession' image=@icon.shield admin
    cmd-line='/K takeown /f "@sel.path" @if(sel.type==1,null,"/r /d y") && icacls "@sel.path" /grant *S-1-5-32-544:F @if(sel.type==1,"/c /l","/t /c /l /q")')
    separator
    menu(title='Options de bascule' image=\uE1AC)
    {
        item(title='Afficher/masquer les fichiers système' image=\uE12E cmd='@command.togglehidden')
        item(title='Afficher/masquer les extensions de fichiers' image=icon.show_file_extensions cmd='@command.toggleext')
    }
                
    menu(type='file|dir|back.dir' mode=single title='Basculer les attributs')
    {
        var { atrr = io.attributes(sel.path) }
        item(title='Caché' checked=@io.attribute.hidden(atrr)
        cmd args='/c ATTRIB @if(io.attribute.hidden(atrr),"-","+")H "@sel.path"' window=hidden)
                        
        item(title='Système' checked=@io.attribute.system(atrr)
        cmd args='/c ATTRIB @if(io.attribute.system(atrr),"-","+")S "@sel.path"' window=hidden)
                            
        item(title='Lecture-seule' checked=@io.attribute.readonly(atrr)
        cmd args='/c ATTRIB @if(io.attribute.readonly(atrr),"-","+")R "@sel.path"' window=hidden)
                            
        item(title='Archive' checked=@io.attribute.archive(atrr)
        cmd args='/c ATTRIB @if(io.attribute.archive(atrr),"-","+")A "@sel.path"' window=hidden)
        separator
        item(title="Date de création :" keys=io.dt.created(sel.path, 'y/m/d') cmd=@io.dt.created(sel.path,2000,1,1))
        item(title="Dernière modification :" keys=io.dt.modified(sel.path, 'y/m/d') cmd=@io.dt.modified(sel.path,2000,1,1))
        item(title="Dernier accès :" keys=io.dt.accessed(sel.path, 'y/m/d') cmd=@io.dt.accessed(sel.path,2000,1,1))
    }

    menu(mode=single type='file' find='.dll|.ocx' separator=before title='Register Server' image=\uea86)
    {
        item(title='Register' admin cmd='regsvr32.exe' args='@sel.path.quote')
        item(title='Unregister' admin cmd='regsvr32.exe' args='/u @sel.path.quote')
    }

    menu(mode=single type='back')
    {
        menu(separator=before title='Nouveau dossier' image=\uE0E5)
        {
            item(title='Jour de la semaine' cmd=@io.dir.create(sys.datetime("ymdHMSs")))
            item(title='Identificateur GUID' cmd=@io.dir.create(str.guid))
        }
                        
        menu(title='Nouveau fichier' image=\uE108)
        {
            var { dt = sys.datetime("ymdHMSs")}
            item(title='Fichier .txt' cmd=@io.file.create('@(dt).txt', 'Hello World!'))
            item(title='Fichier .xml' cmd=@io.file.create('@(dt).xml', '<root>Hello World!</root>'))
            item(title='Fichier .json' cmd=@io.file.create('@(dt).json', '[]'))
            item(title='Fichier .html' cmd=@io.file.create('@(dt).html', "<html>\n\t<head>\n\t</head>\n\t<body>Hello World!\n\t</body>\n</html>"))                  
        }
    }
}
```

**Comment by SaiyajinK** [comment]
@moudey I will wait for the documentation.

For file management it's good I copied pasted with the modifications and it appears again!

on the other hand, a lot of icons are no longer present, there is also a name problem on Windows Terminal in the Terminal section (as well as the missing CMD/powershell/ownership icons etc) :

> on the left locally on the right on my vm

![6tYwih2sR5](https://user-images.githubusercontent.com/105972098/209499910-c1be21aa-46b4-497f-a099-7e14762af4ca.png)
![8wMyAgXefm](https://user-images.githubusercontent.com/105972098/209499913-679b033c-274e-4216-9864-5a30bc5a8656.png)
![iCpOIhzMtE](https://user-images.githubusercontent.com/105972098/209499914-607ec7d2-97c2-4c72-aebd-df8aa0ad8a5e.png)
![ZGw9a5xbwQ](https://user-images.githubusercontent.com/105972098/209499915-dbb46821-8075-44b1-9d2f-dd6b6c947c9b.png)

I notice according to the images different icons: **@icon.admin shield** or **image=\uE218**

where to find these icons? how to know their name and their location to put different ones?

one last thing, I also noticed that the "go to" menu no longer appeared in the right click of the taskbar, whereas on the old version beta 1.8 it was the case.

![rc](https://user-images.githubusercontent.com/105972098/209500612-7a3ea215-7af0-46ea-9989-ba972ed3d931.png)

 How to put it back?

**Comment by moudey** [comment]
Currently using `svg` instead of `icon` scope until it is fixed.

>where to find these icons? how to know their name and their location to put different ones?

The predefined icon scope identifiers can be found at this [link](https://nilesoft.org/docs/functions/id) and
You can explore the glyphs through this [link](https://nilesoft.org/gallery/glyphs)

>one last thing, I also noticed that the "go to" menu no longer appeared in the right click of the taskbar, whereas on the old version beta 1.8 it was the case.

To show the item in all menu, set the value of the `type` property to "*"
```
menu(type='*' title='Goto')
{
...
}
```

**Comment by SaiyajinK** [comment]
@moudey Thank you ! Indeed it is immediately clearer with the links you provide!
I was able to replace the icons I wanted!

I managed to find how to remove the section separators I simply removed the argument **separator=both**

concerning the customization of the appearance I added the following arguments in **shell.nss**:

```
shell
{
	set
	{
		theme
		{
			name="modern"
			
			// auto | none = 0 | transparent = 1 | blur = 2 | acrylic = 3 | mica = 4 | tabbed = 5
			background.effect=3
			
			//background.color=#303030
			
			//background.opacity=75
			
			image.scale=1
			image.align=1
			
			shadow
			{
				enabled=0
				color=#000000
				opacity=10
				size=1
				//offset=2
			}
			
			border
			{
				enabled=1
				size=1
				radius=2
				//color=[color.accent, 100] - backup
				color=[#5d5d5d, 40]
				//opacity=100
				padding = [4, 6]
			}
			
			font
			{
				//size=14
				//weight=1 // value from 1 to 9
			}
			
			item
			{
							//text.normal=[#000,20]
				//text.select=[auto,50]
				back
				{
				//normal = 0
				//normal-disabled = 0
				select = [#b4b4b4, 15]
				//select-disabled = [#fff,10]
				}
				
				//border=[#b4b4b4, 20]
				
				//padding = [left, top, right, bottom]
				//padding = [left+right, top+bottom]
				//padding = all
				//padding.left = 4
				//padding.right = 4
				//padding.top = 4
				//padding.bottom = 4
				
				//margin = [left, top, right, bottom]
				//margin = [left+right, top+bottom]
				//margin = all
				//margin.left = 2
				//margin.right = 2
				//margin.top = 2
				//margin.bottom = 2
				
				//radius=1
			}
		}

		exclude.where = !process.is_explorer
	}
	
	images import 'imports/images.nss'
	
	dynamic
	{
		import if(sys.is11 and this.count == 0, 'imports/taskbar_11.nss')
	}
}
```

Except that I notice that by adding the arguments for the font size and that the latter is below the default size the icon of the nvidia control panel is no longer displayed (size at 13 and below KO, but size at 14 and over OK).

Another question: what language is used in the software ?

because I added a category where I would like to be able to run this:

![lBzGoKcCti](https://user-images.githubusercontent.com/105972098/209524143-67aef077-9c1c-4eec-a7de-53cdad895dc9.png)

- delete temporary files

- launch a specific program installed on my pc by pointing to the executable of the latter

- launch a second specific program installed on my pc by pointing to the executable of the latter

- Rebuild icon cache

- restart explorer (concerning the name, in French it is "redémarrer l'explorateur" except that the apostrophe `'` is put in duplicate and considers that the command stops here and not at the end of the name. It's hard to explain maybe a picture will help you understand :

![6bLXZzH9FN](https://user-images.githubusercontent.com/105972098/209525684-2bdcef7e-1fa0-44c8-92d4-9893dbd2f900.png)

thank you for the answer ++

**Comment by moudey** [comment]
> can we put a custom icon also for the nvidia panel? to put this one for example? image=\ue260 ?

> can we integrate a line like on the old versions which defines the maximum number of characters to display and if it exceeds that create another menu?

```
static
{
    item(where=this.title.len > 30 tip=this.title parent=@id.more_options.title)
    item(type='desktop' find='nvidia panel' image=[\ue260, #0a0])
}

dynamic
{
    menu(type='*' mode="multiple" title=@id.more_options.title)
    {
    }

    item(title="redémarrer l'explorateur")
    // or
    item(title='redémarrer l@char(39,1)explorateur2')
}
```
>Another question: what language is used in the software ?

Shell is written in C++, and the script, is built somewhat similarly to C++, C#, JavaScript, and CSS.

**Comment by SaiyajinK** [comment]
@moudey oké thank you it's good I managed to implement everything as I wanted.

![hRh5ZDPzQ8](https://user-images.githubusercontent.com/105972098/209601231-757cdc8e-0d27-4f9a-97df-9d51c23174a0.png)

On the other hand, the icon of the nvidia panel always remains the same it does not change despite this line inserted:

`item(type='desktop' find='nvidia panel' image=[\ue260, #0a0])`

![ScXEwhmL93](https://user-images.githubusercontent.com/105972098/209674501-c669a2db-6ae7-4a7b-9ba7-ef895359b97c.png)

An idea ?

**Comment by moudey** [comment]
Put nvidia item before any item to apply change s.

```
static
{
    item(type='desktop' find='nvidia panel' image=[\ue260, #0a0])

    item(where=this.title.len > 30 tip=this.title parent=@id.more_options.title)
}
```

**Comment by SaiyajinK** [comment]
@moudey quick and concise ! Amazing ! 

![HAIMd0Zo6C](https://user-images.githubusercontent.com/105972098/209679791-c720da5c-959d-4eac-90dc-d9eea2954bbd.png)

thank you very much for all the answers ! :)
