### ISSUE TITLE
Glyphs Gallery not showing + More Glyphs

### ISSUE THREAD

**Issue by Natejoestev** [moudey/Shell#67]
Glyphs 232, 233, 23B, 23C, and 261 do not load on the gallery
example:
![image](https://user-images.githubusercontent.com/85044853/204957360-697b6852-972f-4ebb-8d7a-e567963f62f7.png)
 
i would also like some other icons glyphs like: google/internet browser, arduino

(also, on the contact page this should be "bugs" not "a bugs"😄)
![image](https://user-images.githubusercontent.com/85044853/204957012-bb744e21-1cc0-4edb-a804-9521e644387d.png)

**Comment by moudey** [comment]
Thanks @Natejoestev These glyphs are currently empty.
