### ISSUE TITLE
vscode submenu doesn't do anything

### ISSUE THREAD

**Issue by pourmand1376** [moudey/Shell#69]
Hi, Thanks for creating this great extension. 

I suppose using `Develop > Editors > vscode` menu should bring up vscode. But It does nothing! What Should I do?

- Windows version: 22H2 (OS Build 22612.900)
- Shell version; 1.7
- VScode info
    Version: 1.73.1 (user setup)
    Commit: 6261075646f055b99068d3688932416f2346dd3b
    Date: 2022-11-09T04:27:29.066Z
    Electron: 19.0.17
    Chromium: 102.0.5005.167
    Node.js: 16.14.2
    V8: 10.2.154.15-electron.0
    OS: Windows_NT x64 10.0.22621
    Sandboxed: No

**Comment by moudey** [comment]
Hi @pourmand1376 Enter vscode path in cmd property
```
item(title='vscode' image=[\uE272, #22A7F2] cmd='path/to/vscode/code.exe' args='"@sel.path"')
```

**Comment by 91XX** [comment]
@moudey item(title='vscode' image=[\uE272, #22A7F2] cmd='C:\Users\ANXIETY\AppData\Local\Programs\Microsoft VS Code\Code.exe' args='"@sel.path"') is this correct? because it's not working for some reason...

**Comment by 91XX** [comment]
@moudey item(title='vscode' image=[\uE272, #22A7F2] cmd='C:\Users\ANXIETY\AppData\Local\Programs\Microsoft VS Code\Code.exe' args='"@sel.path"') is this correct? Because vscode only opens if I right-click on the Desktop and not when in a folder

**Comment by pourmand1376** [comment]
Hi @moudey, Thanks for answering. Where should I enter this line?

**Comment by moudey** [comment]
> Hi @moudey, Thanks for answering. Where should I enter this line? It seems that there should be a config file. But I am unable to find it.

go to Shell directory Open "shell.shl" file with notepad and then search for vscode

**Comment by StevenElev11n** [comment]
Hi @moudey

I edited the cmd='code.exe' to cmd='code' and it's working fine.

**Comment by pourmand1376** [comment]
Thanks, @moudey @StevenElev11n 
I also changed `code.exe` to `code` and it is working just fine.

Maybe it is better to leave `code` as default rather than `code.exe`. What do you say?
