### ISSUE TITLE
Feature request : Add acrylic blurry background effect

### ISSUE THREAD

**Issue by Marvinoo** [moudey/Shell#7]
There are already some beautiful theme colors ryt there but adding acrylic blurry option with ability to control the opacity level would be really awesome! 
Is that even possible?

**Comment by moudey** [comment]
Yes, the effect of transparency and acrylic will be added later.

**Comment by HuyHung1408** [comment]
Looking forward for this

**Comment by moudey** [comment]
@HuyHung1408 This feature is being worked on and will be available in the next update.

**Comment by yatoya** [comment]
Thers is command
transparency = 90
		tip
		{
			enabled = 1
			opacity = 100
but hanging valus does nothing.
How does it work?

**Comment by moudey** [comment]
> Thers is command transparency = 90 tip { enabled = 1 opacity = 100 but changing values does nothing. How does it work?

@yatoya The transparency option for items and tip is not currently enabled. But it is being worked on in the new version.
