### ISSUE TITLE
[Bug] High CPU usage in Windows Explorer when Nilesoft Shell is active

### ISSUE THREAD

**Issue by onurbbr** [moudey/Shell#70]
I noticed that the CPU usage of Windows Explorer is high with Nilesoft Shell. When I disable Nilesoft, the problem goes away.

With Nilesoft Shell disabled:
![Screenshot_20221202_123826](https://user-images.githubusercontent.com/47495526/205268430-8887703d-b32c-4510-8bae-bb2d3a95dc96.png)

With Nilesoft Shell enabled:
![Screenshot_20221202_130250](https://user-images.githubusercontent.com/47495526/205268551-64f385d6-75c5-4eca-9898-4602a9a224e5.png)

I don't know how to get logs. Write here how to get logs. After writing I can send you the logs.

Btw this is my system info: 
OS Name:                   Microsoft Windows 11 Pro
OS Version:                 10.0.22623.1020 Build 22623 (Insider Beta)

**Comment by moudey** [comment]
Hi @onurbbr this issue has been fixed beta version, please refer [this](https://github.com/moudey/Shell/issues/37)

**Comment by onurbbr** [comment]
> Hi @onurbbr this issue has been fixed beta version, please refer [this](https://github.com/moudey/Shell/issues/37)

I am currently using the stable version. I installed it with Scoop package installer. When will the new stable update come?

**Comment by moudey** [comment]
@onurbbr Soon, about a week

**Comment by onurbbr** [comment]
Thank you for your work. Have a nice day.

**Comment by onurbbr** [comment]
Thank you for your work. Have a nice day.
