### ISSUE TITLE
Items' names are not displayed properly

### ISSUE THREAD

**Issue by StevenElev11n** [moudey/Shell#71]
Item's names are not displayed properly:
Screenshot 1:
<img width="341" alt="PowerShell's Name" src="https://user-images.githubusercontent.com/64677064/205280804-1a7032af-b0f9-4b07-9b4d-d11ef2a3dab6.png">
Screenshot 2:
<img width="266" alt="Name cutoff" src="https://user-images.githubusercontent.com/64677064/205280972-a14d54d3-ffcb-4291-8e70-7975bbab2442.png">
Screenshot 3:
<img width="332" alt="Name cutoff 2" src="https://user-images.githubusercontent.com/64677064/205281076-6ebe5642-abde-4726-8460-1f48cd0e86cc.png">

Edit: Windows 11 | Shell ver 1.8

**Comment by moudey** [comment]
Thanks @StevenElev11n Please test this [build](https://github.com/moudey/Shell/files/10127710/shell-test.zip) and provide me the display resolution and scale values

**Comment by StevenElev11n** [comment]
> Thanks @StevenElev11n Please test this [build](https://github.com/moudey/Shell/files/10127710/shell-test.zip) and provide me the display resolution and scale values

The test build displayed perfectly with the resolution of 3840 x 2160 and scale of 150%

**Comment by moudey** [comment]
Is there an issue with `NVIADI Cotrol Panel` icon?

**Comment by StevenElev11n** [comment]
> Is there an issue with `NVIADI Cotrol Panel` icon?

Yes, there is still an issue with NVIDIA icon (no icons were displayed in the test build, but it was displayed as an white icon in v1.8)

**Comment by StevenElev11n** [comment]
Is there a quick fix in v1.7 for displaying the proper name for the PowerShell in the image below:
![image](https://user-images.githubusercontent.com/64677064/205287915-8ede541b-a4d7-434a-83fe-b71214856d69.png)

**Comment by StevenElev11n** [comment]
Should I edit title='@appx.name("WindowsTerminal")@elevated' to title='Windows Terminal@elevated'?

**Comment by moudey** [comment]
This function `appx.name` uses limited resources from system functions, so it returns only available data.

**Comment by StevenElev11n** [comment]
> This function `appx.name` uses limited resources from system functions, so it returns only available data.

The function may use less resources but apparently it's not working or displaying name properly. Should we implement different approach?

**Comment by moudey** [comment]
Use function `id.windows_terminal.title` to return the name of `Windows  Terminal`

**Comment by moudey** [comment]
Do not pass arguments to the function `id.windows_terminal.title`
```
id.command_prompt.title
id.open_command_prompt.title
id.open_windows_powershell.title
```
