### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by ThePython10110** [moudey/Shell#76]
I'm trying to get rid of options I will never use in the taskbar's right-click menu (not Win+X), but they are still there. There are no errors in the log file.

Default menu (without shell)
![image](https://user-images.githubusercontent.com/87204246/205512882-0992605f-8dbc-429b-a2ab-482c01ccf890.png)

After registering:
![image](https://user-images.githubusercontent.com/87204246/205512862-773c84ae-6a98-4af3-b34e-e0ff8c9d2caa.png)

Code:
```
shell 
{
	default
	{
		theme
		{
			name="modern"
			image.align=1
			layout.popup=auto
		}
		//exclude.where = !process.is_explorer
	}
	
	static
	{
		item(where='taskbar' find='Cortana' vis='Disable')
		item(find='Task View' vis='Disable')
		item(find='People' vis='Disable')
		item(find='Ink' vis='Disable')
		item(find='touch' vis='Disable')
	}
	
	dynamic
	{
				
	}
}
```

**Comment by moudey** [comment]
You must pass a boolean to `where` property

In the next update, the `type` property has been added to the static items so that the items can be filtered accurately.

```
item(find='Cortana' vis='Disable')
```

**Comment by ThePython10110** [comment]
I tried a lot of things, and it still doesn't work.
I tried using `where=true` as well as `where=window.is_taskbar` (which is not in the documentation anywhere).
I also tried `vis=remove` (which is _nowhere_ in the documentation), `vis=0`, `vis=1`, `vis=hidden`, `vis=disable`, and `vis=disabled`.

No change...

**Comment by moudey** [comment]
Try this [build](https://github.com/moudey/Shell/files/10149605/shell-test.zip)
New functions and option values will be explained with the next update.

**Comment by ThePython10110** [comment]
That works.
