### ISSUE TITLE
Win+X menu?

### ISSUE THREAD

**Issue by ThePython10110** [moudey/Shell#77]
Is there any way to add/modify items in the Win+X menu? I feel like there should be, since it is affected by the theme.
I tried this:
`item(title='This should appear everywhere')`
And it appeared everywhere but the Win+X menu.

**Comment by moudey** [comment]
I try not to make a mess of all menus. Therefore, other options will be added to adjust the display of dynamic items

**Comment by moudey** [comment]
Refer to #78
