### ISSUE TITLE
v1.5 Typos [EN]

### ISSUE THREAD

**Issue by kevin122673** [moudey/shell#8]
File manage > Toggle Optoins

	Current:
	menu(title='Toggle Optoins' image=\uE1AC)
 		
	Correct:	
	menu(title='Toggle Options' image=\uE1AC)

Power > Shotdown
	Current:
	item(title='Shot down' image=inherit cmd='shutdown' arg='/s')

	Correct:
	item(title='Shut down' image=inherit cmd='shutdown' arg='/s')

File manage > Regester Server
	Current:
	menu(mode=single type='file' find='.dll|.ocx' separator=before title='Regester Server' image=\uea86)

	Correct:
	menu(mode=single type='file' find='.dll|.ocx' separator=before title='Register Server' image=\uea86)

File manage > Regester Server > **
	Current:
	item(title='Regster' admin cmd='regsvr32.exe' args='@sel.path.quote')
	item(title='Unregster' admin cmd='regsvr32.exe' args='/u @sel.path.quote'

	Correct:
	item(title='Register' admin cmd='regsvr32.exe' args='@sel.path.quote')
	item(title='Unregister' admin cmd='regsvr32.exe' args='/u @sel.path.quote'

**Comment by moudey** [comment]
Thank you @kevin122673  for this contribution.
