### ISSUE TITLE
How would I add an option that will copy the name of the files I select to my clipboard?

### ISSUE THREAD

**Issue by Zliced13** [moudey/Shell#89]
Hello @moudey!

I would like to be able to add a copy file names into the Nilesoft context menu, specifically in the **File Manage** submenu. I would like it to copy each file name in a pattern like this; Ex. "WFInfo.zip", "TranslucentFlyouts-Main.zip", "value.ps1".
![(explorer)f29878_12-14-2022](https://user-images.githubusercontent.com/101912712/207687489-3f562339-8061-4eae-8bdc-47af88363e86.jpg)

**Comment by moudey** [comment]
Hello @Zliced13

This `sel.files.name` function does not include quotation marks. But I will support it in the next update
You can use this method to work around the quotation mark with the separator

```
item(mode=multiple title='Copy files name' cmd=sys.copy('"@sel.files.name('","')"'))
```

NOTE: `sys.copy` It will be moved under command scope

**Comment by Zliced13** [comment]
@moudey Thank you for your hard work. However, if there was a tweak I would add to this, I would like it to add a comma after every file name.

Current Output:
`"WFInfo.zip TranslucentFlyouts-Main.zip value.ps1 Install-or-Uninstall-Context-Menu.ps1"`

Preferred Output:
`"WFInfo.zip", "TranslucentFlyouts-Main.zip", "value.ps1", "Install-or-Uninstall-Context-Menu.ps1"`

**Comment by moudey** [comment]
What is version used?

**Comment by moudey** [comment]
Try this [build](https://github.com/moudey/Shell/files/10231493/shell-test.zip)

```
item(mode="multiple" title='Copy files name' cmd=command.copy(sel.files.name(true,",")))
```

**Comment by Zliced13** [comment]
> What is version used?

1.7

**Comment by Zliced13** [comment]
I just tested it, it works for me greatly. Thank you, @moudey.
