### ISSUE TITLE
Updated to 1.5 and now dark mode doesn't work

### ISSUE THREAD

**Issue by Marvinoo** [moudey/shell#9]
It seems there's a bug or something that preventing the dark mode from turning on in the last version, however [the rule is set correctly inside the Shell.shl file](https://i.imgur.com/wFyGVDw.png) the context menu's color [stills white.](https://i.imgur.com/mB8yyje.png)

**Comment by moudey** [comment]
theme and view values ​​are assigned this way

```
view = view.auto
theme = theme.dark
```
