### ISSUE TITLE
Shell Extension Customization/Editing/Moving?

### ISSUE THREAD

**Issue by IdrisQe** [moudey/Shell#90]
Hi, I was just wondering - not sure if it's even feasible - but are there plans to one day allow modification of shell extensions?
Assuming this isn't already possible of course, but the docs don't really say anything about it. I know they're handled differently than regular context menu items, so I get if this isn't doable.

By shell extensions I mean things like the 7-Zip/Winrar submenus and all their functions, "Scan file with [Antivirus of choice]" items, things like that. I originally wanted to try Shell to see if I could move a bunch to specific sub-menus, since I don't use them often but still need access to them for convienience.

**Comment by moudey** [comment]
Hi @IdrisQe,

This is one of Shell's unique features, where you can modify, move, and delete existing items, whether they are system items or belong to a third party, without modifying the system registry.

Static section is responsible for controlling these items, and it has multiple options to search and filter for the items to be targeted. See the following examples

```
static
{
   // Remove 'Delete' item
    item(find='"delete"' vis=0)

    // Move '7-Zip' item to "group 1" submenu.
    item(find='7-zip' parent="/group 1")

    // Search for a menu-type item within a sub-menu and modify name, image, and status
    item(where=this.type==2 find=['open archive', "/group 1/7-zip"] image=#0f0 title=(this.title + "\tHello World!")  vis=2)
}
	
dynamic
{
    menu(mode="multiple" title="group 1")
    {
        item(title="item 1" cmd-line="/k echo Hello World!")
    }
}
```
Use this [build](https://github.com/moudey/Shell/files/10231493/shell-test.zip) as it supports all operations on static objects

See this too #35 #85

**Comment by IdrisQe** [comment]
Oh, fantastic! This actually looks quite simple, I'll have to look into it a bit more when I have time, thank you!
