### ISSUE TITLE
need help for a command to change icon please

### ISSUE THREAD

**Issue by gsrd90** [moudey/Shell#94]
hello I was redirected to your application on another forum and I need help because I know absolutely nothing about the command line.

as you can see on the capture below I would like to set up a menu to directly change the icon of a file, a folder or a drive:

![TqPHrI87F0](https://user-images.githubusercontent.com/108171779/209772271-75ac363d-3ef5-4a18-aef4-a9e81dd6dc2b.png)

the menu is indeed present in the contextual menu but I have no idea what command to enter to directly open the surrounded frame? without having to click on property, personalization and change icon, I want to directly open the frame circled in purple

can you help me to accomplish this please it would be greatly appreciated thank you

I'm on windows 10 22H2 19045.2364 and I'm using stable version 1.7 of shell and I use startisback

**Comment by moudey** [comment]
This option has been added and will be available in the next update through this function `icon.box`

**Comment by gsrd90** [comment]
> This option has been added and will be available in the next update through this function `icon.box`

Hello and thank you for your answer
it's great to be able to integrate my request thank you!
when will this new version be available please?

because from what I understood in the various tickets of the project, the new versions "are no longer the same" as the version I am currently using, is that right?

**Comment by moudey** [comment]
Most of the changes are in the settings section, and only the name of the config file extension has been changed. But you can transfer the items from the old config file without problems

**Comment by gsrd90** [comment]
ok i can't wait to get my hands on it ! when does this version including this function come out?

**Comment by moudey** [comment]
Hi @gsrd90 Please try this [build](https://github.com/moudey/Shell/files/10329755/shell-test.zip)

Add this code to `dynamic` section:
```
item(title='test icon.box' image=#f00 cmd arg='/k echo @icon.box('imageres.dll', 1)')
```

**Comment by gsrd90** [comment]
Hi,
I tried with the version that you advise me to use I added the line in dynamic I have the test icon present in the menu :

![IDb5CHepDJ](https://user-images.githubusercontent.com/105972098/210279089-328c1c43-69fb-481a-a6f9-8bf43d16a9d4.png)

by clicking on it, I have the icon panel that opens directly, it's great:

![zMbqvzwAE3](https://user-images.githubusercontent.com/108171779/210279147-773d32ab-8451-43e0-8394-636d0707eb6f.png)

except that when I click on ok, I have a black window which is displayed and when I close it the icon remains unchanged:

![NYKnJTbpUl](https://user-images.githubusercontent.com/108171779/210279181-1d594dea-ee1e-49fb-b629-38c2a284e871.png)

when I click on ok to select the icon I want it would be possible that it selects it without having this black window that appears?

thank you for your reply

**Comment by moudey** [comment]
`icon.box` returns the path of the file with the index of the icon so that it can be passed to a third party for processing.

**Comment by gsrd90** [comment]
it is impossible for us to define a personalized icon with this method in two clicks?
i mean by that, just click on the icon you choose and do ok and that changes it?
because with the current method, apart from having the path and the number of the exact icon, it does not change directly in two clicks, and to change we always have to go through the traditional method?

**Comment by moudey** [comment]
A shell repository provides auxiliary functions for the context menu that makes dealing with other programs flexible, as it provides the creation of a special shell extension for each process. For example: the "icon.box" function returns the path of the file with the index. You only need to pass this data to the system if direct functions are provided, or to a third party to implement the command to change the icon for the folder.
