### ISSUE TITLE
WinSCP on Win 11 taskbar menu

### ISSUE THREAD

**Issue by burfo** [moudey/Shell#97]
The default menus has a WinSCP item on the Windows 11 taskbar context menu that is defunct, does nothing when clicked:
![image](https://user-images.githubusercontent.com/7247105/210197653-765c2a73-4949-429e-aba2-4c7279088a10.png)

In shell.shl:
```
item(title='WinSCP' image cmd='D:\config\Programs\network\WinSCP\WinSCP.exe' dir)
```
Even if a person has WinSCP installed, it's probably not at that path.  Perhaps we can improve the defaults to be more useful to everybody?

**Comment by moudey** [comment]
Thank you, @burfo. I forgot to remove this item from the configuration file.
